# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

## Site settings
title: Broz-statistics 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bozenne.github.io" # the base hostname & protocol for your site, e.g. http://example.com
description: Welcome to my professional website. You will find a brief description of my research, teaching material, and information about my consulting activity at NRU.


## Personal details
email: brice.ozenne@nru.dk
github_username:  bozenne
orcid: 0000-0001-9694-2956
avatar: img/photoId.jpeg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
