#+TITLE:
#+Author: Brice Ozenne

# header
#+BEGIN_EXPORT latex
\begin{tabular*}{7in}{l@{\extracolsep{\fill}}r}
	\textbf{\Large Brice Ozenne} & \textbf{\today} \\
\end{tabular*}

\bigskip

\begin{minipage}{0.2\linewidth}
\includegraphics[width=\linewidth]{photoId.png}
\end{minipage}
\begin{minipage}{0.75\linewidth}
\begin{tabular*}{7in}{ll@{ }l}
	Nationality&:& french  \\
	Age&:& 35  \\
	Professional email&:& \url{broz@sund.ku.dk} \\ 
        Personal Website&:& \url{https://bozenne.github.io/} \\
        Github&:& \url{https://github.com/bozenne/} \\
\end{tabular*}
\end{minipage}
#+END_EXPORT

\bigskip

* Current position                                          :ignore:
#+LaTeX: \resheading{Current position}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
	October 2023- Now:& \textbf{Associate professor in biostatistics} with a shared position between \\ [2mm]
	& - a research unit in biostatistics \\
	& \href{https://biostat.ku.dk/staff_/?pure=en/persons/540231}{Section of Biostatistics}, University of Copenhagen (KU) \\
	& \O{}ster Farimagsgade 5, 1014 Copenhagen, Denmark \\ [2mm]
	& - a research unit in neuroscience \\
	& \href{https://nru.dk/index.php/staff-list/post-docs/110-brice-ozenne}{Neurobiology Research Unit} (NRU) \\
	& Copenhagen University Hospital, Rigshospitalet \\
	& Building 6931, Blegdamsvej 9, DK-2100 Copenhagen, Denmark \\ [2mm]
\end{tabular}
#+END_EXPORT
where I do research in biostatistics along with a consulting and teaching activity in statistics.

\bigskip

My research work is organized around three topics:
- the development of *multivariate models* for data analysis in
  neuroscience, mainly latent variable models (LVM) and mixed models (LMM) - see publications
  cite:ebert2019molecular,stenbaek2017brain,fisher2017bdnf. From a
  methodological point of view, I study how to perform statistical
  *estimation and inference in small samples* citep:ozenne2020small as
  well as efficient corrections for *multiple testing*
  citep:ozenne2022controlling. These developments are available in the
  R packages =lavaSearch2= (LVM) and =LMMstar= (LMM). 
  
  # \newline *Main collaborators*: Esben Budtz-Jørgensen & Julie Forman (KU, Denmark)

- the analysis of registry data in presence of *right-censoring*,
  *competing risks*, and *confounding* *competing risks*. A typical
  application is the comparison of preventive treatments of
  cardiovascular diseases
  citep:staerk2016ischaemic,staerk2017resumption,staerk2018standard. Based
  on the *semi-parametric theory*, I have developped a robust
  estimator of the average treatment effect and derived its asymptotic
  distribution via its influence function
  citep:ozenne2020estimation. This has been implemented in the =ate=
  function of the =riskRegression= R package. 

  # \newline *Main collaborators*: Thomas Alexander Gerds & Thomas Scheike (KU, Denmark)

\clearpage

- the extension of *generalized pairwise comparisons* (GPC), e.g. to
  handle right-censoring citep:ozenne2021asymptotic, restriction time
  citep:piffoux2024restricted, or perform reliable statistical
  inference with more than two groups. GPC is a method able to handle
  multiple and heterogeneous endpoints which is especially relevant to
  assess the benefit-risk balance of a treatment. A typical
  application is the evaluation of chemotherapies where jointly
  considering gains in survival and side effects is critical
  citep:peron2016net,peron2016assessment. \newline

  # \newline *Main collaborators*: Julien Péron & Max Piffoux (HCL, France), \newline \hphantom{*Collaborators*:} Michaël De Backer & Marc Buyse (IDDI,  Belgium)

- Handling delayed endpoint when designing and analyzing *group
  sequential trials*. A typical application would be a trial on
  anti-depressant where the outcome is the depression score after 1
  month of treatment and one would like to have one or several interim
  analyzes to have the possibility to stop early for efficacy of
  futility. This work has lead to a tutorial paper
  citep:baayen202Xdesign and a companion software package called
  =delayedGSD= hosted on Github. It includes sample size
  calculation, determination of efficacy/futility/decision boundaries,
  p-values, confidence intervals, and median unbiased
  estimates. \newline

  # *Main collaborators*: Paul Blanche (KU, Denmark) & Corine Baayen (Ferring, Denmark)

** /Other domains of interest in statistics:/
#+LaTeX: \begin{minipage}{0.45\linewidth} 
- Mediation analysis
- Smoothing splines
#+LaTeX: \end{minipage}
#+LaTeX: \begin{minipage}{0.05\linewidth} 
#+LaTeX: \end{minipage}
#+LaTeX: \begin{minipage}{0.45\linewidth} 
- Causal inference
- Multiple testing
#+LaTeX: \end{minipage}

\bigskip

* Skills                                                             :ignore:
#+LaTeX: \resheading{Skills}

** /Language/
French (native language), english (fluent), danish (intermediate),
basics in italian.

** /Software/
Proficient in \Rlogo{}, \LaTeX{} and [[https://orgmode.org/][orgmode]]. @@latex:\\@@ 
Basic knowledge but common use of \Cpp{}, lisp (for [[https://www.gnu.org/software/emacs/][GNU Emacs]]) and
git/github (via [[https://magit.vc/][magit]]).

\clearpage

* Education                                                          :ignore:
#+LaTeX: \resheading{Education and research carrier}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2022 - 2023 : & Course in teaching and learning in higher education (Universitetspædagogikum) \\
2020 - 2023 : & Assistant professor in biostatistics with a shared positive between: \\
              & \emph{University of Copenhagen}: researcher and teacher at the Graduate School \\
              & of Health and Medical Sciences \\ 
              & \emph{Copenhagen University Hospital}: consultant \\
              & Development of a 'user-friendly' mixed model package (\texttt{LMMstar} package), \\
              & a package for designing and analyzing groups sequential trials (\texttt{DelayedGSD} package), \\
              & and extension of the \texttt{BuyseTest} package (H-decomposition, restriction time) \\ [3mm]
2020 - 2015 : & Post-doc in biostatistics with a shared positive between: \\
              & \emph{University of Copenhagen}: researcher and teacher at the Graduate School \\
              & of Health and Medical Sciences \\ 
              & \emph{Copenhagen University Hospital}: consultant and leader of the data analysis work package \\ 
              & of the \href{https://np.nru.dk/}{Neuropharm} project  \\ 
              & Development of small sample corrections and multiple testing adjustment for LVM \\
              & and robust estimators of treatment effect for registry data analysis \\
              & (respective R packages: \texttt{lavaSearch2} and \texttt{riskRegression}) \\ [3mm]
2012 - 2015 : & Ph.D. in biostatistics, University Lyon 1, Lyon, France. \\
              & Thesis Title: \href{https://tel.archives-ouvertes.fr/tel-01233049/document}{Statistical modelling for the prognosis of stroke patients.} \\ 
              & Advisor: Pr. Delphine Maucort-Boulch and Pr. Norbert Nighoghossian \\
              & Start of the \texttt{BuyseTest} package emulating a SAS macro. \\ [3mm]
2011 - 2012 : & Master’s degree in biostatistics (\href{https://clarolineconnect.univ-lyon1.fr/icap_website/299/5381}{M2 B3S}), University lyon, Lyon, France. \\ 
              & Carried out in double degree with the École Centrale de Lyon. \\ [3mm]
2009 - 2012 : & Engineering diploma from the École Centrale de Lyon, Lyon, France. \\
              & Erasmus at Politecnico di Milano (2nd semester 2011). \\
\end{tabular}
#+END_EXPORT

* Teaching and supervision                                           :ignore:
#+LaTeX: \resheading{Teaching and supervision}

Current teaching activity for Phd students in medical sciences:
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2015 - 2023 : & \href{https://absalon.ku.dk/courses/47665}{Statistical analysis of repeated measurements} (course director Julie Forman). \\
              & 3 lectures of 3 hours and 6 practicals of 3 hours\\
              & Development of a dedicated \Rlogo package for the course (\href{https://cran.r-project.org/web/packages/LMMstar/index.html}{LMMstar}) \\
2021 - 2023 : & \href{https://absalon.ku.dk/courses/58764}{Epidemiological methods in medical research} as course director. \\
              & 3.5 lectures of 3 hours, 7 practical of 3 hours, 1/2 day student presentations \\
2021 - 2023 : & \href{http://paulblanche.com/files/BasicStat2022.html}{Basic statistics}  (course director Paul Blanche). \\
              & 1 lecture of 3 hours, 1 practical of 3 hours, 1 day student presentations
\end{tabular}
#+END_EXPORT

More in depth presentation of the present and past teaching activity
as well as the pedagocial approach can be found in my [[https://bozenne.github.io/doc/CV/TP-EN-briceOzenne.pdf][teaching
portofilio]]. 

\bigskip

I now also teach Master students in statistics:
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2023 - 2024 : & \href{https://absalon.ku.dk/courses/68009}{Survival analysis} (course director Frank Eriksson). \\
              & 6 lectures of 4 hours and 6 practicals of 1 or 2 hours\\
\end{tabular}
#+END_EXPORT



\bigskip

Co-supervision of students: 

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2023 &:& Tanne Ebert Jørgensen and Johanne Triantafyllou Lorenzen (Master in epidemiology)\\
\multicolumn{3}{l}{Childcare and symptoms of ADHD in the Danish population.} \\ [3mm]
2021-2024 &:& Simon Christoffer Ziersen (Ph.D in biostatistics)\\
\multicolumn{3}{l}{Causal inference in time to event analysis with competing risks} \\ [3mm]
2021 &:& Ramlah Sara Rehman (Bachelor in data science)\\
\multicolumn{3}{l}{An Analysis of Clustering Algorithms: Clustering Trajectories of the Cortisol Concentration.} \\ [3mm]
2019 &:& Alice Brouquet-Laglaire (Master 2 in biostatistics)\\
\multicolumn{3}{l}{Comparison of inference methods for generalized pairwise comparisons.} \\ [3mm]
2014 &:& Ceren Tozlu (Master 2 in biostatistics)\\
\multicolumn{3}{l}{Comparison of classification methods for tissue outcome after ischemic stroke \citep{tozlu2019comparison}.} \\ [3mm]
\end{tabular}
#+END_EXPORT

\bigskip

Pedagogical talks for researchers in neuroscience on specific
statistical tools/issues:
- [[https://bozenne.github.io/doc/Talks/2017-XNRU-power.pdf][Do we need more power?]] ([[https://www.nru.dk/images/News/NeurobiologyResearchUnit-Christmas-symposium2017.pdf][NRU Christmas Symposium 2017]]).
- [[https://bozenne.github.io/doc/Talks/2018-XNRU-DAGs.pdf][To adjust or not adjust, that is the question]] (NRU Christmas Symposium 2018).
- [[https://bozenne.github.io/doc/Talks/2019-XNRU-multcomp.pdf][A refresher on multiple comparisons]]? ([[https://nru.dk/index.php/news-menu/279-nru-christimas-symposium-2019][NRU Christmas Symposium 2019]]).
- [[https://bozenne.github.io/doc/Talks/2022-XNRU-pooling.pdf][The data-processing multiverse: achieving reconciliation for
  Christmas]] (NRU Christmas Symposium 2022).


* Grants                                                             :ignore:
#+LaTeX: \resheading{Grants}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2017-2019: MARIE CURIE Individual Fellowships (200 000\euro, EU H2020-MSCA-IF-2016 746850) \\
2017-2020: Lundbeck Fellowships (140 000\euro, R231-2016-3236) \\
\end{tabular}
#+END_EXPORT

\clearpage

* Publications                                                :ignore:                          
#+LaTeX: \resheading{Publications in peer reviewed scientific journals \hfill \href{https://scholar.google.com/citations?user=rJMNP7YAAAAJ&hl=fr}{link google scholar}}
** /Methodological/ (selected publications - 8/14)
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{scheike2022efficient}
    \item \bibentry{ozenne2022controlling}
    \item \bibentry{ozenne2021asymptotic}
    \item \bibentry{ozenne2020small}
    \item \bibentry{ozenne2020estimation}
    \item \bibentry{ozenne2017riskregression}
    \item \bibentry{ozenne2015precision}
    \item \bibentry{ozenne2015spatially}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]

** /Clinical applications/ (selected publications - 10/54)
#+BEGIN_EXPORT latex
 \begin{enumerate}[resume]
    \item \bibentry{kohler2023serotonin}
    \item \bibentry{nasser2022reliability}
    \item \bibentry{kohler2022concurrent}
    \item \bibentry{beaman2022blood}
    \item \bibentry{larsen2022impact}
    \item \bibentry{ozenne2019individualized}
    \item \bibentry{ebert2019molecular}
    \item \bibentry{staerk2018standard}
    \item \bibentry{stenbaek2017brain}
    \item \bibentry{ozenne2015evaluation}
  \end{enumerate}
#+END_EXPORT

\bigskip

* Software development                                               :ignore:
#+LaTeX: \resheading{Software development}

Packages for the [[https://www.r-project.org/][R]] software:
- *BuyseTest* (author and maintainer): implementation of generalized
  pairwise comparisons, including recent developments to handle
  right-censoring citep:ozenne2021asymptotic. Available on
  [[https://cran.r-project.org/web/packages/BuyseTest/index.html][CRAN]]
  and on [[https://github.com/bozenne/BuyseTest][Github]].

- *lavaSearch2* (author and maintainer): Inference and diagnostic
  tools for latent variable models.  Methodology described in
  citep:ozenne2020small and citep:ozenne2022controlling. Available on
  [[https://cran.r-project.org/web/packages/lavaSearch2/index.html][CRAN]] and on [[https://github.com/bozenne/lavaSearch2][Github]]. .

- *LMMstar* (author and maintainer) : linear mixed model via
  covariance structure (marginal formulation). Inference in small
  sample, test linear and non-linear combinations of parameters,
  multiple comparisons adjustment. Available on [[https://cran.r-project.org/web/packages/LMMstar/index.html][CRAN]] and on [[https://github.com/bozenne/LMMstar][Github]].

- *riskRegression* (contributor): computation of absolute risks and
  average treatment effects. Methodology described in
  citep:ozenne2017riskregression and
  citep:ozenne2020estimation. Available on [[https://cran.r-project.org/web/packages/riskRegression/index.html][CRAN]] and on [[https://github.com/tagteam/riskRegression][Github]].

- *DelayedGSD* (author and maintainer): design and analysis for group
  sequential trial with repeated measurements of a continous
  outcome. Methodology described in citep:baayen202Xdesign (to
  appear). Available on
  [[https://github.com/bozenne/DelayedGSD][Github]].

Package for [[https://www.gnu.org/software/emacs/][emacs]]:
- *emacs-config* (author and maintainer) : Configuration files for
  emacs to ease the interaction with
  R/C++/orgmode/latex/git. Disponible on [[https://github.com/bozenne/emacs-config][Github]].

\pagebreak[3]

* Reviewing activity                                                 :ignore:
#+LaTeX: \resheading{Peer review}
I have reviewed papers for [[https://onlinelibrary.wiley.com/journal/15214036][Biometrical Journal]], [[https://onlinelibrary.wiley.com/journal/15410420][Biometrics]], [[https://www.jstatsoft.org/index][Journal of
statistical software]], [[https://onlinelibrary.wiley.com/journal/10970258][Statistics in Medicine]], and [[https://www.degruyter.com/journal/key/ijb/html][the International
Journal of Biostatistics]].

\bigskip

I am also in the Data and Safety Monitoring Board (DSMB) of the
clinical trial [[http://www.traumox2.org/][TRAUMOX2]] (1420 patients, 5 sites in europe).

\bigskip

* Oral communications                                                         :ignore:
#+LaTeX: \resheading{Oral communications}
Oral presentation at international conferences: 

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Lesion Segmentation using a Spatially Regularized Mixture Model \\
&& \href{http://conferences.nib.si/AS2014/default.htm}{Applied Statistics}, Ribno, Slovenia \hfill (\href{https://bozenne.github.io/doc/Talks/2014-Applied_statistics-Lesion_Segmentation.pdf}{slides}) \\ [3mm]
2015 &:& MRIaggr : un package pour la gestion et le traitement de données multivariées d'imagerie\\
&& \href{https://r2015-grenoble.sciencesconf.org/66037}{Rencontres R, Grenoble, France}  \hfill   (\href{https://bozenne.github.io/doc/Talks/2015-R-MRIaggr.pdf}{slides})  \\ [3mm]
2016 &:& Penalized latent variable models  \\
&& \href{http://cmstatistics.org/RegistrationsV2/COMPSTAT2016/viewSubmission.php?in=440&token=29584n1s18p97n65o7p1r5n36sopq0n4}{Computational statistics}, Oviedo, Spain \hfill (\href{https://bozenne.github.io/doc/Talks/2016-Compstat-pLVM.pdf}{slides}) \\ [3mm]
2017 &:& Assessing treatment effects on registry data in presence of competing risks \\ 
&& ISCB, Vigo, Spain \hfill (\href{https://bozenne.github.io/doc/Talks/2017-ISCB-ate.pdf}{slides}) \\ [3mm]
2019 &:& Generalized pairwise comparisons for right-censored time to event outcomes \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhagen, Denmark \hfill (\href{https://bozenne.github.io/doc/Talks/2019-prezSAfJR-GPC.pdf}{slides}) \\ [3mm]
2019 &:& Multiple testing in latent variable models \\
&& \href{https://kuleuvencongres.be/iscb40/}{ISCB}, Leuven, Belgium \hfill (\href{https://bozenne.github.io/doc/Talks/2019-ISCB-multcomp_LVM.pdf}{slides}) \\
2024 &:& Ordering the sample space in group sequential trials with delayed outcome  \\
&& \href{https://admtp.github.io/ADMTP2024/}{ADMTP Workshop}, Ibiza, Spain \hfill (\href{https://bozenne.github.io/doc/Talks/2024-ADMTP-GSD-pval.pdf}{slides}) \\
\end{tabular}
#+END_EXPORT

\bigskip

Invited speaker at an international conference: 

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2019 &:& Region-Based and Voxel-Wise Analysis of Medical Images Using Latent Variables \\
&& \href{https://events.razzby.com/nbbc19/}{7th NBBC}, Vilnius, Lithuania \\
2020 &:& Robust estimation of the average treatment effects in presence of right-censoring \\
&& and competing risks \\
&& \href{http://www.cmstatistics.org/conferences.php}{CMStatistics}, London, England \\
2022 &:&  	Benefit-risk assessment via generalized pairwise comparisons  \\
&& \href{http://www.cmstatistics.org/CMStatistics2022/programme.php}{CMStatistics}, London, England \\
\end{tabular}
#+END_EXPORT

\bigskip

Chairman at international conferences:

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2019 &:& Mathematical Statistics \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhagen, Denmark
\end{tabular}
#+END_EXPORT

\bigskip

Organisation of a workshop:
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2021 &:& Analysis of repeated measurements with mixed models using the R package LMMstar (1h+3h) \\
&& Methods Week, Karolinska institute, Stockholm, Sweden
\end{tabular}
#+END_EXPORT

* Reference :ignore:

# bibliographystyle:apalike
 bibliographystyle:plainnat

 # [[bibliography:publicationBO.bib]]
[[nobibliography:publicationBO.bib]]

* CONFIG :noexport:
#+LANGUAGE: en
#+LaTeX_CLASS: org-article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+OPTIONS:   title:nil author:nil toc:nil todo:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t
#+options: num:nil

#+LaTeX_HEADER: \pagestyle{empty} % no page numbering
#+LATEX_HEADER: \usepackage[french]{babel}

** Notations
#+LaTeX_HEADER: \newcommand{\Cpp}{C\nolinebreak\hspace{-.05em}\raisebox{.4ex}{\tiny\bf +}\nolinebreak\hspace{-.10em}\raisebox{.4ex}{\tiny\bf +}}
#+LaTeX_HEADER: \usepackage{eurosym} % euro symbol

** Sections
#+LaTeX_HEADER: \usepackage{titlesec}
#+LaTeX_HEADER: \titleformat{\section}{\large}{\thesection}{1em}{}

#+LaTeX_HEADER: \titlespacing*{\section}{0pt}{0.25\baselineskip}{0.25\baselineskip}
** Margin
#+LaTeX_HEADER: \geometry{
#+LaTeX_HEADER: left=20mm,
#+LaTeX_HEADER: right=20mm,
#+LaTeX_HEADER: top=20mm,
#+LaTeX_HEADER: bottom=20mm
#+LaTeX_HEADER: }

** Color
# # change the color of the links
#+LaTeX_HEADER: \hypersetup{
#+LaTeX_HEADER:  citecolor=[rgb]{0,0.5,0},
#+LaTeX_HEADER:  urlcolor=[rgb]{0,0,0.5},
#+LaTeX_HEADER:  linkcolor=[rgb]{0,0,0.5},
#+LaTeX_HEADER: }


** Line spacing
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER: \renewcommand{\baselinestretch}{1.1}

** CV
# from https://www.sharelatex.com/templates/cv-or-resume/sc_cv
#+LaTeX_HEADER: \usepackage{framed}
#+LaTeX_HEADER: \usepackage{tocloft}

#+LaTeX_HEADER: \newlength{\outerbordwidth}
#+LaTeX_HEADER: \raggedbottom
#+LaTeX_HEADER: \raggedright

#+LaTeX_HEADER: \setlength{\outerbordwidth}{3pt}  % Width of border outside of title bars
#+LaTeX_HEADER: \definecolor{shadecolor}{gray}{0.75}  % Outer background color of title bars (0 = black, 1 = white)
#+LaTeX_HEADER: \definecolor{shadecolorB}{gray}{0.93}  % Inner background color of title bars

#+LaTeX_HEADER: \usepackage{mdframed}
#+LaTeX_HEADER: \newcommand{\resitem}[1]{\item #1 \vspace{-2pt}}

#+LaTeX_HEADER: \newcommand{\resheading}[1]{
#+LaTeX_HEADER: \vspace{8pt}
#+LaTeX_HEADER:  \parbox{\textwidth}{\setlength{\FrameSep}{\outerbordwidth}
#+LaTeX_HEADER:     \begin{shaded}
#+LaTeX_HEADER: \setlength{\fboxsep}{0pt}\framebox[\textwidth][l]{\setlength{\fboxsep}{4pt}\fcolorbox{shadecolorB}{shadecolorB}{\textbf{\sffamily{\mbox{~}\makebox[6.762in][l]{\large #1} \vphantom{p\^{E}}}}}}
#+LaTeX_HEADER:     \end{shaded}
#+LaTeX_HEADER:   }\vspace{-5pt}
#+LaTeX_HEADER: }
#+LaTeX_HEADER: \newcommand{\ressubheading}[4]{
#+LaTeX_HEADER: \begin{tabular*}{6.5in}{l@{\cftdotfill{\cftsecdotsep}\extracolsep{\fill}}r}
#+LaTeX_HEADER: 		\textbf{#1} & #2 \\
#+LaTeX_HEADER: 		\textit{#3} & \textit{#4} \\
#+LaTeX_HEADER: \end{tabular*}\vspace{-6pt}}

** List of publications
# ### list publications
#+LaTeX_HEADER: \usepackage{bibentry}
#+LaTeX_HEADER: \nobibliography*

# ### display of my name
#+LaTeX_HEADER: \newcommand{\myname}[1]{\textbf{#1}}

#+LaTeX_HEADER:  \usepackage{url}

# ## [resume] (keep the numbering over several enumerate list)
#+LaTeX_HEADER: \usepackage{enumitem}

** Rlogo
# ## R logo
#+LATEX_HEADER:\definecolor{grayR}{HTML}{8A8990}
#+LATEX_HEADER:\definecolor{grayL}{HTML}{C4C7C9}
#+LATEX_HEADER:\definecolor{blueM}{HTML}{1F63B5}   
#+LATEX_HEADER: \newcommand{\Rlogo}[1][0.07]{
#+LATEX_HEADER: \begin{tikzpicture}[scale=#1]
#+LATEX_HEADER: \shade [right color=grayR,left color=grayL,shading angle=60] 
#+LATEX_HEADER: (-3.55,0.3) .. controls (-3.55,1.75) 
#+LATEX_HEADER: and (-1.9,2.7) .. (0,2.7) .. controls (2.05,2.7)  
#+LATEX_HEADER: and (3.5,1.6) .. (3.5,0.3) .. controls (3.5,-1.2) 
#+LATEX_HEADER: and (1.55,-2) .. (0,-2) .. controls (-2.3,-2) 
#+LATEX_HEADER: and (-3.55,-0.75) .. cycle;
#+LATEX_HEADER: 
#+LATEX_HEADER: \fill[white] 
#+LATEX_HEADER: (-2.15,0.2) .. controls (-2.15,1.2) 
#+LATEX_HEADER: and (-0.7,1.8) .. (0.5,1.8) .. controls (2.2,1.8) 
#+LATEX_HEADER: and (3.1,1.2) .. (3.1,0.2) .. controls (3.1,-0.75) 
#+LATEX_HEADER: and (2.4,-1.45) .. (0.5,-1.45) .. controls (-1.1,-1.45) 
#+LATEX_HEADER: and (-2.15,-0.7) .. cycle;
#+LATEX_HEADER: 
#+LATEX_HEADER: \fill[blueM] 
#+LATEX_HEADER: (1.75,1.25) -- (-0.65,1.25) -- (-0.65,-2.75) -- (0.55,-2.75) -- (0.55,-1.15) -- 
#+LATEX_HEADER: (0.95,-1.15)  .. controls (1.15,-1.15) 
#+LATEX_HEADER: and (1.5,-1.9) .. (1.9,-2.75) -- (3.25,-2.75)  .. controls (2.2,-1) 
#+LATEX_HEADER: and (2.5,-1.2) .. (1.8,-0.95) .. controls (2.6,-0.9) 
#+LATEX_HEADER: and (2.85,-0.35) .. (2.85,0.2) .. controls (2.85,0.7) 
#+LATEX_HEADER: and (2.5,1.2) .. cycle;
#+LATEX_HEADER: 
#+LATEX_HEADER: \fill[white]  (1.4,0.4) -- (0.55,0.4) -- (0.55,-0.3) -- (1.4,-0.3).. controls (1.75,-0.3) 
#+LATEX_HEADER: and (1.75,0.4) .. cycle;
#+LATEX_HEADER: 
#+LATEX_HEADER: \end{tikzpicture}
#+LATEX_HEADER: }
