#+TITLE:
#+Author: Brice Ozenne

# header
#+BEGIN_EXPORT latex
\begin{tabular*}{7in}{l@{\extracolsep{\fill}}r}
	\textbf{\Large Brice Ozenne} & \textbf{\today} \\
\end{tabular*}

\bigskip

\begin{minipage}{0.2\linewidth}
\includegraphics[width=\linewidth]{photoId.png}
\end{minipage}
\begin{minipage}{0.75\linewidth}
\begin{tabular*}{7in}{ll@{ }l}
	Nationality&:& french  \\
	Date of birth&:& February 8, 1990  \\
	Personal email&:& \url{brice.mh.ozenne@gmail.com} \\ 
	Personal phone number&:& (+45) 52 328 128 \\ 
        Personal address&:& Nordre Teglkaj 18, 5 t.h., 2450 Copenhagen SV, Denmark \\
        Personal Website&:& \url{https://bozenne.github.io/} \\
        Github&:& \url{https://github.com/bozenne/} \\
\end{tabular*}
\end{minipage}
#+END_EXPORT

\bigskip

* Current position                                          :ignore:
#+LaTeX: \resheading{Current position}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
	November 2015- Now:& \textbf{Postdoctoral researcher in biostatistics} with a shared position between \\ [2mm]
	& - a research unit in biostatistics \\
	& \href{https://biostat.ku.dk/staff_/?pure=en/persons/540231}{Section of Biostatistics}, University of Copenhagen \\
	& \O{}ster Farimagsgade 5, 1014 Copenhague, Danemark \\ [2mm]
	& - a research unit in neuroscience \\
	& \href{https://nru.dk/index.php/staff-list/post-docs/110-brice-ozenne}{Neurobiology Research Unit} \\
	& Copenhagen University Hospital, Rigshospitalet \\
	& Building 6931, Blegdamsvej 9, DK-2100 Copenhagen, Denmark \\ [2mm]
      & where I do research in biostatistics along with a consulting activity in statistics \\
      & and some teaching.
\end{tabular}
#+END_EXPORT

\bigskip
My research work is organized around three topics:
- the development of *latent variable models* for data analysis in
  neuroscience - see publications
  cite:ebert2019molecular,stenbaek2017brain,fisher2017bdnf. From a
  methodological point of view, I study how to perform statistical
  *estimation and inference in small samples* citep:ozenne20XXsmall as
  well as efficient corrections for *multiple testing*
  citep:ozenne20XXcontroling. These developments are available in the
  R package =lavaSearch2=.

- the analysis of registry data in presence of *right-censoring*,
  *competing risks*, and *confounding* *competing risks*. A typical
  application is the comparison of preventive treatments of
  cardiovascular diseases
  citep:staerk2016ischaemic,staerk2017resumption,staerk2018standard. Based
  on the *semi-parametric theory*, I have developped a robust
  estimator of the average treatment effect and derived its asymptotic
  distribution via its influence function
  citep:ozenne2020estimation. This has been implemented in the =ate=
  function of the =riskRegression= R package.

\clearpage

- the extension of *generalized pairwise comparisons* (GPC) to
  right-censoring citep:peron2016extension. GPC is a method able to
  handle multiple and heterogeneous endpoints which is especially
  relevant to assess the benefit-risk balance of a treatment. A
  typical application is the evaluation of chemotherapies where
  jointly considering gains in survival and side effects is
  critical. I am now working on deriving the asymptotic distribution
  of some of the estimators implemented in the =BuyseTest= using the
  U-statistique theory.

** /Other domains of interest in statistics:/
- Smoothing splines and functional data analysis
- Causal inference and dynamic treatment regimes
- Post-selection inference


** /Language/
French (native language), english (fluent), danish (intermediate),
basics in italian.

** /Software/
Proficient in \Rlogo{}, \LaTeX{} and [[https://orgmode.org/][orgmode]]. @@latex:\\@@ 
Basic knowledge but common use of \Cpp{}, lisp (for [[https://www.gnu.org/software/emacs/][GNU Emacs]]) and
git/github (via [[https://magit.vc/][magit]]).


* Education                                                  :ignore:
#+LaTeX: \resheading{Education}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2012 - 2015 : & Ph.D. in biostatistics, University Lyon 1, Lyon, France. \\
              & Thesis Title: \href{https://tel.archives-ouvertes.fr/tel-01233049/document}{Statistical modelling for the prognosis of stroke patients.} \\ 
              & Advisor: Pr. Delphine Maucort-Boulch and Pr. Norbert Nighoghossian \\ [3mm]
2011 - 2012 : & Master’s degree in biostatistics (\href{https://clarolineconnect.univ-lyon1.fr/icap_website/299/5381}{M2 B3S}), University lyon, Lyon, France. \\ 
              & Carried out in double degree with the École Centrale de Lyon. \\ [3mm]
2009 - 2012 : & Engineering diploma from the École Centrale de Lyon, Lyon, France. \\
              & Erasmus at Politecnico di Milano (2nd semester 2011). \\
\end{tabular}
#+END_EXPORT

* Teaching and supervision                                           :ignore:
#+LaTeX: \resheading{Teaching and supervision}

Teaching (L : lecture, PC : practical classes)
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2015 - 2020 : & \href{http://publicifsv.sund.ku.dk/~jufo/RepeatedMeasures2016.html}{Statistical analysis of repeated measurements} for Phd students in medical sciences (18h, PC). \\
2016 - 2017 : & \href{http://publicifsv.sund.ku.dk/~kkho/undervisning/sem2016/}{Structural Equation Models} for Master students in statistics (2h, L). \\
2014 - 2015 : & \href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215839}{Bayesian statistics} for Master students in public health (6h, PC).\\
2013 - 2015 : & \href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215839}{Survival Analysis} for Master students in public health (18h, PC).\\
\end{tabular}
#+END_EXPORT

\clearpage

Pedagogical talks for researchers in neuroscience on specific
statistical tools/issues:
- [[https://bozenne.github.io/doc/Talks/2017-XNRU-power.pdf][Do we need more power?]] ([[https://www.nru.dk/images/News/NeurobiologyResearchUnit-Christmas-symposium2017.pdf][NRU Christmas Symposium 2017]]).
- [[https://bozenne.github.io/doc/Talks/2018-XNRU-DAGs.pdf][To adjust or not adjust, that is the question]] (NRU Christmas Symposium 2018).
- [[https://bozenne.github.io/doc/Talks/2019-XNRU-multcomp.pdf][A refresher on multiple comparisons]]? ([[https://nru.dk/index.php/news-menu/279-nru-christimas-symposium-2019][NRU Christmas Symposium 2019]]).

\bigskip

Co-supervision of *master 2* student: 

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Ceren Tozlu \\
\multicolumn{3}{l}{Comparison of classification methods for tissue outcome after ischemic stroke \citep{tozlu2019comparison}.} \\ [3mm]
2019 &:& Alice Brouquet-Laglaire \\
\multicolumn{3}{l}{Comparison of inference methods for generalized pairwise comparisons.} \\ [3mm]
\end{tabular}
#+END_EXPORT

\bigskip

Contribution to the supervision of *Phd-students* in science or
medicine via the statistical consultations:

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2017-2020 &:& Martin Korsbak Madsen (thèse de médecine)  \\
\multicolumn{3}{l}{Neurobiological effects of 5-HT2AR modulation} \\
\multicolumn{3}{l}{Publications: \cite{madsen2020single,madsen2019psychedelic}} \\ [3mm]
2016-2019 &:& Martin N\o{}rgaard (thèse de science)  \\
\multicolumn{3}{l}{Optimisation de la stratégie de traitement des données IRM et TEP en neuroimagerie} \\
\multicolumn{3}{l}{Publication: \cite{norgaard2019preprocessing}} \\ [3mm]
2015-2018 &:& Vincent Beliveau (thèse de science) \\
\multicolumn{3}{l}{Imagerie fonctionnelle et moléculaire du système cérébral de sérotonine chez l'humain} \\ 
\multicolumn{3}{l}{Publications: \cite{beliveau2020structure,beliveau2017high}} \\ [3mm]
2015-2018 &:& Liv Vadskj\ae r Hjordt (thèse en psychologie) \\
\multicolumn{3}{l}{A Study of Cognitive and Personality Factors Involved inSeasonal Affective Disorder} \\ 
\multicolumn{3}{l}{Publications: \cite{hjordt2018self,hjordt2017season}} \\ [3mm]
2015-2018 &:& Mette Thrane Foged  (thèse de médecine) \\
\multicolumn{3}{l}{Epilepsy surgery: Outcomes of the Danish evaluation program and development} \\ 
\multicolumn{3}{l}{\hphantom{Epilepsy surgery:} of new EEG based methods} \\ 
\multicolumn{3}{l}{Publications: \cite{foged2017safety,foged2018verbal}} \\ [3mm]
\end{tabular}
#+END_EXPORT


* Grants                                                             :ignore:
#+LaTeX: \resheading{Grants}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2017-2019: MARIE CURIE Individual Fellowships (200 000\euro, EU H2020-MSCA-IF-2016 746850) \\
2017-2020: Lundbeck Fellowships (140 000\euro, R231-2016-3236) \\

\end{tabular}
#+END_EXPORT

\clearpage

* Scientific output                                                  :ignore:
#+LaTeX: \resheading{Scientific output \hfill \href{https://scholar.google.com/citations?user=rJMNP7YAAAAJ&hl=fr}{lien google scholar}}
** /Publications (methodological)/

Published:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{verbeeck2020evaluation}
    \item \bibentry{ozenne2020estimation}
    \item \bibentry{norgaard2019preprocessing}
    \item \bibentry{ozenne2017riskregression}
    \item \bibentry{peron2016extension}
    \item \bibentry{ozenne2015precision}
    \item \bibentry{ozenne2015spatially}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]

In revision:
#+BEGIN_EXPORT latex
\begin{enumerate}
    \item \bibentry{ozenne20XXsmall}
    \item \bibentry{ozenne20XXcontroling}
    \item \bibentry{peron20XXunbiased}
\end{enumerate}
#+END_EXPORT

\pagebreak[3]

** /Publications (clinical applications)/

Published:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{beliveau2020structure}
    \item \bibentry{madsen2020single}
    \item \bibentry{ozenne2019individualized}
    \item \bibentry{ebert2019molecular}
    \item \bibentry{madsen2019psychedelic}
    \item \bibentry{tozlu2019comparison}
    \item \bibentry{ip2018pre}
    \item \bibentry{borgsted2018amygdala}
    \item \bibentry{hjordt2018self}
    \item \bibentry{foged2018verbal}
    \item \bibentry{staerk2018standard}
    \item \bibentry{hjordt2017season}
    \item \bibentry{beliveau2017high}
    \item \bibentry{stenbaek2017brain}
    \item \bibentry{staerk2017resumption}
    \item \bibentry{fisher2017bdnf}
    \item \bibentry{foged2017safety}
    \item \bibentry{peron2016net}
    \item \bibentry{staerk2016ischaemic}
    \item \bibentry{peron2016assessment}
    \item \bibentry{ozenne2015evaluation}
    \item \bibentry{hermitte2013very}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]


* Software development                                              :ignore:
#+LaTeX: \resheading{Software development}

Packages for the [[https://www.r-project.org/][R]] software:
- *BuyseTest* (author and maintainer): generalized pairwise
  comparisons. Implementation of the extension described in
  citep:peron2016extension,peron20XXunbiased. Available on [[https://cran.r-project.org/web/packages/BuyseTest/index.html][CRAN]] and on [[https://github.com/bozenne/BuyseTest][Github]].

- *lavaSearch2* (author and maintainer): Inference and diagnostic
  tools for latent variable models.  Methodology described in
  citep:ozenne20XXsmall and citep:ozenne20XXcontroling. Available on
  [[https://cran.r-project.org/web/packages/lavaSearch2/index.html][CRAN]] and on [[https://github.com/bozenne/lavaSearch2][Github]]. .

- *riskRegression* (contributor): computation of absolute risks and
  average treatment effects. Methodology described in
  citep:ozenne2017riskregression and
  citep:ozenne2020estimation. Available on [[https://cran.r-project.org/web/packages/riskRegression/index.html][CRAN]] and on [[https://github.com/tagteam/riskRegression][Github]].

\bigskip

Package for [[https://www.gnu.org/software/emacs/][emacs]]:
- *emacs-config* (author and maintainer) : Configuration files for
  emacs to ease the interaction with
  R/C++/orgmode/latex/git. Disponible sur sur [[https://github.com/bozenne/emacs-config][Github]].

\pagebreak[3]
* Peer review       :ignore:
#+LaTeX: \resheading{Peer review}
I have reviewed papers for Biometrics, Statistics in Medicine, and the
International Journal of Biostatistics.

\bigskip

* Oral communications                                                         :ignore:
#+LaTeX: \resheading{Oral communications}
Oral presentation at international conferences: 
\smallskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Lesion Segmentation using a Spatially Regularized Mixture Model \\
&& \href{http://conferences.nib.si/AS2014/default.htm}{Applied Statistics}, Ribno, Slovenia \\
2015 &:& \href{https://r2015-grenoble.sciencesconf.org/66037}{MRIaggr : un package pour la gestion et le traitement de données multivariées d'imagerie} \\
&& Rencontres R, Grenoble, France \\
2016 &:& \href{http://cmstatistics.org/RegistrationsV2/COMPSTAT2016/viewSubmission.php?in=440&token=29584n1s18p97n65o7p1r5n36sopq0n4}{Penalized latent variable models} \\
&& Computational statistics, Oviedo, Spain \\
2017 &:& Assessing treatment effects on registry data in presence of competing risks \\ 
&& \href{http://www.iscb2017.info/}{ISCB}, Vigo, Spain \\
2019 &:& Generalized pairwise comparisons for right-censored time to event outcomes \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhagen, Denmark \\
2019 &:& Region-Based and Voxel-Wise Analysis of Medical Images Using Latent Variables \\
&& \href{https://events.razzby.com/nbbc19/}{7th NBBC}, Vilnius, Lithuania \\
2019 &:& Multiple testing in latent variable models \\
&& \href{https://kuleuvencongres.be/iscb40/}{ISCB}, Leuven, Belgium \\
\end{tabular}
#+END_EXPORT

\bigskip

Chairman at international conferences:
\smallskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2019 &:& Mathematical Statistics \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhagen, Denmark
\end{tabular}
#+END_EXPORT


* Reference :ignore:

# bibliographystyle:apalike
 bibliographystyle:plainnat

 # [[bibliography:publicationBO.bib]]
[[nobibliography:publicationBO.bib]]

* CONFIG :noexport:
#+LANGUAGE: en
#+LaTeX_CLASS: org-article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+OPTIONS:   title:nil author:nil toc:nil todo:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t
#+options: num:nil

#+LaTeX_HEADER: \pagestyle{empty} % no page numbering
#+LATEX_HEADER: \usepackage[french]{babel}

** Notations
#+LaTeX_HEADER: \newcommand{\Rlogo}{\textbf{\textsf{R}}}
#+LaTeX_HEADER: \newcommand{\Cpp}{C\nolinebreak\hspace{-.05em}\raisebox{.4ex}{\tiny\bf +}\nolinebreak\hspace{-.10em}\raisebox{.4ex}{\tiny\bf +}}
#+LaTeX_HEADER: \usepackage{eurosym} % euro symbol

** Sections
#+LaTeX_HEADER: \usepackage{titlesec}
#+LaTeX_HEADER: \titleformat{\section}{\large}{\thesection}{1em}{}

#+LaTeX_HEADER: \titlespacing*{\section}{0pt}{0.25\baselineskip}{0.25\baselineskip}
** Margin
#+LaTeX_HEADER: \geometry{
#+LaTeX_HEADER: left=20mm,
#+LaTeX_HEADER: right=20mm,
#+LaTeX_HEADER: top=20mm,
#+LaTeX_HEADER: bottom=20mm
#+LaTeX_HEADER: }

** Line spacing
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER: \renewcommand{\baselinestretch}{1.1}

** CV
# from https://www.sharelatex.com/templates/cv-or-resume/sc_cv
#+LaTeX_HEADER: \usepackage{framed}
#+LaTeX_HEADER: \usepackage{tocloft}

#+LaTeX_HEADER: \newlength{\outerbordwidth}
#+LaTeX_HEADER: \raggedbottom
#+LaTeX_HEADER: \raggedright

#+LaTeX_HEADER: \setlength{\outerbordwidth}{3pt}  % Width of border outside of title bars
#+LaTeX_HEADER: \definecolor{shadecolor}{gray}{0.75}  % Outer background color of title bars (0 = black, 1 = white)
#+LaTeX_HEADER: \definecolor{shadecolorB}{gray}{0.93}  % Inner background color of title bars

#+LaTeX_HEADER: \usepackage{mdframed}
#+LaTeX_HEADER: \newcommand{\resitem}[1]{\item #1 \vspace{-2pt}}

#+LaTeX_HEADER: \newcommand{\resheading}[1]{
#+LaTeX_HEADER: \vspace{8pt}
#+LaTeX_HEADER:  \parbox{\textwidth}{\setlength{\FrameSep}{\outerbordwidth}
#+LaTeX_HEADER:     \begin{shaded}
#+LaTeX_HEADER: \setlength{\fboxsep}{0pt}\framebox[\textwidth][l]{\setlength{\fboxsep}{4pt}\fcolorbox{shadecolorB}{shadecolorB}{\textbf{\sffamily{\mbox{~}\makebox[6.762in][l]{\large #1} \vphantom{p\^{E}}}}}}
#+LaTeX_HEADER:     \end{shaded}
#+LaTeX_HEADER:   }\vspace{-5pt}
#+LaTeX_HEADER: }
#+LaTeX_HEADER: \newcommand{\ressubheading}[4]{
#+LaTeX_HEADER: \begin{tabular*}{6.5in}{l@{\cftdotfill{\cftsecdotsep}\extracolsep{\fill}}r}
#+LaTeX_HEADER: 		\textbf{#1} & #2 \\
#+LaTeX_HEADER: 		\textit{#3} & \textit{#4} \\
#+LaTeX_HEADER: \end{tabular*}\vspace{-6pt}}

** List of publications
# ### list publications
#+LaTeX_HEADER: \usepackage{bibentry}
#+LaTeX_HEADER: \nobibliography*

# ### display of my name
#+LaTeX_HEADER: \newcommand{\myname}[1]{\textbf{#1}}

#+LaTeX_HEADER:  \usepackage{url}
