#+TITLE:
#+Author: Brice Ozenne

# header
#+BEGIN_EXPORT latex
\begin{tabular*}{7in}{l@{\extracolsep{\fill}}r}
	\textbf{\Large Brice Ozenne} & \textbf{\today} \\
\end{tabular*}

\bigskip

\begin{minipage}{0.2\linewidth}
\includegraphics[width=\linewidth]{photoId.png}
\end{minipage}
\begin{minipage}{0.75\linewidth}
\begin{tabular*}{7in}{ll@{ }l}
	Nationality&:& french  \\
	Date of birth&:& February 8, 1990  \\
	Personal email&:& \url{brice.ozenne@orange.fr} \\ 
	Personal phone number&:& (+45) 52 328 128 \\ 
        Personal address&:& 3 Emblasgade, 1 t.h., 2100 Copenhagen \O{}, Denmark \\
\end{tabular*}
\end{minipage}
#+END_EXPORT

\bigskip

* CURRENT POSITION                                                   :ignore:
#+LaTeX: \resheading{CURRENT POSITION}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
	November 2015- Now:& \textbf{Postdoctoral researcher} (\href{http://publichealth.ku.dk/staff/?pure=en/persons/540231}{website})\\
	& Section of Biostatistics, University of Copenhagen \\
	& \O{}ster Farimagsgade 5, 1014 Copenhague, Danemark \\ [2mm]
	& Neurobiology Research Unit \\
	& Copenhagen University Hospital, Rigshospitalet \\
	& Building 6931, Blegdamsvej 9, DK-2100 Copenhagen, Denmark
\end{tabular}
#+END_EXPORT

\bigskip
My research work is organized around three topics:
- the development of *latent variable models* for the analysis of
  complex data (software =lavaSearch2=). I apply these developments on
  neuroimaging data and data from psychological tests to investigate
  the relationship between the brain response and depression.

\smallskip

- the analysis of registry data with *time to events outcomes* and
  *competing risks* (software =riskRegression=). My developments have,
  for instance, been applied to compare preventive stroke treatments
  using the danish registry data.

\smallskip

- the development of *generalized pairwise comparisons* to handle
  multiple and heterogenous outcomes (software =BuyseTest=). A typical
  application is the assessment of new chemotherapy where being able
  to balance the benefit (longer in survival time) and the risk
  (treatment side effects) in an interpretable way is important.

* SKILLS                                                             :ignore:
#+LaTeX: \resheading{SKILLS}
** /Language/
French (native language), english (fluent), basics in italian and danish.

** /Software/
Good knowledge of \Rlogo{}, \LaTeX{} and [[https://orgmode.org/][orgmode]]. @@latex:\\@@ 
Basic knowledge but common use of \Cpp{}, lisp (for [[https://www.gnu.org/software/emacs/][GNU Emacs]]) and
git/github (via [[https://magit.vc/][magit]]).


* EDUCATION :ignore:
#+LaTeX: \resheading{EDUCATION}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2012 - 2015 : & Ph.D. in biostatistics, University Lyon 1, Lyon, France. \\
              & Thesis Title: \href{https://tel.archives-ouvertes.fr/tel-01233049/document}{Statistical modelling for the prognosis of stroke patients.} \\ 
              & Advisor: Pr. Delphine Maucort-Boulch and Pr. Norbert Nighoghossian \\ [3mm]
2011 - 2012 : & Master’s degree in biostatistics (\href{https://clarolineconnect.univ-lyon1.fr/icap_website/299/5381}{M2 B3S}), University lyon, Lyon, France. \\ 
              & Carried out in double degree with the École Centrale de Lyon. \\ [3mm]
2009 - 2012 : & Engineering diploma from the École Centrale de Lyon, Lyon, France. \\
              & Erasmus at Politecnico di Milano (2nd semester 2011). \\
\end{tabular}
#+END_EXPORT

\pagebreak[3]

* GRANTS                                                             :ignore:
#+LaTeX: \resheading{GRANTS}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2017-2019: MARIE CURIE Individual Fellowships (200 000\euro) \\
2017-2020: Lundbeck Fellowships (140 000\euro) \\

\end{tabular}
#+END_EXPORT

* SCIENTIFIC OUTPUT                                                  :ignore:
#+LaTeX: \resheading{SCIENTIFIC OUTPUT}
** /Publications (methodological)/

Published:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{ozenne2017riskregression}
    \item \bibentry{peron2016extension}
    \item \bibentry{ozenne2015precision}
    \item \bibentry{ozenne2015spatially}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]

In revision:
#+BEGIN_EXPORT latex
\begin{enumerate}
    \item \bibentry{ozenne20XXestimation}
    \item \bibentry{ozenne20XXsmall}
    \item \bibentry{peron20XXunbiased}
\end{enumerate}
#+END_EXPORT

Submitted:
#+BEGIN_EXPORT latex
\begin{enumerate}
    \item \bibentry{ozenne20XXcontroling}
    \item \bibentry{norgaard20XXpreprocessing} 
\end{enumerate}
#+END_EXPORT

\pagebreak[3]

** /Software development (package for the [[https://www.r-project.org/][R]] software)/
#+LaTeX: \begin{minipage}{0.01\textwidth}
#+LaTeX: \hspace{\fill}
#+LaTeX: \end{minipage}
#+LaTeX: \begin{minipage}{0.92\textwidth}
- *BuyseTest* (author and maintainer): generalized pairwise
  comparisons. Implementation of the extension described in
  citep:peron2016extension,peron20XXunbiased. Available on [[https://cran.r-project.org/web/packages/BuyseTest/index.html][CRAN]] and on [[https://github.com/bozenne/BuyseTest][Github]].

- *lavaSearch2* (author and maintainer): Inference and diagnostic
  tools for latent variable models.  Methodology described in
  citep:ozenne20XXsmall and citep:ozenne20XXcontroling. Available on
  [[https://cran.r-project.org/web/packages/lavaSearch2/index.html][CRAN]] and on [[https://github.com/bozenne/lavaSearch2][Github]]. .

- *riskRegression* (contributor): computation of absolute risks and
  average treatment effects. Methodology described in
  citep:ozenne2017riskregression and
  citep:ozenne20XXestimation. Available on [[https://cran.r-project.org/web/packages/riskRegression/index.html][CRAN]] and on [[https://github.com/tagteam/riskRegression][Github]].
#+LaTeX: \end{minipage}

\pagebreak[3]

** /Publications (clinical applications)/

Published:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{madsen2019psychedelic}
    \item \bibentry{ip2018pre}
    \item \bibentry{borgsted2018amygdala}
    \item \bibentry{hjordt2018self}
    \item \bibentry{foged2018verbal}
    \item \bibentry{staerk2018standard}
    \item \bibentry{hjordt2017season}
    \item \bibentry{beliveau2017high}
    \item \bibentry{stenbaek2017brain}
    \item \bibentry{staerk2017resumption}
    \item \bibentry{fisher2017bdnf}
    \item \bibentry{foged2017safety}
    \item \bibentry{peron2016net}
    \item \bibentry{staerk2016ischaemic}
    \item \bibentry{peron2016assessment}
    \item \bibentry{ozenne2015evaluation}
    \item \bibentry{hermitte2013very}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]

Submitted:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{ebert20XXmolecular}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]

In progress:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{beliveau20XXstructure}
    \item \bibentry{vadskjaer20XXpsychometric}
  \end{enumerate}
#+END_EXPORT

* PEER REVIEW       :ignore:
#+LaTeX: \resheading{PEER REVIEW}
I have reviewed a paper for Biometrics, Statistics in Medicine, and the
International Journal of Biostatistics.
* TEACHING                                                           :ignore:
#+LaTeX: \resheading{TEACHING \hfill L : lecture, PC : practical classes}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2016 - 2017 : & \href{http://publicifsv.sund.ku.dk/~jufo/RepeatedMeasures2016.html}{Statistical analysis of repeated measurements} for Phd students in medical sciences (18h, PC). \\
              & \href{http://publicifsv.sund.ku.dk/~kkho/undervisning/sem2016/}{Structural Equation Models} for Master students in statistics (2h, L). \\
2015 - 2016 : & \href{http://publicifsv.sund.ku.dk/~jufo/RepeatedMeasuresE2015.html}{Statistical analysis of repeated measurements} for Phd students in medical sciences (18h, PC). \\
2014 - 2015 : & \href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215839}{Bayesian statistics} for Master students in public health (6h, PC).\\
              & \href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215839}{Survival Analysis} for Master students in public health (18h, PC).\\
2013 - 2014 : & \href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215839}{Bayesian statistics} for Master students in public health (6h, PC).
\end{tabular}
#+END_EXPORT

* SUPERVISION                                                        :ignore:
#+LaTeX: \resheading{SUPERVISION}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2015 - Now &:& \textbf{statistical consultant} at NRU (\href{https://nru.dk/}{Neurobiology Research Unit}).  \\ 
\multicolumn{3}{l}{Advise neuroscientists and psychologists.} \\ [3mm]
\end{tabular}
#+END_EXPORT

\bigskip

Co-superviser of *master 2* students:
\smallskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Ceren Tozlu \\
\multicolumn{3}{l}{Comparison of classification methods for tissue outcome after ischemic stroke.} \\ [3mm]
2019 &:& Alice Brouquet-Laglaire \\
\multicolumn{3}{l}{Comparison of inference methods for generalized pairwise comparisons.} \\ [3mm]
\end{tabular}
#+END_EXPORT

\bigskip

Contribution to the supervision of *Phd* students:
\smallskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2015-2018 &:& Vincent Beliveau \\
\multicolumn{3}{l}{Functional and Molecular Imaging of the Serotonin System in the Human Brain} \\ [3mm]
2016-2019 &:& Martin N\o{}rgaard \\
\multicolumn{3}{l}{Optimizing preprocessing pipelines in PET/MRI neuroimaging} \\ [3mm]
\end{tabular}
#+END_EXPORT

* ORAL COMMUNICATIONS                                                         :ignore:
#+LaTeX: \resheading{ORAL COMMUNICATIONS}
Oral presentation at international conferences: 
\smallskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Image segmentation using a spatially regularized mixture model \\
&& \href{https://www.biometricsociety.org/meetings-events/ibcs/}{IBC}, Florence, Italia \\
2015 &:& \href{https://r2015-grenoble.sciencesconf.org/66037}{MRIaggr : un package pour la gestion et le traitement de données multivariées d'imagerie} \\
&& Rencontres R, Grenoble, France \\
2016 &:& \href{http://cmstatistics.org/RegistrationsV2/COMPSTAT2016/viewSubmission.php?in=440&token=29584n1s18p97n65o7p1r5n36sopq0n4}{Penalized latent variable models} \\
&& Computational statistics, Oviedo, Spain \\
2017 &:& Assessing treatment effects on registry data in presence of competing risks \\ 
&& \href{http://www.iscb2017.info/}{ISCB}, Vigo, Spain \\
2019 &:& Generalized pairwise comparisons for right-censored time to event outcomes \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhagen, Denmark \\
\end{tabular}
#+END_EXPORT

\bigskip

Chairman at international conferences:
\smallskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2019 &:& Mathematical Statistics \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhagen, Denmark
\end{tabular}
#+END_EXPORT


* Reference :ignore:

# bibliographystyle:apalike
 bibliographystyle:plainnat

 # [[bibliography:publicationBO.bib]]
[[nobibliography:publicationBO.bib]]

* CONFIG :noexport:
#+LANGUAGE: en
#+LaTeX_CLASS: org-article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+OPTIONS:   title:nil author:nil toc:nil todo:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t
#+options: num:nil

#+LaTeX_HEADER: \pagestyle{empty} % no page numbering
#+LATEX_HEADER: \usepackage[french]{babel}

** Notations
#+LaTeX_HEADER: \newcommand{\Rlogo}{\textbf{\textsf{R}}}
#+LaTeX_HEADER: \newcommand{\Cpp}{C\nolinebreak\hspace{-.05em}\raisebox{.4ex}{\tiny\bf +}\nolinebreak\hspace{-.10em}\raisebox{.4ex}{\tiny\bf +}}
#+LaTeX_HEADER: \usepackage{eurosym} % euro symbol

** Sections
#+LaTeX_HEADER: \usepackage{titlesec}
#+LaTeX_HEADER: \titleformat{\section}{\large}{\thesection}{1em}{}

#+LaTeX_HEADER: \titlespacing*{\section}{0pt}{0.25\baselineskip}{0.25\baselineskip}
** Margin
#+LaTeX_HEADER: \geometry{
#+LaTeX_HEADER: left=20mm,
#+LaTeX_HEADER: right=20mm,
#+LaTeX_HEADER: top=20mm,
#+LaTeX_HEADER: bottom=20mm
#+LaTeX_HEADER: }

** Line spacing
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER: \renewcommand{\baselinestretch}{1.1}

** CV
# from https://www.sharelatex.com/templates/cv-or-resume/sc_cv
#+LaTeX_HEADER: \usepackage{framed}
#+LaTeX_HEADER: \usepackage{tocloft}

#+LaTeX_HEADER: \newlength{\outerbordwidth}
#+LaTeX_HEADER: \raggedbottom
#+LaTeX_HEADER: \raggedright

#+LaTeX_HEADER: \setlength{\outerbordwidth}{3pt}  % Width of border outside of title bars
#+LaTeX_HEADER: \definecolor{shadecolor}{gray}{0.75}  % Outer background color of title bars (0 = black, 1 = white)
#+LaTeX_HEADER: \definecolor{shadecolorB}{gray}{0.93}  % Inner background color of title bars

#+LaTeX_HEADER: \usepackage{mdframed}
#+LaTeX_HEADER: \newcommand{\resitem}[1]{\item #1 \vspace{-2pt}}

#+LaTeX_HEADER: \newcommand{\resheading}[1]{
#+LaTeX_HEADER: \vspace{8pt}
#+LaTeX_HEADER:  \parbox{\textwidth}{\setlength{\FrameSep}{\outerbordwidth}
#+LaTeX_HEADER:     \begin{shaded}
#+LaTeX_HEADER: \setlength{\fboxsep}{0pt}\framebox[\textwidth][l]{\setlength{\fboxsep}{4pt}\fcolorbox{shadecolorB}{shadecolorB}{\textbf{\sffamily{\mbox{~}\makebox[6.762in][l]{\large #1} \vphantom{p\^{E}}}}}}
#+LaTeX_HEADER:     \end{shaded}
#+LaTeX_HEADER:   }\vspace{-5pt}
#+LaTeX_HEADER: }
#+LaTeX_HEADER: \newcommand{\ressubheading}[4]{
#+LaTeX_HEADER: \begin{tabular*}{6.5in}{l@{\cftdotfill{\cftsecdotsep}\extracolsep{\fill}}r}
#+LaTeX_HEADER: 		\textbf{#1} & #2 \\
#+LaTeX_HEADER: 		\textit{#3} & \textit{#4} \\
#+LaTeX_HEADER: \end{tabular*}\vspace{-6pt}}

** List of publications
# ### list publications
#+LaTeX_HEADER: \usepackage{bibentry}
#+LaTeX_HEADER: \nobibliography*

# ### display of my name
#+LaTeX_HEADER: \newcommand{\myname}[1]{\textbf{#1}}

#+LaTeX_HEADER:  \usepackage{url}
