#+TITLE:
#+Author: Brice Ozenne

# header
#+BEGIN_EXPORT latex
\begin{tabular*}{7in}{l@{\extracolsep{\fill}}r}
	\textbf{\Large Brice Ozenne} & \textbf{\today} \\
\end{tabular*}

\bigskip

\begin{minipage}{0.2\linewidth}
\includegraphics[width=\linewidth]{photoId.png}
\end{minipage}
\begin{minipage}{0.75\linewidth}
\begin{tabular*}{7in}{ll@{ }l}
	Nationalité&:& française  \\
	Né&:& le 8 février 1990 à Saint Hilaire du Harcouët (50)  \\
	Courriel personnel&:& \url{brice.mh.ozenne@gmail.com} \\ 
	Téléphone personnel&:& (+45) 52 328 128 \\ 
        Adresse personnelle&:& Nordre Teglkaj 18, 5 t.h., 2450 Copenhagen SV, Danemark \\
\end{tabular*}
\end{minipage}
#+END_EXPORT


* Poste                                                              :ignore:
#+LaTeX: \resheading{Activité de recherche}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
	Novembre 2015- Actuellement:& \textbf{Post doctorant} (\href{http://publichealth.ku.dk/staff/?pure=en/persons/540231}{page personnelle})\\
	& Section of Biostatistics, University of Copenhagen \\
	& \O{}ster Farimagsgade 5, 1014 Copenhague, Danemark \\
	& \\
	& Neurobiology Research Unit \\
	& Copenhagen University Hospital, Rigshospitalet \\
	& Building 6931, Blegdamsvej 9, DK-2100 Copenhagen, Denmark
\end{tabular}
#+END_EXPORT

\bigskip

Mon travail de recherche s'articule autour de trois thèmes:
- le développement de *modèles à variables latentes* pour l'analyse de
  données complexes (logiciel =lavaSearch2=). Ces travaux trouvent leur application dans
  l'analyse des données issues de neuroimagerie ou de tests
  psychologiques.

\smallskip

- l'analyse de données de *survie en présence de risques compétitifs*
  sur données de registres (logiciel =riskRegression=). Ces méthodes sont utilisées pour comparer
  l'efficacité de traitements préventifs de maladies cardiovasculaires
  à l'aide des données des registres danois.

\smallskip

- l'extension des *méthodes de comparaison par paires*,
  permettant d'évaluer la balance bénéfice-risque d'un traitement avec
  des critères de jugement de différentes natures (logiciel =BuyseTest=). Plusieurs
  applications de cette méthode ont été publiées lors de l'évaluation
  de chimiothérapies. 

* Compétences                                                        :ignore:
#+LaTeX: \resheading{Compétences}
** /Linguistiques/
Français (langue maternelle), anglais (courant), notions d'italien et de danois.

** /Logicielles/
Bonne connaissance de \Rlogo{}, \LaTeX{} et [[https://orgmode.org/][orgmode]]. @@latex:\\@@
Utilisation courante mais basique de \Cpp{}, lisp (pour [[https://www.gnu.org/software/emacs/][GNU Emacs]]),
git/github et inkscape.

* Formation                                                          :ignore:
#+LaTeX: \resheading{Formation Universitaire}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2012 - 2015 : & Doctorat en biostatistiques, Université Lyon 1. \\
\multicolumn{2}{l}{Directeur/Co-directeur: Pr. Delphine Maucort-Boulch / Pr. Norbert Nighoghossian} \\ 
\multicolumn{2}{l}{Sujet: \href{https://tel.archives-ouvertes.fr/tel-01233049/document}{Modélisation statistique pour le pronostic de patients atteints d’un Accident Vasculaire Cérébral}} \\ 
\multicolumn{2}{l}{Développement d'outils de segmentation d'image, de prédiction et d'évaluation dans le cadre de l'AVC.}\\
\multicolumn{2}{l}{Le produit final étant une méthode permettant une prédiction personnalisée de l'extension du volume}\\
\multicolumn{2}{l}{de l'AVC après admission du patient à l'hopital.} \\ [3mm]
\end{tabular}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2012 : & Stage de master 2, Hospices Civils de Lyon. \\
\multicolumn{2}{l}{Encadrant: Pr. Delphine Maucort-Boulch} \\ 
\multicolumn{2}{l}{Sujet: mise en place d’un critère IRM de reperfusion lors d'un AVC} \\ 
\multicolumn{2}{l}{Le stage a permis de proposer un critère de reperfusion basé sur trois mesures IRM du niveau} \\
\multicolumn{2}{l}{de perfusion et de le valider au regard de critères cliniques.} \\  [3mm]
\end{tabular}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2009 - 2012 : &  École Centrale de Lyon, formation d'ingénieur généraliste avec spécialisation en statistiques \\ 
              & Erasmus à l'université Politecnico di Milano (2nd semestre 2011) \\
              & Master en biostatistiques à l'Université Lyon 1 en double diplôme (\href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215838}{M2 B3S}). \\
\end{tabular}
#+END_EXPORT

* Financement                                                        :ignore:
#+LaTeX: \resheading{Financement}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2017-2019: MARIE CURIE Individual Fellowships (200 000\euro) \\
2017-2020: Lundbeck Fellowships (140 000\euro) \\

\end{tabular}
#+END_EXPORT

* Production scientifique                                            :ignore:
#+LaTeX: \resheading{Production scientifique}
** /Publications (méthodologiques)/

Publié:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{ozenne2017riskregression}
    \item \bibentry{peron2016extension}
    \item \bibentry{ozenne2015precision}
    \item \bibentry{ozenne2015spatially}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]

En révision:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{ozenne20XXestimation}
    \item \bibentry{ozenne20XXsmall}
    \item \bibentry{peron20XXunbiased}
\end{enumerate}
#+END_EXPORT

\pagebreak[3]

Soumis:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{ozenne20XXcontroling}    
    \item \bibentry{norgaard20XXpreprocessing}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]

** /Développement logiciel (librairies pour le logiciel [[https://www.r-project.org/][R]])/
#+LaTeX: \begin{minipage}{0.01\textwidth}
#+LaTeX: \hspace{\fill}
#+LaTeX: \end{minipage}
#+LaTeX: \begin{minipage}{0.92\textwidth}
- *BuyseTest* (Créateur et mainteneur) : Comparisons par paires
  généralisées. Implémentation de la méthode décrite dans
  citep:peron2016extension,peron20XXunbiased. Disponible sur le [[https://cran.r-project.org/web/packages/BuyseTest/index.html][CRAN]]
  et sur [[https://github.com/bozenne/BuyseTest][Github]].

- *lavaSearch2* (Créateur et mainteneur) : Inférence et outils
  diagnostiques dans les modèles à variables latentes. Papier
  décrivant la méthode soumis (citep:ozenne20XXsmall and citep:ozenne20XXcontroling). Disponible sur le [[https://cran.r-project.org/web/packages/lavaSearch2/index.html][CRAN]] et sur [[https://github.com/bozenne/lavaSearch2][Github]]. .

- *riskRegression* (Contributeur) : Calculateur du risque
  d'évènenement en présence de risques compétitifs. Implémentation de
  la méthode décrite dans citep:ozenne2017riskregression et
  citep:ozenne20XXestimation. Disponible sur le [[https://cran.r-project.org/web/packages/riskRegression/index.html][CRAN]] et sur [[https://github.com/tagteam/riskRegression][Github]].
#+LaTeX: \end{minipage}

\pagebreak[3]

** /Publications (applications cliniques)/

Publié:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{madsen2019psychedelic}
    \item \bibentry{ip2018pre}
    \item \bibentry{borgsted2018amygdala}
    \item \bibentry{hjordt2018self}
    \item \bibentry{foged2018verbal}
    \item \bibentry{staerk2018standard}
    \item \bibentry{hjordt2017season}
    \item \bibentry{beliveau2017high}
    \item \bibentry{stenbaek2017brain}
    \item \bibentry{staerk2017resumption}
    \item \bibentry{fisher2017bdnf}
    \item \bibentry{foged2017safety}
    \item \bibentry{peron2016net}
    \item \bibentry{staerk2016ischaemic}
    \item \bibentry{peron2016assessment}
    \item \bibentry{ozenne2015evaluation}
    \item \bibentry{hermitte2013very}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]

En révision:
#+BEGIN_EXPORT latex
\begin{enumerate}
    \item \bibentry{ebert20XXmolecular}
\end{enumerate}
#+END_EXPORT

\pagebreak[3]

En cours de rédaction:
#+BEGIN_EXPORT latex
\begin{enumerate}
    \item \bibentry{beliveau20XXstructure}
    \item \bibentry{vadskjaer20XXpsychometric}
\end{enumerate}
#+END_EXPORT

\pagebreak[3]

* Relecture d'articles                                               :ignore:
#+LaTeX: \resheading{Relecture d'article}
J'ai relu un article pour Biometrics, Statistics in Medicine, et
International Journal of Biostatistics.
* Enseignement                                                       :ignore:
#+LaTeX: \resheading{Enseignement \hfill CM : cours magistral, TD : travaux dirigés}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2016 - 2017 : & \href{http://publicifsv.sund.ku.dk/~jufo/RepeatedMeasures2016.html}{Analyse statistique de données répétées}. TD pour doctorants en médecine (18h). \\
              & \href{http://publicifsv.sund.ku.dk/~kkho/undervisning/sem2016/}{Modèles d'équations structurelles}. CM pour étudiants de master en statistiques (2h). \\
2015 - 2016 : & \href{http://publicifsv.sund.ku.dk/~jufo/RepeatedMeasuresE2015.html}{Analyse statistique de données répétées}. TD pour doctorants en médecine (18h). \\
2014 - 2015 : & \href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215839}{Modèles de Survie}. TD pour étudiants de master en santé publique (6h).\\
              & \href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215839}{Statistique bayésienne}. TD pour étudiants de master en santé publique (18h).\\
2013 - 2014 : & \href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215839}{Statistique bayésienne}. TD pour étudiants de master en santé publique (6h).\\
\end{tabular}
#+END_EXPORT

* Encadrement                                                        :ignore:
#+LaTeX: \resheading{Encadrement}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2015 - Actuellement &:& \textbf{consultant} en statistiques pour NRU (\href{https://nru.dk/}{Neurobiology Research Unit}).  \\ 
\multicolumn{3}{l}{ Conseille les chercheurs en neuroscience dans l'analyse de leurs données et la rédaction d'articles.} \\ [3mm]
\end{tabular}
#+END_EXPORT

\bigskip

Co-encadrant d'étudiant en *master 2*:
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Ceren Tozlu \\
\multicolumn{3}{l}{Comparaison de méthodes de classification pour la prédiction du devenir des tissus lors d'un AVC.} \\ [3mm]
2019 &:& Alice Brouquet-Laglaire \\
\multicolumn{3}{l}{Comparaison de méthodes d’inférence dans le cadre des comparaisons par paires généralisées.} \\ [3mm]
\end{tabular}
#+END_EXPORT

\pagebreak[3]

Participation à l'encadrement de *thèses*:
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2015-2018 &:& Vincent Beliveau \\
\multicolumn{3}{l}{Imagerie fonctionnelle et moléculaire du système cérébral de sérotonine chez l'humain} \\ [3mm]
2016-2019 &:& Martin N\o{}rgaard \\
\multicolumn{3}{l}{Optimisation de la stratégie de traitement des données IRM et TEP en neuroimagerie} \\ [3mm]
\end{tabular}
#+END_EXPORT

* Communications orales                                             :ignore:
#+LaTeX: \resheading{Conférences}
Présentations orales lors de conférences internationales: 
\smallskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Image segmentation using a spatially regularized mixture model \\
&& \href{https://www.biometricsociety.org/meetings-events/ibcs/}{IBC}, Florence, Italie \\
2015 &:& \href{https://r2015-grenoble.sciencesconf.org/66037}{MRIaggr : un package pour la gestion et le traitement de données multivariées d'imagerie} \\
&& Rencontres R, Grenoble, France \\
2016 &:& \href{http://cmstatistics.org/RegistrationsV2/COMPSTAT2016/viewSubmission.php?in=440&token=29584n1s18p97n65o7p1r5n36sopq0n4}{Penalized latent variable models} \\
&& Computational statistics, Oviedo, Espagne \\
2017 &:& Assessing treatment effects on registry data in presence of competing risks \\ 
&& \href{http://www.iscb2017.info/}{ISCB}, Vigo, Espagne \\
2019 &:& Generalized pairwise comparisons for right-censored time to event outcomes \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhague, Danemark \\
\end{tabular}
#+END_EXPORT

\bigskip

Responsable de session ("chairman"):
\smallskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2019 &:& Mathematical Statistics \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhague, Danemark
\end{tabular}
#+END_EXPORT

* Reference                                                          :ignore:

# bibliographystyle:apalike
 bibliographystyle:plainnat

 # [[bibliography:publicationBO.bib]]
[[nobibliography:publicationBO.bib]]

* CONFIG :noexport:
#+LANGUAGE: fr
#+LaTeX_CLASS: org-article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+OPTIONS:   title:nil author:nil toc:nil todo:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t
#+options: num:nil

#+LaTeX_HEADER: \pagestyle{empty} % no page numbering
#+LATEX_HEADER: \usepackage[french]{babel}

** Notations
#+LaTeX_HEADER: \newcommand{\Rlogo}{\textbf{\textsf{R}}}
#+LaTeX_HEADER: \newcommand{\Cpp}{C\nolinebreak\hspace{-.05em}\raisebox{.4ex}{\tiny\bf +}\nolinebreak\hspace{-.10em}\raisebox{.4ex}{\tiny\bf +}}
#+LaTeX_HEADER: \usepackage{eurosym} % euro symbol

** Sections
#+LaTeX_HEADER: \usepackage{titlesec}
#+LaTeX_HEADER: \titleformat{\section}{\large}{\thesection}{1em}{}

#+LaTeX_HEADER: \titlespacing*{\section}{0pt}{0.25\baselineskip}{0.25\baselineskip}
** Margin
#+LaTeX_HEADER: \geometry{
#+LaTeX_HEADER: left=20mm,
#+LaTeX_HEADER: right=20mm,
#+LaTeX_HEADER: top=20mm,
#+LaTeX_HEADER: bottom=20mm
#+LaTeX_HEADER: }

** Line spacing
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER: \renewcommand{\baselinestretch}{1.1}

** CV
# from https://www.sharelatex.com/templates/cv-or-resume/sc_cv
#+LaTeX_HEADER: \usepackage{framed}
#+LaTeX_HEADER: \usepackage{tocloft}

#+LaTeX_HEADER: \newlength{\outerbordwidth}
#+LaTeX_HEADER: \raggedbottom
#+LaTeX_HEADER: \raggedright

#+LaTeX_HEADER: \setlength{\outerbordwidth}{3pt}  % Width of border outside of title bars
#+LaTeX_HEADER: \definecolor{shadecolor}{gray}{0.75}  % Outer background color of title bars (0 = black, 1 = white)
#+LaTeX_HEADER: \definecolor{shadecolorB}{gray}{0.93}  % Inner background color of title bars

#+LaTeX_HEADER: \usepackage{mdframed}
#+LaTeX_HEADER: \newcommand{\resitem}[1]{\item #1 \vspace{-2pt}}

#+LaTeX_HEADER: \newcommand{\resheading}[1]{
#+LaTeX_HEADER: \vspace{8pt}
#+LaTeX_HEADER:  \parbox{\textwidth}{\setlength{\FrameSep}{\outerbordwidth}
#+LaTeX_HEADER:     \begin{shaded}
#+LaTeX_HEADER: \setlength{\fboxsep}{0pt}\framebox[\textwidth][l]{\setlength{\fboxsep}{4pt}\fcolorbox{shadecolorB}{shadecolorB}{\textbf{\sffamily{\mbox{~}\makebox[6.762in][l]{\large #1} \vphantom{p\^{E}}}}}}
#+LaTeX_HEADER:     \end{shaded}
#+LaTeX_HEADER:   }\vspace{-5pt}
#+LaTeX_HEADER: }
#+LaTeX_HEADER: \newcommand{\ressubheading}[4]{
#+LaTeX_HEADER: \begin{tabular*}{6.5in}{l@{\cftdotfill{\cftsecdotsep}\extracolsep{\fill}}r}
#+LaTeX_HEADER: 		\textbf{#1} & #2 \\
#+LaTeX_HEADER: 		\textit{#3} & \textit{#4} \\
#+LaTeX_HEADER: \end{tabular*}\vspace{-6pt}}

** List of publications
# ### list publications
#+LaTeX_HEADER: \usepackage{bibentry}
#+LaTeX_HEADER: \nobibliography*

# ### display of my name
#+LaTeX_HEADER: \newcommand{\myname}[1]{\textbf{#1}}

#+LaTeX_HEADER:  \usepackage{url}
