#+TITLE:
#+Author: Brice Ozenne

# header

#+BEGIN_EXPORT latex
\begin{tabular*}{7in}{l@{\extracolsep{\fill}}r}
	\textbf{\Large Brice Ozenne} & \textbf{\today} \\
\end{tabular*}

\bigskip

\begin{minipage}{0.2\linewidth}
\includegraphics[width=\linewidth]{photoId.png}
\end{minipage}
\begin{minipage}{0.75\linewidth}
\begin{tabular*}{7in}{ll@{ }l}
	Nationalité&:& française  \\
	Né&:& le 8 février 1990 à Saint Hilaire du Harcouët (50)  \\
	Courriel personnel&:& \url{brice.mh.ozenne@gmail.com} \\ 
	Téléphone personnel&:& (+45) 52 328 128 \\ 
        Adresse personnelle&:& Nordre Teglkaj 18, 5 t.h., 2450 Copenhague SV, Danemark \\
        Site internet&:& \url{https://bozenne.github.io/} \\
        Github &:& \url{https://github.com/bozenne/} \\
\end{tabular*}
\end{minipage}
#+END_EXPORT

* Profil                                                             :ignore:
#+LaTeX: \resheading{Profil}
** /Position actuelle:/

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
	Depuis novembre 2015 :& \textbf{Post-doctorat en biostatistiques} avec une position partagée entre: \\ [2mm]
      & - une unité de recherche en biostatistiques \\
	& \href{https://biostat.ku.dk/staff_/?pure=en/persons/540231}{Section of Biostatistics}, University of Copenhagen \\
	& \O{}ster Farimagsgade 5, 1014 Copenhague, Danemark \\ [2mm]
	& - une unité de recherche en neuroscience \\
	& \href{https://nru.dk/index.php/staff-list/post-docs/110-brice-ozenne}{Neurobiology Research Unit} \\
	& Copenhagen University Hospital, Rigshospitalet \\
	& Building 6931, Blegdamsvej 9, DK-2100 Copenhague, Danemark \\ [2mm]
	& où j'exerce conjointement une activité de recherche en biostatistiques, \\ 
      & de consultant en statistiques et une activité pédagogique.
\end{tabular}
#+END_EXPORT

\bigskip
# description

** /Thématiques de recherche:/
#+LaTeX: { \justify
Mon travail de recherche s'articule autour de trois thématiques:
- le développement de *modèles à variables latentes* pour l'analyse de
  données en neuroscience - voir les publications
  cite:ebert2019molecular,stenbaek2017brain,fisher2017bdnf pour des
  exemples d'application. D'un point de vue méthodologique, je
  m'intéresse à *l'estimation et l'inférence en petits échantillons*
  citep:ozenne2020small ainsi qu'à développer des corrections
  efficaces en présence de *tests multiples*
  citep:ozenne20XXcontroling. Ces développements sont implémentés dans
  la librairie R =lavaSearch2=.
  
\bigskip

- l'analyse de données de registre en présence de *censure à droite,
  risques compétitifs, et variables de confusion*, en particulier pour
  comparer l'efficacité de traitements préventifs de maladies
  cardiovasculaires
  citep:staerk2016ischaemic,staerk2017resumption,staerk2018standard. En
  utilisant des résultats de la *théorie semi-paramétrique*, j'ai
  développé un estimateur robuste basé sur plusieurs modèles de
  régressions et utilisé sa fonction d'influence pour obtenir sa
  distribution asymptotique citep:ozenne2020estimation. Cette méthode
  est implémentée dans la fonction =ate= de la librairie R
  =riskRegression=.

\bigskip

- l'extension des *méthodes de comparaison par paires* (GPC) aux
  données censurées citep:peron2016extension. Les GPC permettent
  d'analyser simultanément plusieurs critères de jugements et donc
  d'évaluer la balance bénéfice-risque d'un traitement. Une
  application typique est de proposer une statistique reflétant à la
  fois les gains en survie et les effets secondaires de traitements
  anti-cancéreux citep:peron2016net,peron2016assessment. Je
  m'intéresse par exemple à la théorie des U-statistiques pour obtenir
  la distribution asymptotique de certains estimateurs implémentés
  dans la librairie R =BuyseTest= (article en cours de rédaction).
#+LaTeX: }

\bigskip

** /Autres domaines d'intérêt en statistiques:/
- Spline de lissages et modélisation fonctionnelle
- Inférence causale et régimes de traitement dynamiques
- Inférence statistique après sélection 

** /Compétences logicielles/
Maitrise de \Rlogo{}, \LaTeX{} et [[https://orgmode.org/][orgmode]]. @@latex:\\@@
Utilisation courante mais basique de \Cpp{}, Lisp (pour [[https://www.gnu.org/software/emacs/][GNU Emacs]]),
Git/Github et Inkscape.

** /Compétences Linguistiques/
Français (langue maternelle), anglais (courant), danois
(intermédiaire), notions d'italien.

* Formation                                                          :ignore:
#+LaTeX: \resheading{Formation Universitaire}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2012 - 2015 : & \textbf{Doctorat en biostatistiques}, Université Lyon 1. \\
\multicolumn{2}{l}{\emph{Directeur/Co-directeur}: Pr. Delphine Maucort-Boulch / Pr. Norbert Nighoghossian} \\ 
\multicolumn{2}{l}{Sujet: \href{https://tel.archives-ouvertes.fr/tel-01233049/document}{modélisation statistique pour le pronostic de patients atteints d’un Accident Vasculaire Cérébral}} \\ 
\multicolumn{2}{l}{\hphantom{Sujet:} Développement d'outils de segmentation d'image et de prédiction appliqués à l'AVC.}\\
\multicolumn{2}{l}{\hphantom{Sujet:} Le produit final étant une prédiction personnalisée de l'extension du volume de l'AVC}\\
\multicolumn{2}{l}{\hphantom{Sujet:} à l'admission du patient à l'hopital.} \\ [3mm]
\end{tabular}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2012 : & \textbf{Stage de master 2}, Hospices Civils de Lyon. \\
\multicolumn{2}{l}{\emph{Encadrant}: Pr. Delphine Maucort-Boulch} \\ 
\multicolumn{2}{l}{Sujet: mise en place d’un critère IRM de reperfusion lors d'un AVC} \\ 
\multicolumn{2}{l}{\hphantom{Sujet:} Le stage a permis de proposer un critère de reperfusion basé sur trois mesures IRM} \\
\multicolumn{2}{l}{\hphantom{Sujet:} du niveau de perfusion et de le valider au regard de critères cliniques.} \\  [3mm]
\end{tabular}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2009 - 2012 : & \textbf{Formation d'ingénieur avec spécialisation en statistiques} à École Centrale de Lyon \\ 
              & \textbf{Erasmus} à l'Université Politecnico di Milano (2nd semestre 2011) \\
              & \textbf{Master en biostatistiques} à l'Université Lyon 1 en double diplôme (\href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215838}{M2 B3S}). \\
\end{tabular}
#+END_EXPORT

\clearpage

* Enseignement et encadrement d'étudiants                                 :ignore:
#+LaTeX: \resheading{Enseignement et encadrement d'étudiants}
Enseignement (CM : cours magistral, TD : travaux dirigés):

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2015 - 2020 : & \href{http://publicifsv.sund.ku.dk/~jufo/RepeatedMeasures2019.html}{Analyse statistique de données répétées}. TD pour doctorants en médecine (18h). \\
2016 - 2017 : & Modèles d'équations structurelles. CM pour étudiants de master en statistiques (2h). \\
2014 - 2015 : & \href{https://clarolineconnect.univ-lyon1.fr/resource/open/file/2733301}{Modèles de Survie}. TD pour étudiants de master en santé publique (6h).\\
2013 - 2015 : & \href{https://clarolineconnect.univ-lyon1.fr/resource/open/file/2733304}{Statistique bayésienne}. TD pour étudiants de master en santé publique (18h).\\
\end{tabular}
#+END_EXPORT

\bigskip

Exposés pédagogiques pour chercheurs en neuroscience sur des
outils/problématiques statistiques:
- [[https://bozenne.github.io/doc/Talks/2017-XNRU-power.pdf][Do we need more power?]] ([[https://www.nru.dk/images/News/NeurobiologyResearchUnit-Christmas-symposium2017.pdf][NRU Christmas Symposium 2017]]).
- [[https://bozenne.github.io/doc/Talks/2018-XNRU-DAGs.pdf][To adjust or not adjust, that is the question]] (NRU Christmas Symposium 2018).
- [[https://bozenne.github.io/doc/Talks/2019-XNRU-multcomp.pdf][A refresher on multiple comparisons]]? ([[https://nru.dk/index.php/news-menu/279-nru-christimas-symposium-2019][NRU Christmas Symposium 2019]]).

\bigskip

Co-encadrant d'étudiant en *master 2*: 

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Ceren Tozlu \\
\multicolumn{3}{l}{Comparaison de méthodes de classification pour la prédiction du devenir des tissus lors} \\ 
\multicolumn{3}{l}{d'un AVC \citep{tozlu2019comparison}.} \\ [3mm]
2019 &:& Alice Brouquet-Laglaire \\
\multicolumn{3}{l}{Comparaison de méthodes d’inférence dans le cadre des comparaisons par paires généralisées.} \\ [3mm]
\end{tabular}
#+END_EXPORT

* Financement                                                        :ignore:
#+LaTeX: \resheading{Financement}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2017-2019: \href{https://nru.dk/index.php/news-menu/187-marie-curie-grant-to-nru}{MARIE CURIE Individual Fellowships} (200 000\euro, EU H2020-MSCA-IF-2016 746850) \\
2017-2020: Lundbeck Fellowships (140 000\euro, R231-2016-3236) \\
\end{tabular}
#+END_EXPORT

* Production scientifique                                            :ignore:
#+LaTeX: \resheading{Production scientifique \hfill \href{https://scholar.google.com/citations?user=rJMNP7YAAAAJ&hl=fr}{lien google scholar}}
** /Publications (méthodologiques)/

Publié:
#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{ozenne2020small}
    \item \bibentry{verbeeck2020evaluation}
    \item \bibentry{ozenne2020estimation}
    \item \bibentry{norgaard2019preprocessing}
    \item \bibentry{ozenne2017riskregression}
    \item \bibentry{peron2016extension}
    \item \bibentry{ozenne2015precision}
    \item \bibentry{ozenne2015spatially}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]

En révision:
#+BEGIN_EXPORT latex
 \begin{enumerate}[resume]
    \item \bibentry{ozenne20XXcontroling}
    \item \bibentry{peron20XXunbiased}
    \item \bibentry{cantagallo20XXnew}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]


** /Publications (applications cliniques)/

Publié:
#+BEGIN_EXPORT latex
 \begin{enumerate}[resume]
    \item \bibentry{dam2020hot}
    \item \bibentry{hjordt2020psychometric}
    \item \bibentry{beliveau2020structure}
    \item \bibentry{madsen2020single}
    \item \bibentry{ozenne2019individualized}
    \item \bibentry{ebert2019molecular}
    \item \bibentry{madsen2019psychedelic}
    \item \bibentry{tozlu2019comparison}
    \item \bibentry{ip2018pre}
    \item \bibentry{borgsted2018amygdala}
    \item \bibentry{hjordt2018self}
    \item \bibentry{foged2018verbal}
    \item \bibentry{staerk2018standard}
    \item \bibentry{hjordt2017season}
    \item \bibentry{beliveau2017high}
    \item \bibentry{stenbaek2017brain}
    \item \bibentry{staerk2017resumption}
    \item \bibentry{fisher2017bdnf}
    \item \bibentry{foged2017safety}
    \item \bibentry{peron2016net}
    \item \bibentry{staerk2016ischaemic}
    \item \bibentry{peron2016assessment}
    \item \bibentry{ozenne2015evaluation}
    \item \bibentry{hermitte2013very}
\end{enumerate}
#+END_EXPORT

\clearpage

* Production logicielle                                              :ignore:
#+LaTeX: \resheading{Production logicielle}

Librairies de fonctions pour le logiciel [[https://www.r-project.org/][R]]:
- *BuyseTest* (Créateur et mainteneur) : Comparisons par paires
  généralisées. Implémentation de la méthode décrite dans
  citep:peron2016extension,peron20XXunbiased. Disponible sur le [[https://cran.r-project.org/web/packages/BuyseTest/index.html][CRAN]]
  et sur [[https://github.com/bozenne/BuyseTest][Github]].

- *lavaSearch2* (Créateur et mainteneur) : Inférence et outils
  diagnostiques dans les modèles à variables latentes. Papier
  décrivant la méthode soumis (citep:ozenne2020small and citep:ozenne20XXcontroling). Disponible sur le [[https://cran.r-project.org/web/packages/lavaSearch2/index.html][CRAN]] et sur [[https://github.com/bozenne/lavaSearch2][Github]]. .

- *riskRegression* (Contributeur) : Calculateur du risque
  d'évènenement en présence de risques compétitifs. Implémentation de
  la méthode décrite dans citep:ozenne2017riskregression et
  citep:ozenne2020estimation. Disponible sur le [[https://cran.r-project.org/web/packages/riskRegression/index.html][CRAN]] et sur [[https://github.com/tagteam/riskRegression][Github]].

\bigskip

Librairie pour le logiciel [[https://www.gnu.org/software/emacs/][emacs]]:
- *emacs-config* (Créateur et mainteneur) : configuration facilitant
  l'intéraction avec R/C++/orgmode/latex/git. Disponible sur sur
  [[https://github.com/bozenne/emacs-config][Github]].

* Relecture d'articles                                               :ignore:
#+LaTeX: \resheading{Relecture d'article}
Biometrics, Statistics in Medicine, et International Journal of Biostatistics.

* Communications orales                                             :ignore:
#+LaTeX: \resheading{Conférences}
Présentations orales lors de conférences internationales: 

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Lesion Segmentation using a Spatially Regularized Mixture Model \\
&& \href{http://conferences.nib.si/AS2014/default.htm}{Applied Statistics}, Ribno, Slovénie \hfill (\href{https://bozenne.github.io/doc/Talks/2014-Applied_statistics-Lesion_Segmentation.pdf}{support de présentation}) \\ [3mm]
2015 &:& MRIaggr : un package pour la gestion et le traitement de données multivariées d'imagerie\\
&& \href{https://r2015-grenoble.sciencesconf.org/66037}{Rencontres R, Grenoble, France}  \hfill   (\href{https://bozenne.github.io/doc/Talks/2015-R-MRIaggr.pdf}{support de présentation})  \\ [3mm]
2016 &:& Penalized latent variable models  \\
&& \href{http://cmstatistics.org/RegistrationsV2/COMPSTAT2016/viewSubmission.php?in=440&token=29584n1s18p97n65o7p1r5n36sopq0n4}{Computational statistics}, Oviedo, Espagne \hfill (\href{https://bozenne.github.io/doc/Talks/2016-Compstat-pLVM.pdf}{support de présentation}) \\ [3mm]
2017 &:& Assessing treatment effects on registry data in presence of competing risks \\ 
&& ISCB, Vigo, Espagne \hfill (\href{https://bozenne.github.io/doc/Talks/2017-ISCB-ate.pdf}{support de présentation}) \\ [3mm]
2019 &:& Generalized pairwise comparisons for right-censored time to event outcomes \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhague, Danemark \hfill (\href{https://bozenne.github.io/doc/Talks/2019-prezSAfJR-GPC.pdf}{support de présentation}) \\ [3mm]
2019 &:& Multiple testing in latent variable models \\
&& \href{https://kuleuvencongres.be/iscb40/}{ISCB}, Leuven, Belgique \hfill (\href{https://bozenne.github.io/doc/Talks/2019-ISCB-multcomp_LVM.pdf}{support de présentation}) \\
\end{tabular}
#+END_EXPORT


\clearpage

Invitation à des conférences internationales: 

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2019 &:& Region-Based and Voxel-Wise Analysis of Medical Images Using Latent Variables \\
&& \href{https://events.razzby.com/nbbc19/}{7th NBBC}, Vilnius, Lithuanie \\
2020 (à venir) &:& Robust estimation of the average treatment effects in presence of right-censoring \\
&& and competing risks \\
&& \href{http://www.cmstatistics.org/conferences.php}{CMStatistics}, Londres, Angleterre \\
\end{tabular}
#+END_EXPORT

\bigskip

Responsable de session ("chairman"):

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2019 &:& Mathematical Statistics \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhague, Danemark
\end{tabular}
#+END_EXPORT

* Reference                                                          :ignore:

# bibliographystyle:apalike
 bibliographystyle:plainnat

 # [[bibliography:publicationBO.bib]]
[[nobibliography:publicationBO.bib]]

* CONFIG :noexport:
#+LANGUAGE: fr
#+LaTeX_CLASS: org-article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+OPTIONS:   title:nil author:nil toc:nil todo:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t
#+options: num:nil

#+LaTeX_HEADER: \pagestyle{empty} % no page numbering
#+LATEX_HEADER: \usepackage[french]{babel}

** Notations
#+LaTeX_HEADER: \newcommand{\Rlogo}{\textbf{\textsf{R}}}
#+LaTeX_HEADER: \newcommand{\Cpp}{C\nolinebreak\hspace{-.05em}\raisebox{.4ex}{\tiny\bf +}\nolinebreak\hspace{-.10em}\raisebox{.4ex}{\tiny\bf +}}
#+LaTeX_HEADER: \usepackage{eurosym} % euro symbol

** Sections
#+LaTeX_HEADER: \usepackage{titlesec}
#+LaTeX_HEADER: \titleformat{\section}{\large}{\thesection}{1em}{}

#+LaTeX_HEADER: \titlespacing*{\section}{0pt}{0.25\baselineskip}{0.25\baselineskip}
** Margin
#+LaTeX_HEADER: \geometry{
#+LaTeX_HEADER: left=20mm,
#+LaTeX_HEADER: right=20mm,
#+LaTeX_HEADER: top=20mm,
#+LaTeX_HEADER: bottom=20mm
#+LaTeX_HEADER: }

** Line spacing
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER: \renewcommand{\baselinestretch}{1.1}

** CV
# from https://www.sharelatex.com/templates/cv-or-resume/sc_cv
#+LaTeX_HEADER: \usepackage{framed}
#+LaTeX_HEADER: \usepackage{tocloft}

#+LaTeX_HEADER: \newlength{\outerbordwidth}
#+LaTeX_HEADER: \raggedbottom
#+LaTeX_HEADER: \raggedright

#+LaTeX_HEADER: \setlength{\outerbordwidth}{3pt}  % Width of border outside of title bars
#+LaTeX_HEADER: \definecolor{shadecolor}{gray}{0.75}  % Outer background color of title bars (0 = black, 1 = white)
#+LaTeX_HEADER: \definecolor{shadecolorB}{gray}{0.93}  % Inner background color of title bars

#+LaTeX_HEADER: \usepackage{mdframed}
#+LaTeX_HEADER: \newcommand{\resitem}[1]{\item #1 \vspace{-2pt}}

#+LaTeX_HEADER: \newcommand{\resheading}[1]{
#+LaTeX_HEADER: \vspace{8pt}
#+LaTeX_HEADER:  \parbox{\textwidth}{\setlength{\FrameSep}{\outerbordwidth}
#+LaTeX_HEADER:     \begin{shaded}
#+LaTeX_HEADER: \setlength{\fboxsep}{0pt}\framebox[\textwidth][l]{\setlength{\fboxsep}{4pt}\fcolorbox{shadecolorB}{shadecolorB}{\textbf{\sffamily{\mbox{~}\makebox[6.762in][l]{\large #1} \vphantom{p\^{E}}}}}}
#+LaTeX_HEADER:     \end{shaded}
#+LaTeX_HEADER:   }\vspace{-5pt}
#+LaTeX_HEADER: }
#+LaTeX_HEADER: \newcommand{\ressubheading}[4]{
#+LaTeX_HEADER: \begin{tabular*}{6.5in}{l@{\cftdotfill{\cftsecdotsep}\extracolsep{\fill}}r}
#+LaTeX_HEADER: 		\textbf{#1} & #2 \\
#+LaTeX_HEADER: 		\textit{#3} & \textit{#4} \\
#+LaTeX_HEADER: \end{tabular*}\vspace{-6pt}}

#+LaTeX_HEADER: \usepackage{ragged2e}

** List of publications
# ### list publications
#+LaTeX_HEADER: \usepackage{bibentry}
#+LaTeX_HEADER: \nobibliography*

# ### display of my name
#+LaTeX_HEADER: \newcommand{\myname}[1]{\textbf{#1}}

#+LaTeX_HEADER:  \usepackage{url}

** list
#+LaTeX_HEADER:\usepackage{enumitem}
