#+TITLE:
#+Author: Brice Ozenne

# header
#+BEGIN_EXPORT latex
\begin{tabular*}{7in}{l@{\extracolsep{\fill}}r}
	\textbf{\Large Brice Ozenne} & \textbf{\today} \\
\end{tabular*}

\bigskip

\begin{minipage}{0.2\linewidth}
\includegraphics[width=\linewidth]{photoId.png}
\end{minipage}
\begin{minipage}{0.75\linewidth}
\begin{tabular*}{7in}{ll@{ }l}
	Nationalité&:& française  \\
	Né&:& le 8 février 1990 à Saint Hilaire du Harcouët (50)  \\
	Courriel personnel&:& \url{brice.mh.ozenne@gmail.com} \\ 
	Téléphone personnel&:& (+45) 52 328 128 \\ 
        Adresse personnelle&:& Nordre Teglkaj 18, 5 t.h., 2450 Copenhagen SV, Danemark \\
        Site internet&:& \url{https://bozenne.github.io/} \\
        Github&:& \url{https://github.com/bozenne/} \\
\end{tabular*}
\end{minipage}
#+END_EXPORT


* Poste                                                              :ignore:
#+LaTeX: \resheading{Activité de recherche}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
	Depuis octobre 2020 :& \textbf{Professeur assistant en biostatistiques} avec une position partagée entre \\ [2mm]
      & - une unité de recherche en biostatistiques \\
	& \href{https://biostat.ku.dk/staff_/?pure=en/persons/540231}{Section of Biostatistics}, University of Copenhagen \\
	& \O{}ster Farimagsgade 5, 1014 Copenhague, Danemark \\ [2mm]
	& - une unité de recherche en neuroscience \\
	& \href{https://nru.dk/index.php/staff-list/post-docs/110-brice-ozenne}{Neurobiology Research Unit} \\
	& Copenhagen University Hospital, Rigshospitalet \\
	& Building 6931, Blegdamsvej 9, DK-2100 Copenhagen, Danemark \\ [2mm]
	& où j'exerce conjointement une activité de recherche en biostatistiques, \\ 
      & de consultant en statistiques et une activité pédagogique.
\end{tabular}
#+END_EXPORT

\bigskip

Mon travail de recherche s'articule autour de trois thèmes:
- le développement de *modèles multivariés* pour l'analyse de données
  en neuroscience. Principalement modèles mixed (LMM) et modèles à
  variables latentes (LVM) - voir les publications
  citep:ebert2019molecular,stenbaek2017brain,fisher2017bdnf pour des
  exemples d'application. D'un point de vue méthodologique, je
  m'intéresse à *l'estimation et l'inférence en petits échantillons*
  citep:ozenne2020small ainsi qu'à développer des corrections
  efficaces en présence de *tests multiples*
  citep:ozenne2022controlling. Ces développements sont implémentés dans
  les librairies R =lavaSearch2= (LVM) et =LMMstar= (LMM).

\bigskip

- l'analyse de données de registre en présence de *censure à droite,
  risques compétitifs, et variables de confusion*, en particulier pour
  comparer l'efficacité de traitements préventifs de maladies
  cardiovasculaires (publications
  cite:staerk2018standard,staerk2017resumption,staerk2016ischaemic). En
  utilisant des résultats de la *théorie semi-paramétrique*, j'ai
  développé un estimateur robuste basé sur plusieurs modèles de
  régressions et utilisé sa fonction d'influence pour obtenir sa
  distribution asymptotique citep:ozenne2020estimation. Cette méthode
  est implémentée dans la fonction =ate= de la librairie R
  =riskRegression=. Voir aussi citep:scheike2022efficient pour un
  travail plus théorique sur l'efficacité d'estimateurs issus du
  modèle de Fine and Gray.

\bigskip

- l'extension des *méthodes de comparaison par paires* (GPC) aux
  données censurées citep:peron2016extension. Les GPC permettent
  d'analyser simultanément plusieurs critères de jugements et donc
  d'évaluer la balance bénéfice-risque d'un traitement. Une
  application typique est de proposer une statistique reflétant à la
  fois les gains en survie et les effets secondaires de traitements
  anti-cancéreux (publications citep:peron2016net et
  citep:peron2016assessment). Je m'intéresse par exemple à la théorie
  des U-statistiques pour obtenir la distribution asymptotique de
  certains estimateurs implémentés dans la librairie R =BuyseTest=
  (citep:ozenne2021asymptotic).

\bigskip

** /Autres domaines d'intérêt en statistiques:/
- Spline de lissages et modélisation fonctionnelle
- Inférence causale et régimes de traitement dynamiques
- Essais cliniques séquentiels 
- Inférence statistique après sélection 

* Compétences                                                        :ignore:
#+LaTeX: \resheading{Compétences}
** /Linguistiques/
Français (langue maternelle), anglais (courant), danois (intermédiaire), notions d'italien.

** /Logicielles/
Bonne connaissance de \Rlogo{}, \LaTeX{} et [[https://orgmode.org/][orgmode]]. @@latex:\\@@
Utilisation courante mais basique de \Cpp{}, lisp (pour [[https://www.gnu.org/software/emacs/][GNU Emacs]]),
git/github et inkscape.

* Formation                                                          :ignore: 
#+LaTeX: \resheading{Formation universitaire et parcours de recherche}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2015 - 2020 :& \textbf{Post-doctorat en biostatistiques} avec une position partagée entre: \\
\multicolumn{2}{l}{- \emph{l'Université de Copenhague}: rechercheur et enseignant à l'école doctorale de médicine.}  \\
\multicolumn{2}{l}{- \emph{le CHU de Copenhague (NRU)}: consultant et responsable de l'analyse de données}\\
\multicolumn{2}{l}{ \hphantom{le CHU de Copenhague (NRU): } au sein du projet \href{https://np.nru.dk/}{Neuropharm}.}\\
\end{tabular}
Développement de modèle à variables latents en neuroimagerie (librarie R \texttt{lavaSearch2}) ainsi que d'estimateurs robustes pour l'analyse de données de registre (librarie R \texttt{riskRegression}).
#+END_EXPORT

\bigskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2012 - 2015 : & \textbf{Doctorat en biostatistiques}, Université Lyon 1. \\
\multicolumn{2}{l}{\emph{Directeur/Co-directeur}: Pr. Delphine Maucort-Boulch / Pr. Norbert Nighoghossian} \\ 
\multicolumn{2}{l}{Sujet: \href{https://tel.archives-ouvertes.fr/tel-01233049/document}{modélisation statistique pour le pronostic de patients atteints d’un Accident Vasculaire Cérébral}} \\ 
\multicolumn{2}{l}{\hphantom{Sujet:} Développement d'outils de segmentation d'image et de prédiction appliqués à l'AVC.}\\
\multicolumn{2}{l}{\hphantom{Sujet:} Le produit final étant une prédiction personnalisée de l'extension du volume de l'AVC}\\
\multicolumn{2}{l}{\hphantom{Sujet:} à l'admission du patient à l'hopital.} \\ [3mm]
\end{tabular}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2012 : & \textbf{Stage de master 2}, Hospices Civils de Lyon. \\
\multicolumn{2}{l}{\emph{Encadrant}: Pr. Delphine Maucort-Boulch} \\ 
\multicolumn{2}{l}{Sujet: mise en place d’un critère IRM de reperfusion lors d'un AVC} \\ 
\multicolumn{2}{l}{\hphantom{Sujet:} Le stage a permis de proposer un critère de reperfusion basé sur trois mesures IRM} \\
\multicolumn{2}{l}{\hphantom{Sujet:} du niveau de perfusion et de le valider au regard de critères cliniques.} \\  [3mm]
\end{tabular}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2009 - 2012 : & \textbf{Formation d'ingénieur avec spécialisation en statistiques} à École Centrale de Lyon \\ 
              & \textbf{Erasmus} à l'Université Politecnico di Milano (2nd semestre 2011) \\
              & \textbf{Master en biostatistiques} à l'Université Lyon 1 en double diplôme (\href{http://mastersantepublique.univ-lyon1.fr/webapp/website/website.html?id=3124911&pageId=215838}{M2 B3S}). \\
\end{tabular}
#+END_EXPORT

* Enseignement et encadrement d'étudiants                                 :ignore:
#+LaTeX: \resheading{Enseignement et encadrement d'étudiants}
Enseignement (CM : cours magistral, TD : travaux dirigés):

\medskip

Doctorants en santé:

#+BEGIN_EXPORT latex
\begin{tabular}{r@{ }l}
2021 - 2022 : & \href{http://publicifsv.sund.ku.dk/~jufo/RepeatedMeasures2019.html}{Analyse statistique de données répétées}. CM et TD (6h et 18h). \\
            : & Outils statistiques pour l'épidémiologie. Responsable CM, TD (10h et 18h). \\
            : & Introduction aux statistiques. CM, TD (3h et 3h). \\
2015 - 2020 : & \href{http://publicifsv.sund.ku.dk/~jufo/RepeatedMeasures2019.html}{Analyse statistique de données répétées}. TD (18h). \\
\end{tabular}
#+END_EXPORT

\bigskip

Etudiants de master de statistiques:

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2016 - 2017 : & Modèles d'équations structurelles. CM (2h). \\
\end{tabular}
#+END_EXPORT

\bigskip

Etudiants de master en santé publique:

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2014 - 2015 : & \href{https://clarolineconnect.univ-lyon1.fr/resource/open/file/2733301}{Modèles de Survie}. TD (18h).\\
2013 - 2015 : & \href{https://clarolineconnect.univ-lyon1.fr/resource/open/file/2733304}{Statistique bayésienne}. TD (6h).\\
\end{tabular}
#+END_EXPORT


\bigskip

Exposés pédagogiques pour chercheurs en neuroscience sur des
outils/problématiques statistiques:
- [[https://bozenne.github.io/doc/Talks/2017-XNRU-power.pdf][Do we need more power?]] ([[https://www.nru.dk/images/News/NeurobiologyResearchUnit-Christmas-symposium2017.pdf][NRU Christmas Symposium 2017]]).
- [[https://bozenne.github.io/doc/Talks/2018-XNRU-DAGs.pdf][To adjust or not adjust, that is the question]] (NRU Christmas Symposium 2018).
- [[https://bozenne.github.io/doc/Talks/2019-XNRU-multcomp.pdf][A refresher on multiple comparisons]]? ([[https://nru.dk/index.php/news-menu/279-nru-christimas-symposium-2019][NRU Christmas Symposium 2019]]).

\bigskip

Co-encadrant d'étudiant en *master 2*: 

\medskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Ceren Tozlu \\
\multicolumn{3}{l}{Comparaison de méthodes de classification pour la prédiction du devenir des tissus lors} \\ 
\multicolumn{3}{l}{d'un AVC \citep{tozlu2019comparison}.} \\ [3mm]
2019 &:& Alice Brouquet-Laglaire \\
\multicolumn{3}{l}{Comparaison de méthodes d’inférence dans le cadre des comparaisons par paires généralisées.} \\ [3mm]
\end{tabular}
#+END_EXPORT

* Financement                                                        :ignore:
#+LaTeX: \resheading{Financement}
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l}
2017-2019: MARIE CURIE Individual Fellowships (200 000\euro) \\
2017-2020: Lundbeck Fellowships (140 000\euro) \\

\end{tabular}
#+END_EXPORT

\clearpage

* Production scientifique                                            :ignore:
#+LaTeX: \resheading{Production scientifique}
** /Publications (méthodologiques)/

#+BEGIN_EXPORT latex
 \begin{enumerate}
    \item \bibentry{scheike2022efficient}
    \item \bibentry{ozenne2022controlling}
    \item \bibentry{ozenne2021asymptotic}
    \item \bibentry{peron2021correcting}
    \item \bibentry{cantagallo2021new}
    \item \bibentry{ozenne2020small}
    \item \bibentry{verbeeck2020evaluation}
    \item \bibentry{ozenne2020estimation}
    \item \bibentry{norgaard2019preprocessing}
    \item \bibentry{ozenne2017riskregression}
    \item \bibentry{peron2016extension}
    \item \bibentry{ozenne2015precision}
    \item \bibentry{ozenne2015spatially}
  \end{enumerate}
#+END_EXPORT

** /Développement logiciel (librairies pour le logiciel [[https://www.r-project.org/][R]])/
#+LaTeX: \begin{minipage}{0.01\textwidth}
#+LaTeX: \hspace{\fill}
#+LaTeX: \end{minipage}
#+LaTeX: \begin{minipage}{0.92\textwidth}
- *BuyseTest* (Créateur et mainteneur) : Comparisons par paires
  généralisées. Implémentation de la méthode décrite dans
  citep:peron2016extension,peron2021correcting. Disponible sur le [[https://cran.r-project.org/web/packages/BuyseTest/index.html][CRAN]]
  et sur [[https://github.com/bozenne/BuyseTest][Github]].

- *lavaSearch2* (Créateur et mainteneur) : Inférence et outils
  diagnostiques dans les modèles à variables latentes
  (cite:ozenne2020small,ozenne2022controling). Disponible sur
  le [[https://cran.r-project.org/web/packages/lavaSearch2/index.html][CRAN]] et sur [[https://github.com/bozenne/lavaSearch2][Github]]. .

- *LMMstar* (Créateur et mainteneur) : Modèles mixtes linéaires:
  formulation marginale avec differentes structures de
  variance-covariance residuelle et outils d'inférence statistique
  associés'. Disponible sur le [[https://cran.r-project.org/web/packages/LMMstar/index.html][CRAN]] et sur [[https://github.com/bozenne/LMMstar][Github]]. .

- *riskRegression* (Contributeur) : Calculateur du risque
  d'évènenement en présence de risques compétitifs. Implémentation de
  la méthode décrite dans cite:ozenne2017riskregression et
  cite:ozenne2020estimation. Disponible sur le [[https://cran.r-project.org/web/packages/riskRegression/index.html][CRAN]] et sur [[https://github.com/tagteam/riskRegression][Github]].
#+LaTeX: \end{minipage}

\bigskip

Librairie pour le logiciel [[https://www.gnu.org/software/emacs/][emacs]]:
- *emacs-config* (Créateur et mainteneur) : configuration facilitant
  l'intéraction avec R/C++/orgmode/latex/git. Disponible sur sur
  [[https://github.com/bozenne/emacs-config][Github]].

\pagebreak[3]

** /Publications (applications cliniques)/

#+BEGIN_EXPORT latex
 \begin{enumerate}[resume]
    \item \bibentry{nasser2022reliability}
    \item \bibentry{armand2022brain}
    \item \bibentry{kohler2022concurrent}
    \item \bibentry{armand2022acute}
    \item \bibentry{armand2022brain}
    \item \bibentry{fisher2022emotional}
    \item \bibentry{beaman2022blood}
    \item \bibentry{drummond2022psilocybin}
    \item \bibentry{larsen2022impact}
    \item \bibentry{mcculloch2022lasting}
    \item \bibentry{ip2021eeg}
    \item \bibentry{madsen2021psilocybin}
    \item \bibentry{joergensen2021default}
    \item \bibentry{brandt2021reward}
    \item \bibentry{dea2021brain}
    \item \bibentry{ip2021pretreatement}
    \item \bibentry{hoghe2021MAMA}
    \item \bibentry{raval2021single}
    \item \bibentry{hogsted2021stress}
    \item \bibentry{donovan2021effects}
    \item \bibentry{lee2020absolute}
    \item \bibentry{hansen2020visual}
    \item \bibentry{spies2020common}
    \item \bibentry{larsen2020oral}
    \item \bibentry{thystrup2020severity}
    \item \bibentry{dam2020hot}x
    \item \bibentry{hjordt2020psychometric}
    \item \bibentry{beliveau2020structure}
    \item \bibentry{madsen2020single}
    \item \bibentry{ozenne2019individualized}
    \item \bibentry{ebert2019molecular}
    \item \bibentry{madsen2019psychedelic}
    \item \bibentry{tozlu2019comparison}
    \item \bibentry{ip2018pre}
    \item \bibentry{borgsted2018amygdala}
    \item \bibentry{hjordt2018self}
    \item \bibentry{foged2018verbal}
    \item \bibentry{staerk2018standard}
    \item \bibentry{hjordt2017season}
    \item \bibentry{beliveau2017high}
    \item \bibentry{stenbaek2017brain}
    \item \bibentry{staerk2017resumption}
    \item \bibentry{fisher2017bdnf}
    \item \bibentry{foged2017safety}
    \item \bibentry{peron2016net}
    \item \bibentry{staerk2016ischaemic}
    \item \bibentry{peron2016assessment}
    \item \bibentry{ozenne2015evaluation}
    \item \bibentry{hermitte2013very}
  \end{enumerate}
#+END_EXPORT

\pagebreak[3]


* Relecture d'articles                                               :ignore:
#+LaTeX: \resheading{Relecture d'article}
J'ai relu des articles pour Biometrics, Statistics in Medicine,
International Journal of Biostatistics, and BMC medical reasearch
methodology. Voir mon [[https://publons.com/researcher/1214277/brice-maxime-hugues-ozenne/][profile publons]] pour plus d'informations.


\clearpage

* Communications orales                                             :ignore:
#+LaTeX: \resheading{Conférences}
Présentations orales lors de conférences internationales: 
\smallskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2014 &:& Image segmentation using a spatially regularized mixture model \\
&& \href{https://www.biometricsociety.org/meetings-events/ibcs/}{IBC}, Florence, Italie \\
2015 &:& \href{https://r2015-grenoble.sciencesconf.org/66037}{MRIaggr : un package pour la gestion et le traitement de données multivariées d'imagerie} \\
&& Rencontres R, Grenoble, France \\
2016 &:& \href{http://cmstatistics.org/RegistrationsV2/COMPSTAT2016/viewSubmission.php?in=440&token=29584n1s18p97n65o7p1r5n36sopq0n4}{Penalized latent variable models} \\
&& Computational statistics, Oviedo, Espagne \\
2017 &:& Assessing treatment effects on registry data in presence of competing risks \\ 
&& \href{http://www.iscb2017.info/}{ISCB}, Vigo, Espagne \\
2019 &:& Generalized pairwise comparisons for right-censored time to event outcomes \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhague, Danemark \\
2020 &:& Robust estimation of the average treatment effects in presence of right-censoring \\
&& and competing risks \\
&& \href{http://www.cmstatistics.org/conferences.php}{CMStatistics}, Londres, Angleterre \\
\end{tabular}
#+END_EXPORT

\bigskip

Responsable de session ("chairman"):

\smallskip

#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2019 &:& Mathematical Statistics \\
&& \href{https://publicifsv.sund.ku.dk/~safjr2019/}{Survival analysis for junior researcher}, Copenhague, Danemark
\end{tabular}
#+END_EXPORT

\bigskip

Organisation d'une formation ("Workshop"):
#+BEGIN_EXPORT latex
\begin{tabular}{l@{ }l@{ }l}
2021 &:& Analysis of repeated measurements with mixed models using the R package LMMstar (1h+3h) \\
&& Methods Week, Karolinska institute, Stockholm, Sweden
\end{tabular}
#+END_EXPORT

\smallskip


* Reference                                                          :ignore:

# bibliographystyle:apalike
 bibliographystyle:plainnat

 # [[bibliography:publicationBO.bib]]
[[nobibliography:publicationBO.bib]]

* CONFIG :noexport:
#+LANGUAGE: fr
#+LaTeX_CLASS: org-article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+OPTIONS:   title:nil author:nil toc:nil todo:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t
#+options: num:nil

#+LaTeX_HEADER: \pagestyle{empty} % no page numbering
#+LATEX_HEADER: \usepackage[french]{babel}

** Notations
#+LaTeX_HEADER: \newcommand{\Rlogo}{\textbf{\textsf{R}}}
#+LaTeX_HEADER: \newcommand{\Cpp}{C\nolinebreak\hspace{-.05em}\raisebox{.4ex}{\tiny\bf +}\nolinebreak\hspace{-.10em}\raisebox{.4ex}{\tiny\bf +}}
#+LaTeX_HEADER: \usepackage{eurosym} % euro symbol

** Sections
#+LaTeX_HEADER: \usepackage{titlesec}
#+LaTeX_HEADER: \titleformat{\section}{\large}{\thesection}{1em}{}

#+LaTeX_HEADER: \titlespacing*{\section}{0pt}{0.25\baselineskip}{0.25\baselineskip}
** Margin
#+LaTeX_HEADER: \geometry{
#+LaTeX_HEADER: left=20mm,
#+LaTeX_HEADER: right=20mm,
#+LaTeX_HEADER: top=20mm,
#+LaTeX_HEADER: bottom=20mm
#+LaTeX_HEADER: }

** Color
# # change the color of the links
#+LaTeX_HEADER: \hypersetup{
#+LaTeX_HEADER:  citecolor=[rgb]{0,0.5,0},
#+LaTeX_HEADER:  urlcolor=[rgb]{0,0,0.5},
#+LaTeX_HEADER:  linkcolor=[rgb]{0,0,0.5},
#+LaTeX_HEADER: }

** Line spacing
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER: \renewcommand{\baselinestretch}{1.1}

** CV
# from https://www.sharelatex.com/templates/cv-or-resume/sc_cv
#+LaTeX_HEADER: \usepackage{framed}
#+LaTeX_HEADER: \usepackage{tocloft}

#+LaTeX_HEADER: \newlength{\outerbordwidth}
#+LaTeX_HEADER: \raggedbottom
#+LaTeX_HEADER: \raggedright

#+LaTeX_HEADER: \setlength{\outerbordwidth}{3pt}  % Width of border outside of title bars
#+LaTeX_HEADER: \definecolor{shadecolor}{gray}{0.75}  % Outer background color of title bars (0 = black, 1 = white)
#+LaTeX_HEADER: \definecolor{shadecolorB}{gray}{0.93}  % Inner background color of title bars

#+LaTeX_HEADER: \usepackage{mdframed}
#+LaTeX_HEADER: \newcommand{\resitem}[1]{\item #1 \vspace{-2pt}}

#+LaTeX_HEADER: \newcommand{\resheading}[1]{
#+LaTeX_HEADER: \vspace{8pt}
#+LaTeX_HEADER:  \parbox{\textwidth}{\setlength{\FrameSep}{\outerbordwidth}
#+LaTeX_HEADER:     \begin{shaded}
#+LaTeX_HEADER: \setlength{\fboxsep}{0pt}\framebox[\textwidth][l]{\setlength{\fboxsep}{4pt}\fcolorbox{shadecolorB}{shadecolorB}{\textbf{\sffamily{\mbox{~}\makebox[6.762in][l]{\large #1} \vphantom{p\^{E}}}}}}
#+LaTeX_HEADER:     \end{shaded}
#+LaTeX_HEADER:   }\vspace{-5pt}
#+LaTeX_HEADER: }
#+LaTeX_HEADER: \newcommand{\ressubheading}[4]{
#+LaTeX_HEADER: \begin{tabular*}{6.5in}{l@{\cftdotfill{\cftsecdotsep}\extracolsep{\fill}}r}
#+LaTeX_HEADER: 		\textbf{#1} & #2 \\
#+LaTeX_HEADER: 		\textit{#3} & \textit{#4} \\
#+LaTeX_HEADER: \end{tabular*}\vspace{-6pt}}

** List of publications
# ### list publications
#+LaTeX_HEADER: \usepackage{bibentry}
#+LaTeX_HEADER: \nobibliography*

# ### display of my name
#+LaTeX_HEADER: \newcommand{\myname}[1]{\textbf{#1}}

#+LaTeX_HEADER:  \usepackage{url}

# ## [resume] (keep the numbering over several enumerate list)
#+LaTeX_HEADER: \usepackage{enumitem}
