#+TITLE: A simple example of multiple imputation using the mice package
#+Author: Brice Ozenne


This document gathers code from the documentation of the mice
package. See https://stefvanbuuren.name/mice/.

\bigskip

#+BEGIN_SRC R :exports none :results output :session *R* :cache no
path <- "~/Github/bozenne.github.io/doc/2019-10-22-multipleImputation/"
setwd(path)
#+END_SRC

#+RESULTS:

Load packages
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
library(lava)
library(mice)
library(data.table)
library(ggplot2)
#+END_SRC

#+RESULTS:

* Simulate data

Just to have an example to work with. Generative model:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
mSim <- lvm(Y~group+season+bmi+gender+age)
categorical(mSim, labels = c("winter","summer")) <- ~season
categorical(mSim, labels = c("SAD","HC")) <- ~group
categorical(mSim, labels = c("Male","Female")) <- ~gender
distribution(mSim,~bmi) <- lava::gaussian.lvm(mean = 22, sd = 3)
distribution(mSim,~age) <- lava::uniform.lvm(20,80)
#+END_SRC

#+RESULTS:

Sampling
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
n <- 1e2
set.seed(10)
dt.data <- as.data.table(sim(mSim,n))
#+END_SRC

#+RESULTS:
Add missing values
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
dt.data[1:10, "age":=NA]
dt.data[11:20, c("age","bmi","Y"):=NA]
#+END_SRC

#+RESULTS:

\clearpage

* Working with mice

** Step 1: Inspect the missing data pattern
Check the number of missing values in the dataset:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
colSums(is.na(dt.data))
#+END_SRC

#+RESULTS:
:      Y  group season    bmi gender    age 
:     10      0      0     10      0     20

Missing data patterns:   
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
md.data <- md.pattern(dt.data)
md.data
#+END_SRC

#+RESULTS:
:    group season gender  Y bmi age   
: 80     1      1      1  1   1   1  0
: 10     1      1      1  1   1   0  1
: 10     1      1      1  0   0   0  3
:        0      0      0 10  10  20 40

#+BEGIN_SRC R :exports none :results output :session *R* :cache no
pdf("./figures/missingDataPattern.pdf")
md.pattern(dt.data)
dev.off()
#+END_SRC

#+RESULTS:
:    group season gender  Y bmi age   
: 80     1      1      1  1   1   1  0
: 10     1      1      1  1   1   0  1
: 10     1      1      1  0   0   0  3
:        0      0      0 10  10  20 40
: windows 
:       2

- the left column counts the number of observations having a specific
  missing data pattern.
- the right column display the number of missing data in each pattern
- the bottom row counts the number of missing value relative to each
  variable (and the total number of missing values).

#+name: fig:md
#+ATTR_LaTeX: :width 0.8\textwidth :options trim={40 120 40 120},clip :placement [!h]
[[./figures/missingDataPattern.pdf]]

\clearpage

** Step 2: Reflect upon the missing data and correlation patterns

It is often useful to consider the missing data patterns next to the
association between variables. Ideally the association pattern should
be based on prior knowledge as the empirical one (i.e. based on the
observed data) may be difficult to estimate reliably in presence of
missing data. To keep things concrete, let's use a rough approximation
(pearson correlation also for categorical variables) of the
correlation structure:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
dtNum.data <- as.data.frame(lapply(dt.data,as.numeric))
cor.data <- cor(dtNum.data, use = "pairwise")
cor.data[setdiff(colnames(md.data),""),
         setdiff(colnames(md.data),"")]
#+END_SRC

#+RESULTS:
:              group      season      gender           Y         bmi         age
: group   1.00000000 -0.08242959 -0.04222003  0.11147368 -0.09679738  0.09304925
: season -0.08242959  1.00000000 -0.09090909  0.09219243  0.06508765  0.07620663
: gender -0.04222003 -0.09090909  1.00000000 -0.12831302  0.04329831 -0.17662044
: Y       0.11147368  0.09219243 -0.12831302  1.00000000  0.32446590  0.98452932
: bmi    -0.09679738  0.06508765  0.04329831  0.32446590  1.00000000  0.16195300
: age     0.09304925  0.07620663 -0.17662044  0.98452932  0.16195300  1.00000000

*Intuition*: A complete case analysis where =Y= is regressed against
=group=, adjusting for =season=, =gender=, =bmi=, =age= would discard
information from all the 20 subjects with missing values.
- Complete case would discard valuable information for the 10 subjects
  where =Y= is known but =age=. Indeed, =age= being very correlated
  with =Y=, those subjects are not really missing data. Multiple
  imputation can avoid discarding such valuable information, leading
  to superior statistical power and possibly less bias.
- the 10 subjects missing =bmi=, =age=, and =Y= carry little
  information as =group=, =season=, and =gender= do not seem to be
  particularly useful to guess the missing values. In that case
  multiple imputation would essentially impute the group mean for
  =bmi=, =age=, and =Y= leading to similar results as complete case
  analysis.

\clearpage

*Multiple imputation (MI) vs. complete case (CC)* citep:vanbuuren2018:
  "Suppose that the complete-data model is a regression with outcome
  \(Y\) and predictors \(X\). If the missing data occur in \(Y\) only,
  complete-case analysis and multiple imputation are equivalent [...]
  Multiple imputation gains an advantage over complete-case analysis
  if additional predictors for \(Y\) are available that are not part
  of \(X\). The efficiency of complete-case analysis declines if \(X\)
  contains missing values. [...] there are two special cases where
  listwise deletation outperforms multiple imputation [...]
  - the probability to be missing does not depend on Y
  - the complete data model is logistic regression [...] the
    probability to be missing depends only on Y and not on X"
    
\bigskip
\bigskip
\bigskip

** Step 3: Define imputation model

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
all.variables <- setdiff(colnames(md.data),"")
n.variables <- length(all.variables)
Mlink <- matrix(0, n.variables, n.variables,
                dimnames = list(all.variables,all.variables))
Mlink["Y", which(colnames(Mlink)!="Y")] <- 1
Mlink["age", which(colnames(Mlink)!="age")] <- 1
Mlink["bmi", which(colnames(Mlink)!="bmi")] <- 1
Mlink
#+END_SRC

#+RESULTS:
:        group season gender Y bmi age
: group      0      0      0 0   0   0
: season     0      0      0 0   0   0
: gender     0      0      0 0   0   0
: Y          1      1      1 0   1   1
: bmi        1      1      1 1   0   1
: age        1      1      1 1   1   0

A value of 1 means that the column variable is used as a predictor for
 the target block (in the rows).

\clearpage

** Step 4: Generate imputed datasets
Generate imputed values
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
n.imputed <- 3 ## number of imputed datasets
dt.mice <- mice(dt.data,
                m=n.imputed, 
                maxit = 100, # number of iterations to obtain the imputed dataset
                predictorMatrix = Mlink,
                method = 'pmm', # Predictive mean matching, only ok for continuous variables, it is possible to set constrains for positive variables
                seed = 500, printFlag = FALSE)
summary(dt.mice)
#+END_SRC

#+RESULTS:
#+begin_example
Class: mids
Number of multiple imputations:  3 
Imputation methods:
 group season gender      Y    bmi    age 
    ""     ""     ""  "pmm"  "pmm"  "pmm" 
PredictorMatrix:
       group season gender Y bmi age
group      0      0      0 0   0   0
season     0      0      0 0   0   0
gender     0      0      0 0   0   0
Y          1      1      1 0   1   1
bmi        1      1      1 1   0   1
age        1      1      1 1   1   0
#+end_example

*** Interacting with the mice object

Missingness indicator:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
table(cci(dt.mice))
#+END_SRC

#+RESULTS:
: 
: FALSE  TRUE 
:    20    80

\clearpage

Complete case dataset:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
str(cc(dt.mice))
#+END_SRC

#+RESULTS:
: 'data.frame':	80 obs. of  6 variables:
:  $ Y     : num  48.7 91.6 75.3 51.8 92 ...
:  $ group : Factor w/ 2 levels "SAD","HC": 1 2 1 1 2 1 2 1 1 1 ...
:  $ season: Factor w/ 2 levels "winter","summer": 1 1 2 1 1 2 2 2 2 2 ...
:  $ bmi   : num  23.4 25.7 20.2 24.3 23.8 ...
:  $ gender: Factor w/ 2 levels "Male","Female": 2 2 2 1 1 2 1 1 2 2 ...
:  $ age   : num  24.8 66.1 53.7 29.7 68.4 ...

Extract observations with missing values:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
str(ic(dt.mice))
#+END_SRC

#+RESULTS:
: 'data.frame':	20 obs. of  6 variables:
:  $ Y     : num  92.2 91 63.1 76.2 75.2 ...
:  $ group : Factor w/ 2 levels "SAD","HC": 1 2 1 2 1 2 2 1 2 2 ...
:  $ season: Factor w/ 2 levels "winter","summer": 2 2 2 2 1 2 2 1 1 1 ...
:  $ bmi   : num  21.8 25.5 28.6 23.2 19.8 ...
:  $ gender: Factor w/ 2 levels "Male","Female": 2 2 1 2 2 2 1 2 1 1 ...
:  $ age   : num  NA NA NA NA NA NA NA NA NA NA ...

Dataset after multiple imputation:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
str(complete(dt.mice, action = 1)) ## first imputed dataset
#+END_SRC

#+RESULTS:
: 'data.frame':	100 obs. of  6 variables:
:  $ Y     : num  92.2 91 63.1 76.2 75.2 ...
:  $ group : Factor w/ 2 levels "SAD","HC": 1 2 1 2 1 2 2 1 2 2 ...
:  $ season: Factor w/ 2 levels "winter","summer": 2 2 2 2 1 2 2 1 1 1 ...
:  $ bmi   : num  21.8 25.5 28.6 23.2 19.8 ...
:  $ gender: Factor w/ 2 levels "Male","Female": 2 2 1 2 2 2 1 2 1 1 ...
:  $ age   : num  72.2 61.6 36.7 51.7 56.3 ...

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
str(complete(dt.mice, action = 2)) ## second imputed dataset
#+END_SRC

#+RESULTS:
: 'data.frame':	100 obs. of  6 variables:
:  $ Y     : num  92.2 91 63.1 76.2 75.2 ...
:  $ group : Factor w/ 2 levels "SAD","HC": 1 2 1 2 1 2 2 1 2 2 ...
:  $ season: Factor w/ 2 levels "winter","summer": 2 2 2 2 1 2 2 1 1 1 ...
:  $ bmi   : num  21.8 25.5 28.6 23.2 19.8 ...
:  $ gender: Factor w/ 2 levels "Male","Female": 2 2 1 2 2 2 1 2 1 1 ...
:  $ age   : num  68.4 64.1 30.4 48.9 53.7 ...

\clearpage

** Step 5: Check the imputed datasets
*** Build-in plot to visualize missing values

Dotplot of the orignal data (blue) vs. imputed data (pink) to check
that the imputed values are plausible (e.g. no negative age):
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
stripplot(dt.mice, age~.imp, pch=20, cex=2)
#+END_SRC

#+RESULTS:

#+BEGIN_SRC R :exports none :results output :session *R* :cache no
pdf("./figures/striplotImputed.pdf")
stripplot(dt.mice, age~.imp, pch=20, cex=2)
dev.off()
#+END_SRC

#+RESULTS:
: windows 
:       2

#+RESULTS:
[[file:./figures/striplotImputed.pdf]]

- Points above x=1 represent the original data
- Points above x=2 represent the first imputed dataset
- Points above x=3 represent the second imputed dataset
- ...

\clearpage


Boxplot of the orignal data (blue) vs. imputed data (pink) for a more
compact visualization:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
stripplot(dt.mice, age~.imp, pch=20, cex=2)
#+END_SRC


#+BEGIN_SRC R :exports none :results output :session *R* :cache no
pdf("./figures/bwplotImputed.pdf")
bwplot(dt.mice)
dev.off()
#+END_SRC

#+RESULTS:
: windows 
:       2

#+RESULTS:

#+ATTR_LaTeX: :width 0.8\textwidth :options trim={0 10 0 0},clip :placement [!h]
[[file:./figures/bwplotImputed.pdf]]

Density plot of the orignal data (blue) vs. imputed data (pink) to
compare more in detail the distributions:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
densityplot(dt.mice, layout = c(3,1))
#+END_SRC

#+BEGIN_SRC R :exports none :results output :session *R* :cache no
pdf("./figures/densityplotImputed.pdf", width = 10, height = 4)
densityplot(dt.mice, layout = c(3,1))
dev.off()
#+END_SRC

#+RESULTS:
: windows 
:       2

#+RESULTS:
[[file:./figures/densityplotImputed.pdf]]


*** Convergence of the imputation algorithm

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
plot(dt.mice, layout = c(1,2))
#+END_SRC   

#+RESULTS:

#+BEGIN_SRC R :exports none :results output :session *R* :cache no
pdf("./figures/traceCVimputed.pdf")
plot(dt.mice, layout = c(1,2))
dev.off()
#+END_SRC

#+RESULTS:
: windows 
:       2

#+ATTR_LaTeX: :width 0.70\textwidth :placement [!h]
[[file:./figures/traceCVimputed.pdf]]

Should look more like the bottom plot than the top plot where the
chains are not mixing very well. Note that here at least 50 iteration
are needed to reach a steady state.

*** Make your own plot

Imputed values can be directly extracted from the object:

\medskip

#+LaTeX: \begin{minipage}{0.5\linewidth} 
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
head(dt.mice$imp$age)
#+END_SRC

#+RESULTS:
:          1        2        3
: 1 67.14724 20.49185 51.74262
: 2 33.40963 24.89930 51.74262
: 3 31.30446 43.02380 48.88883
: 4 31.30446 22.29032 48.88883
: 5 35.79714 31.66111 69.79847
: 6 31.30446 31.66111 69.79847

#+LaTeX: \end{minipage}
#+LaTeX: \begin{minipage}{0.45\linewidth} 
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
tail(dt.mice$imp$age)
#+END_SRC

#+RESULTS:
:           1        2        3
: 15 31.30446 22.29032 69.79847
: 16 35.79714 22.29032 24.91940
: 17 35.79714 24.89930 48.88883
: 18 33.40963 22.29032 24.91940
: 19 31.30446 43.02380 48.88883
: 20 31.30446 22.29032 48.88883
#+LaTeX: \end{minipage}


The columns correspond to the 3 different imputed datasets and the
rows to 20 imputed values per dataset.

\clearpage

The imputed datasets can be extracted using:

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
dfMICE.data <- complete(dt.mice, action = "long")
str(dfMICE.data)
#+END_SRC

#+RESULTS:
: 'data.frame':	300 obs. of  8 variables:
:  $ Y     : num  92.2 91 63.1 76.2 75.2 ...
:  $ group : Factor w/ 2 levels "SAD","HC": 1 2 1 2 1 2 2 1 2 2 ...
:  $ season: Factor w/ 2 levels "winter","summer": 2 2 2 2 1 2 2 1 1 1 ...
:  $ bmi   : num  21.8 25.5 28.6 23.2 19.8 ...
:  $ gender: Factor w/ 2 levels "Male","Female": 2 2 1 2 2 2 1 2 1 1 ...
:  $ age   : num  72.2 61.6 36.7 51.7 56.3 ...
:  $ .imp  : int  1 1 1 1 1 1 1 1 1 1 ...
:  $ .id   : int  1 2 3 4 5 6 7 8 9 10 ...


One can them display the observed and imputed values, possibly with an
interval to reflect the sampling variation of the imputed value (here 1st and 3rd quantiles)
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
library(LMMstar)
dfMICE.mean <- summarize(Y ~ .id + group, data = dfMICE.data)
dfMICE.mean$impute <- dfMICE.mean$sd>0
dfMICE.mean$group.num <- as.numeric(dfMICE.mean$group)
dfMICE.mean$Nimpute <- unlist(tapply(dfMICE.mean$impute,dfMICE.mean$group,cumsum))*(dfMICE.mean$impute)

ggMICE.point <- ggplot(dfMICE.mean,
                       aes(x = group.num+0.1*Nimpute, y = mean))
ggMICE.point <- ggMICE.point + geom_point(aes(color = impute,
                                              shape = impute))
ggMICE.point <- ggMICE.point + geom_segment(data = dfMICE.mean[dfMICE.mean$impute,],
                                            aes(color = impute, y = q1, yend = q3))
ggMICE.point <- ggMICE.point + scale_x_continuous(
                                 breaks = 1:2,
                                 labels = levels(dfMICE.mean$group)
                               )
ggMICE.point <- ggMICE.point + labs(x = "group", y = "Y",
                                    color = "Imputed value",
                                    shape = "Imputed value")
ggMICE.point
#+END_SRC

#+RESULTS:

#+BEGIN_SRC R :exports none :results output :session *R* :cache no
pdf("./figures/manualDotImputed.pdf")
ggMICE.point
dev.off()
#+END_SRC

#+RESULTS:
: windows 
:       2

#+ATTR_LaTeX: :width 1\textwidth :options trim={0 0 0 0},clip :placement [!h]
[[./figures/manualDotImputed.pdf]]


\clearpage

** Step 6: Fit the statical model on each imputed dataset

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
e.mice <- with(data = dt.mice,
               lm(Y~group+season+bmi+gender+age)
               )
e.mice
#+END_SRC

#+RESULTS:
#+begin_example
call :
with.mids(data = dt.mice, expr = lm(Y ~ group + season + bmi + 
    gender + age))

call1 :
mice(data = dt.data, m = n.imputed, method = "pmm", predictorMatrix = Mlink, 
    maxit = 100, printFlag = FALSE, seed = 500)

nmis :
[1] 10  0  0 10  0 20

analyses :
[[1]]

Call:
lm(formula = Y ~ group + season + bmi + gender + age)

Coefficients:
 (Intercept)       groupHC  seasonsummer           bmi  genderFemale           age  
    -0.02614       0.95181       1.13110       0.99033       0.70594       1.00116  


[[2]]

Call:
lm(formula = Y ~ group + season + bmi + gender + age)

Coefficients:
 (Intercept)       groupHC  seasonsummer           bmi  genderFemale           age  
     0.05021       0.59320       0.87012       1.01371       0.59669       1.00034  


[[3]]

Call:
lm(formula = Y ~ group + season + bmi + gender + age)

Coefficients:
 (Intercept)       groupHC  seasonsummer           bmi  genderFemale           age  
      0.5906        0.7486        1.0359        0.9588        1.0171        1.0077
#+end_example

We can check that using =with= is equivalent to run the linear
regression on the imputed dataset:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
dt.tempo <- copy(dt.data)
dt.tempo[is.na(bmi), bmi := dt.mice$imp$bmi[,1]]
dt.tempo[is.na(age), age := dt.mice$imp$age[,1]]
dt.tempo[is.na(Y), Y := dt.mice$imp$Y[,1]]
lm(Y ~ group + season + bmi + gender + age, data  = dt.tempo)
#+END_SRC

#+RESULTS:
: 
: Call:
: lm(formula = Y ~ group + season + bmi + gender + age, data = dt.tempo)
: 
: Coefficients:
:  (Intercept)       groupHC  seasonsummer           bmi  genderFemale           age  
:     -0.02614       0.95181       1.13110       0.99033       0.70594       1.00116

\clearpage

** Step 7: Pool the results over the imputed datasets

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
ePool.mice <- pool(e.mice)
summary(ePool.mice)
#+END_SRC

#+RESULTS:
:           term  estimate   std.error   statistic        df      p.value
: 1  (Intercept) 0.2048883 0.970756912   0.2110604 38.881759 8.339425e-01
: 2      groupHC 0.7645464 0.319142478   2.3956273  9.220665 3.956182e-02
: 3 seasonsummer 1.0123677 0.286505516   3.5335015 18.085773 2.359316e-03
: 4          bmi 0.9876296 0.049550963  19.9315925  9.684670 3.472961e-09
: 5 genderFemale 0.7732397 0.353001211   2.1904733  6.590121 6.701387e-02
: 6          age 1.0030637 0.008348779 120.1449616 15.554399 1.645574e-24


The (pooled) estimate is the average of the estimates relative to each
imputed dataset:
#+BEGIN_SRC R :exports both :results output :session *R* :cache n
Q.coef <- colMeans(do.call(rbind,lapply(e.mice$analyses, coef)))
Q.coef
#+END_SRC

#+RESULTS:
:  (Intercept)      groupHC seasonsummer          bmi genderFemale          age 
:    0.2048883    0.7645464    1.0123677    0.9876296    0.7732397    1.0030637

The variance is a bit more complex and involves:
- the within-imputation variance (depends on the sample size)
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
covW <- Reduce("+",lapply(e.mice$analyses, vcov))/n.imputed
print(covW, digits = 5)
#+END_SRC

#+RESULTS:
:              (Intercept)     groupHC seasonsummer         bmi genderFemale         age
: (Intercept)    0.7916558 -0.04307788  -0.02717933 -0.02939118  -0.03847724 -0.00154551
: groupHC       -0.0430779  0.05873233   0.00490851  0.00083376   0.00140149 -0.00017523
: seasonsummer  -0.0271793  0.00490851   0.05882881 -0.00042661   0.00549819 -0.00002796
: bmi           -0.0293912  0.00083376  -0.00042661  0.00144421  -0.00074300 -0.00004101
: genderFemale  -0.0384772  0.00140149   0.00549819 -0.00074300   0.06116567  0.00035449
: age           -0.0015455 -0.00017523  -0.00002796 -0.00004101   0.00035449  0.00004799

- the between-imputation variance (depends on the amount of missing data)
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
ls.diffCoef <- lapply(e.mice$analyses, function(iI){coef(iI)-Q.coef})
covB <- Reduce("+",lapply(ls.diffCoef,tcrossprod))/(n.imputed-1)
print(covB, digits = 5)
#+END_SRC

#+RESULTS:
:            [,1]        [,2]        [,3]        [,4]        [,5]        [,6]
: [1,]  0.1130349 -1.1447e-02  0.00182317 -0.00788221  0.06845745  1.3253e-03
: [2,] -0.0114468  3.2340e-02  0.02311661 -0.00175256  0.00688497  1.8197e-05
: [3,]  0.0018232  2.3117e-02  0.01744245 -0.00203333  0.01143001  1.3527e-04
: [4,] -0.0078822 -1.7526e-03 -0.00203333  0.00075832 -0.00590408 -1.0488e-04
: [5,]  0.0684574  6.8850e-03  0.01143001 -0.00590408  0.04758314  8.7018e-04
: [6,]  0.0013253  1.8197e-05  0.00013527 -0.00010488  0.00087018  1.6284e-05

- the simulation error
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
covE <- covB/n.imputed
print(covE, digits = 5)
#+END_SRC

#+RESULTS:
:             [,1]        [,2]        [,3]        [,4]        [,5]        [,6]
: [1,]  0.03767828 -3.8156e-03  0.00060772 -2.6274e-03  0.02281915  4.4177e-04
: [2,] -0.00381559  1.0780e-02  0.00770554 -5.8419e-04  0.00229499  6.0656e-06
: [3,]  0.00060772  7.7055e-03  0.00581415 -6.7778e-04  0.00381000  4.5090e-05
: [4,] -0.00262740 -5.8419e-04 -0.00067778  2.5277e-04 -0.00196803 -3.4962e-05
: [5,]  0.02281915  2.2950e-03  0.00381000 -1.9680e-03  0.01586105  2.9006e-04
: [6,]  0.00044177  6.0656e-06  0.00004509 -3.4962e-05  0.00029006  5.4279e-06

The total variance is:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
covT <- covW + covB + covE
#+END_SRC

#+RESULTS:

leading to the standard errors:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
sqrt(diag(covT))
#+END_SRC
#+RESULTS:
:  (Intercept)      groupHC seasonsummer          bmi genderFemale          age 
:  0.970756912  0.319142478  0.286505516  0.049550963  0.353001211  0.008348779

# #+BEGIN_SRC R :exports both :results output :session *R* :cache no
# summary(ePool.mice)$std.error
# #+END_SRC

# #+RESULTS:
# : [1] 0.744297026 0.198790594 0.228668346 0.030690688 0.206315648 0.005623804


\bigskip

There is also a function to extract the R-squared:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
pool.r.squared(e.mice)
#+END_SRC

#+RESULTS:
:           est     lo 95     hi 95        fmi
: R^2 0.9961692 0.9942275 0.9974586 0.06584253

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
vec.rsquared <- sapply(e.mice$analyses, function(iImp){
    summary(iImp)$r.squared
})
tanh(mean(atanh(vec.rsquared)))
#+END_SRC

#+RESULTS:
: [1] 0.9961692

\clearpage

* Special case: stratified imputation \newline and variable transformation

Mice can be adapted to use a group-specific imputation model[fn:https://thestatsgeek.com/2021/06/02/multiple-imputation-separately-by-groups-in-r-and-stata/
]:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
dtMale.data <- dt.data[dt.data$gender=="Male",]
dtFemale.data <- dt.data[dt.data$gender=="Female",]

all.variables <- c("Y","group","season","bmi","age","gender")
n.variables <- length(all.variables)
Mlink <- matrix(0, n.variables, n.variables,
                dimnames = list(all.variables,all.variables))
Mlink["bmi",c("group","season","age")] <- 1
Mlink

## stratified imputation
dtMale.mice <- mice(dtMale.data,
                    m=10, 
                    maxit = 50, 
                    predictorMatrix = Mlink,
                    method = c("","","","norm","",""),
                    seed = 500, printFlag = FALSE)
dtFemale.mice <- mice(dtFemale.data,
                      m=10, 
                      maxit = 50,
                      predictorMatrix = Mlink,
                      method = c("","","","norm","",""),
                      seed = 500, printFlag = FALSE)
dt.mice <- rbind(dtMale.mice, dtFemale.mice)

## sanity check
test <- complete(dt.mice)$bmi
GS <-  c(complete(dtMale.mice)$bmi,
             complete(dtFemale.mice)$bmi)
range(test-GS)
#+END_SRC

#+RESULTS:
#+begin_example
       Y group season bmi age gender
Y      0     0      0   0   0      0
group  0     0      0   0   0      0
season 0     0      0   0   0      0
bmi    0     1      1   0   1      0
age    0     0      0   0   0      0
gender 0     0      0   0   0      0
Advarselsbesked:
Number of logged events: 1
Advarselsbesked:
Number of logged events: 1
[1] 0 0
#+end_example

and to define new variables post-imputation[fn:https://github.com/amices/mice/issues/34]:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
dtLong.mice <- complete(dt.mice, action='long', include=TRUE)
dtLong.mice$newvar <- dtLong.mice$Y^2
dt2.mice <- as.mids(dtLong.mice)

## sanity check
range(complete(dt2.mice)$newvar - complete(dt.mice)$Y^2)

## run model
elm.mice <- with(dt2.mice, lm(newvar ~ group+season+bmi+age+gender))
summary(pool(elm.mice))
#+END_SRC

#+RESULTS:
: [1] 0 0
:           term    estimate  std.error   statistic       df      p.value
: 1  (Intercept) -4389.00375 386.635258 -11.3517939 23.29985 5.655387e-11
: 2      groupHC   -53.95254  82.370728  -0.6549965 83.82218 5.142635e-01
: 3 seasonsummer   172.60520  84.141766   2.0513617 75.16262 4.371633e-02
: 4          bmi   115.09828  16.840419   6.8346443 19.81157 1.275398e-06
: 5          age   148.31890   2.280725  65.0314676 84.14586 0.000000e+00
: 6 genderFemale   203.09995  84.971650   2.3902084 69.70597 1.954547e-02

\clearpage

* Special case: imputation using a specific law and no covariate
Mice can be adapted in order, for instance, to sample from a uniform
distribution or a truncated normal distribution. First define a
function able to generate data like:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
mice.impute.SI_unif <- function(y, ry, ...){ ## uniform xglaw
    n.NA <- sum(ry==FALSE)
    sample <- runif(n.NA, min = 0, max = 1)
    return(cbind(sample))
}
#+END_SRC

or

#+BEGIN_SRC R :exports both :results output :session *R* :cache no
mice.impute.SI_tnorm <- function(y, ry, ...){ ## truncated normal law
    require(truncnorm)
    n.NA <- sum(ry==FALSE)
    sample <- rtruncnorm(n.NA, a = 0, b = 1, mean = 1, sd = 0.1)
    return(cbind(sample))
}
#+END_SRC
#+RESULTS:

Then prepare the matrix indicating which variable should be used
during the imputation:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
impute.var <- c("bmi","group")
Mlink2 <- matrix(0, 
                 nrow = length(impute.var), 
                 ncol = length(impute.var), 
                 dimnames = list(impute.var,impute.var))
Mlink2["bmi","group"] <- 1
Mlink2
#+END_SRC

#+RESULTS:
:       bmi group
: bmi     0     1
: group   0     0

\clearpage 

Then run mice as usual except that the method should correspond to one of the previous functions:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
n.imputed <- 50 ## number of imputed datasets
set.seed(1)
dt.mice2 <- mice(dt.data,
                 m=n.imputed, 
                 maxit = 1, # not relevant
                 predictorMatrix = Mlink2, # not relevant
                 method = 'SI_tnorm', # function previous define (without "mice.impute.")
                 seed = 500, printFlag = FALSE)
#+END_SRC

#+RESULTS:

Then as usual one should check that the imputed values are satisfying:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
quantile(unlist(dt.mice2$imp$bmi))
#+END_SRC

#+RESULTS:
:        0%       25%       50%       75%      100% 
: 0.7041556 0.8790477 0.9317021 0.9687630 0.9997288


#+BEGIN_SRC R :exports both :results output :session *R* :cache no
hist(unlist(dt.mice2$imp$bmi))
#+END_SRC

#+RESULTS:

# #+BEGIN_SRC R :results graphics :file "./figures/histImputed2.pdf" :exports results :session *R* :cache no
# hist(unlist(dt.mice2$imp$bmi))
# #+END_SRC


#+ATTR_LaTeX: :width 0.8\textwidth :placement [!h]
[[file:./figures/histImputed2.pdf]]

\clearpage

One more plot:
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
stripplot(dt.mice2, bmi~.imp, pch=20, cex=2)
#+END_SRC

#+RESULTS:

# #+BEGIN_SRC R :results graphics :file "./figures/striplotImputed2.pdf" :exports results :session *R* :cache no
# stripplot(dt.mice2, bmi~.imp, pch=20, cex=2)
# #+END_SRC

#+RESULTS:
[[file:./figures/striplotImputed2.pdf]]

Here for instance the imputed values does not overlap the observed one
so something (i.e. the parameters of the distribution used for the
imputation) is wrong.

# \bigskip

# Then as before one can fit the statistical model using =with=:
# #+BEGIN_SRC R :exports both :results output :session *R* :cache no
# e.mice2 <- with(data = dt.mice2,
#                 lm(Y~group+season+bmi+gender+age)
#                 )
# ePool.mice2 <- pool(e.mice2)
# summary(ePool.mice2)
# #+END_SRC

# #+RESULTS:
# :                estimate  std.error statistic       df      p.value
# : (Intercept)  16.3571621 1.44891707 11.289233 92.05265 0.000000e+00
# : groupHC       0.3117620 0.64131399  0.486130 92.05265 6.280303e-01
# : seasonsummer  1.6171573 0.63762913  2.536204 92.05265 1.289066e-02
# : bmi           0.2207013 0.04502684  4.901550 92.05265 4.065644e-06
# : genderFemale  0.9072630 0.63710993  1.424029 92.05265 1.578191e-01
# : age           1.0209777 0.01772960 57.586060 92.05265 0.000000e+00

\clearpage

* Reporting guideline 
From https://stefvanbuuren.name/Winnipeg/Lectures/Winnipeg.pdf:
- Amount of missing data
- Reasons for missingness
- Differences between complete and incomplete data
- Method used to account for missing data
- Software
- Number of imputed datasets
- Imputation model
- Derived variables
- Diagnostics
- Pooling
- Listwise deletion
- Sensitivity analysis


* Reference
# help: https://gking.harvard.edu/files/natnotes2.pdf

#+BEGIN_EXPORT latex
\begingroup
\renewcommand{\section}[2]{}
#+END_EXPORT
bibliographystyle:apalike
[[bibliography:bibliography.bib]] 
#+BEGIN_EXPORT latex
\endgroup
#+END_EXPORT

#+BEGIN_EXPORT LaTeX
\appendix
\titleformat{\section}
{\normalfont\Large\bfseries}{}{1em}{Appendix~\thesection:~}

\renewcommand{\thefigure}{\Alph{figure}}
\renewcommand{\thetable}{\Alph{table}}
\renewcommand{\theequation}{\Alph{equation}}

\setcounter{figure}{0}    
\setcounter{table}{0}    
\setcounter{equation}{0}    

\setcounter{page}{1}
#+END_EXPORT

* CONFIG :noexport:
#+LANGUAGE:  en
#+LaTeX_CLASS: org-article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+OPTIONS:   title:t author:t toc:nil todo:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t

** Display of the document
# ## space between lines
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER:\renewcommand{\baselinestretch}{1.1}

# ## margins
#+LATEX_HEADER:\geometry{top=1cm}

# ## personalize the prefix in the name of the sections
#+LaTeX_HEADER: \usepackage{titlesec}
# ## fix bug in titlesec version
# ##  https://tex.stackexchange.com/questions/299969/titlesec-loss-of-section-numbering-with-the-new-update-2016-03-15
#+LaTeX_HEADER: \usepackage{etoolbox}
#+LaTeX_HEADER: 
#+LaTeX_HEADER: \makeatletter
#+LaTeX_HEADER: \patchcmd{\ttlh@hang}{\parindent\z@}{\parindent\z@\leavevmode}{}{}
#+LaTeX_HEADER: \patchcmd{\ttlh@hang}{\noindent}{}{}{}
#+LaTeX_HEADER: \makeatother

** Color
# ## define new colors
#+LATEX_HEADER: \RequirePackage{colortbl} % arrayrulecolor to mix colors
#+LaTeX_HEADER: \definecolor{myorange}{rgb}{1,0.2,0}
#+LaTeX_HEADER: \definecolor{mypurple}{rgb}{0.7,0,8}
#+LaTeX_HEADER: \definecolor{mycyan}{rgb}{0,0.6,0.6}
#+LaTeX_HEADER: \newcommand{\lightblue}{blue!50!white}
#+LaTeX_HEADER: \newcommand{\darkblue}{blue!80!black}
#+LaTeX_HEADER: \newcommand{\darkgreen}{green!50!black}
#+LaTeX_HEADER: \newcommand{\darkred}{red!50!black}
#+LaTeX_HEADER: \definecolor{gray}{gray}{0.5}

# ## change the color of the links
#+LaTeX_HEADER: \hypersetup{
#+LaTeX_HEADER:  citecolor=[rgb]{0,0.5,0},
#+LaTeX_HEADER:  urlcolor=[rgb]{0,0,0.5},
#+LaTeX_HEADER:  linkcolor=[rgb]{0,0,0.5},
#+LaTeX_HEADER: }

** Font
# https://tex.stackexchange.com/questions/25249/how-do-i-use-a-particular-font-for-a-small-section-of-text-in-my-document
#+LaTeX_HEADER: \newenvironment{mycomment}{\small \color{gray}\fontfamily{lmtt}\selectfont}{\par}
#+LaTeX_HEADER: \newenvironment{myactivity}{\color{orange}\fontfamily{qzc}\selectfont}{\par}

** Symbols
# ## valid and cross symbols
#+LaTeX_HEADER: \RequirePackage{pifont}
#+LaTeX_HEADER: \RequirePackage{relsize}
#+LaTeX_HEADER: \newcommand{\Cross}{{\raisebox{-0.5ex}%
#+LaTeX_HEADER:		{\relsize{1.5}\ding{56}}}\hspace{1pt} }
#+LaTeX_HEADER: \newcommand{\Valid}{{\raisebox{-0.5ex}%
#+LaTeX_HEADER:		{\relsize{1.5}\ding{52}}}\hspace{1pt} }
#+LaTeX_HEADER: \newcommand{\CrossR}{ \textcolor{red}{\Cross} }
#+LaTeX_HEADER: \newcommand{\ValidV}{ \textcolor{green}{\Valid} }

# ## warning symbol
#+LaTeX_HEADER: \usepackage{stackengine}
#+LaTeX_HEADER: \usepackage{scalerel}
#+LaTeX_HEADER: \newcommand\Warning[1][3ex]{%
#+LaTeX_HEADER:   \renewcommand\stacktype{L}%
#+LaTeX_HEADER:   \scaleto{\stackon[1.3pt]{\color{red}$\triangle$}{\tiny\bfseries !}}{#1}%
#+LaTeX_HEADER:   \xspace
#+LaTeX_HEADER: }

# # R Software
#+LATEX_HEADER: \newcommand\Rlogo{\textbf{\textsf{R}}\xspace} % 

** Code
# Documentation at https://org-babel.readthedocs.io/en/latest/header-args/#results
# :tangle (yes/no/filename) extract source code with org-babel-tangle-file, see http://orgmode.org/manual/Extracting-source-code.html 
# :cache (yes/no)
# :eval (yes/no/never)
# :results (value/output/silent/graphics/raw/latex)
# :export (code/results/none/both)
#+PROPERTY: header-args :session *R* :tangle yes :cache no ## extra argument need to be on the same line as :session *R*

# Code display:
#+LATEX_HEADER: \RequirePackage{fancyvrb}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small,formatcom = {\color[rgb]{0.5,0,0}}}

# ## change font size input (global change)
# ## doc: https://ctan.math.illinois.edu/macros/latex/contrib/listings/listings.pdf
# #+LATEX_HEADER: \newskip\skipamount   \skipamount =6pt plus 0pt minus 6pt
# #+LATEX_HEADER: \lstdefinestyle{code-tiny}{basicstyle=\ttfamily\tiny, aboveskip =  kipamount, belowskip =  kipamount}
# #+LATEX_HEADER: \lstset{style=code-tiny}
# ## change font size input (local change, put just before BEGIN_SRC)
# ## #+ATTR_LATEX: :options basicstyle=\ttfamily\scriptsize
# ## change font size output (global change)
# ## \RecustomVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\tiny,formatcom = {\color[rgb]{0.5,0,0}}}

** Lists
#+LATEX_HEADER: \RequirePackage{enumitem} % better than enumerate

** Image and graphs
#+LATEX_HEADER: \RequirePackage{epstopdf} % to be able to convert .eps to .pdf image files
#+LATEX_HEADER: \RequirePackage{capt-of} % 
#+LATEX_HEADER: \RequirePackage{caption} % newlines in graphics

#+LaTeX_HEADER: \RequirePackage{tikz-cd} % graph
# ## https://tools.ietf.org/doc/texlive-doc/latex/tikz-cd/tikz-cd-doc.pdf

** Table
#+LATEX_HEADER: \RequirePackage{booktabs} % for nice lines in table (e.g. toprule, bottomrule, midrule, cmidrule)

** Inline latex
# @@latex:any arbitrary LaTeX code@@


** Algorithm
#+LATEX_HEADER: \RequirePackage{amsmath}
#+LATEX_HEADER: \RequirePackage{algorithm}
#+LATEX_HEADER: \RequirePackage[noend]{algpseudocode}

** Math
#+LATEX_HEADER: \RequirePackage{dsfont}
#+LATEX_HEADER: \RequirePackage{amsmath,stmaryrd,graphicx}
#+LATEX_HEADER: \RequirePackage{prodint} % product integral symbol (\PRODI)

# ## lemma
# #+LaTeX_HEADER: \RequirePackage{amsthm}
# #+LaTeX_HEADER: \newtheorem{theorem}{Theorem}
# #+LaTeX_HEADER: \newtheorem{lemma}[theorem]{Lemma}

*** Template for shortcut
#+LATEX_HEADER: \usepackage{ifthen}
#+LATEX_HEADER: \usepackage{xifthen}
#+LATEX_HEADER: \usepackage{xargs}
#+LATEX_HEADER: \usepackage{xspace}

#+LATEX_HEADER: \newcommand\defOperator[7]{%
#+LATEX_HEADER:	\ifthenelse{\isempty{#2}}{
#+LATEX_HEADER:		\ifthenelse{\isempty{#1}}{#7{#3}#4}{#7{#3}#4 \left#5 #1 \right#6}
#+LATEX_HEADER:	}{
#+LATEX_HEADER:	\ifthenelse{\isempty{#1}}{#7{#3}#4_{#2}}{#7{#3}#4_{#1}\left#5 #2 \right#6}
#+LATEX_HEADER: }
#+LATEX_HEADER: }

#+LATEX_HEADER: \newcommand\defUOperator[5]{%
#+LATEX_HEADER: \ifthenelse{\isempty{#1}}{
#+LATEX_HEADER:		#5\left#3 #2 \right#4
#+LATEX_HEADER: }{
#+LATEX_HEADER:	\ifthenelse{\isempty{#2}}{\underset{#1}{\operatornamewithlimits{#5}}}{
#+LATEX_HEADER:		\underset{#1}{\operatornamewithlimits{#5}}\left#3 #2 \right#4}
#+LATEX_HEADER: }
#+LATEX_HEADER: }

#+LATEX_HEADER: \newcommand{\defBoldVar}[2]{	
#+LATEX_HEADER:	\ifthenelse{\equal{#2}{T}}{\boldsymbol{#1}}{\mathbf{#1}}
#+LATEX_HEADER: }

**** Probability
#+LATEX_HEADER: \newcommandx\Esp[2][1=,2=]{\defOperator{#1}{#2}{E}{}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Prob[2][1=,2=]{\defOperator{#1}{#2}{P}{}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Qrob[2][1=,2=]{\defOperator{#1}{#2}{Q}{}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Var[2][1=,2=]{\defOperator{#1}{#2}{V}{ar}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Cov[2][1=,2=]{\defOperator{#1}{#2}{C}{ov}{\lbrack}{\rbrack}{\mathbb}}

#+LATEX_HEADER: \newcommandx\Binom[2][1=,2=]{\defOperator{#1}{#2}{B}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Gaus[2][1=,2=]{\defOperator{#1}{#2}{N}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Wishart[2][1=,2=]{\defOperator{#1}{#2}{W}{ishart}{(}{)}{\mathcal}}

#+LATEX_HEADER: \newcommandx\Likelihood[2][1=,2=]{\defOperator{#1}{#2}{L}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\logLikelihood[2][1=,2=]{\defOperator{#1}{#2}{\ell}{}{(}{)}{}}
#+LATEX_HEADER: \newcommandx\Information[2][1=,2=]{\defOperator{#1}{#2}{I}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Score[2][1=,2=]{\defOperator{#1}{#2}{S}{}{(}{)}{\mathcal}}

**** Operators
#+LATEX_HEADER: \newcommandx\Vois[2][1=,2=]{\defOperator{#1}{#2}{V}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\IF[2][1=,2=]{\defOperator{#1}{#2}{IF}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Ind[1][1=]{\defOperator{}{#1}{1}{}{(}{)}{\mathds}}

#+LATEX_HEADER: \newcommandx\Max[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{min}}
#+LATEX_HEADER: \newcommandx\Min[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{max}}
#+LATEX_HEADER: \newcommandx\argMax[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{argmax}}
#+LATEX_HEADER: \newcommandx\argMin[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{argmin}}
#+LATEX_HEADER: \newcommandx\cvD[2][1=D,2=n \rightarrow \infty]{\xrightarrow[#2]{#1}}

#+LATEX_HEADER: \newcommandx\Hypothesis[2][1=,2=]{
#+LATEX_HEADER:         \ifthenelse{\isempty{#1}}{
#+LATEX_HEADER:         \mathcal{H}
#+LATEX_HEADER:         }{
#+LATEX_HEADER: 	\ifthenelse{\isempty{#2}}{
#+LATEX_HEADER: 		\mathcal{H}_{#1}
#+LATEX_HEADER: 	}{
#+LATEX_HEADER: 	\mathcal{H}^{(#2)}_{#1}
#+LATEX_HEADER:         }
#+LATEX_HEADER:         }
#+LATEX_HEADER: }

#+LATEX_HEADER: \newcommandx\dpartial[4][1=,2=,3=,4=\partial]{
#+LATEX_HEADER: 	\ifthenelse{\isempty{#3}}{
#+LATEX_HEADER: 		\frac{#4 #1}{#4 #2}
#+LATEX_HEADER: 	}{
#+LATEX_HEADER: 	\left.\frac{#4 #1}{#4 #2}\right\rvert_{#3}
#+LATEX_HEADER: }
#+LATEX_HEADER: }

#+LATEX_HEADER: \newcommandx\dTpartial[3][1=,2=,3=]{\dpartial[#1][#2][#3][d]}

#+LATEX_HEADER: \newcommandx\ddpartial[3][1=,2=,3=]{
#+LATEX_HEADER: 	\ifthenelse{\isempty{#3}}{
#+LATEX_HEADER: 		\frac{\partial^{2} #1}{\partial #2^2}
#+LATEX_HEADER: 	}{
#+LATEX_HEADER: 	\frac{\partial^2 #1}{\partial #2\partial #3}
#+LATEX_HEADER: }
#+LATEX_HEADER: } 

**** General math
#+LATEX_HEADER: \newcommand\Real{\mathbb{R}}
#+LATEX_HEADER: \newcommand\Rational{\mathbb{Q}}
#+LATEX_HEADER: \newcommand\Natural{\mathbb{N}}
#+LATEX_HEADER: \newcommand\trans[1]{{#1}^\intercal}%\newcommand\trans[1]{{\vphantom{#1}}^\top{#1}}
#+LATEX_HEADER: \newcommand{\independent}{\mathrel{\text{\scalebox{1.5}{$\perp\mkern-10mu\perp$}}}}
#+LaTeX_HEADER: \newcommand\half{\frac{1}{2}}
#+LaTeX_HEADER: \newcommand\normMax[1]{\left|\left|#1\right|\right|_{max}}
#+LaTeX_HEADER: \newcommand\normTwo[1]{\left|\left|#1\right|\right|_{2}}

#+LATEX_HEADER: \newcommand\Veta{\boldsymbol{\eta}}
#+LATEX_HEADER: \newcommand\VX{\mathbf{X}}


** Notations
