#+TITLE: Different types of ICC in R

#+BEGIN_SRC R :exports none :session *R* :cache no
path <- "~/Documents/GitHub/bozenne.github.io/doc/2018-10-27-ICC/"
path.figure <- file.path(path,"figures")
#+END_SRC


In this document, we will consider measurements done at several
sessions over several individuals. We assume no missing data, i.e.,
all individuals have measurements for all sessions. The question we
would like to answer is what is the reliability of the measurements?

#+BEGIN_EXPORT latex
\begingroup
\renewcommand{\section}[2]{}
\tableofcontents
\endgroup
#+END_EXPORT

\clearpage

Recommanded references: 
- Kenneth O. McGraw and S. P. Wong *Forming Inferences About Some Intraclass Correlation Coefficients*, Psychological Methods, 1996, Vol. l,No. 1,30-46
- Lawrence Lin, A.S. Hedayat, Wenting Wu, *Statistical Tools for Measuring Agreement*, 2012, Springer. 

\clearpage

* Preparation

#+LATEX: \lstset{style=code-tiny}

** Load R packages
#+BEGIN_SRC R :export code :results both :session *R* :cache no 
library(data.table)
library(lava)
library(lme4)
library(nlme)
library(irr)
library(psych)
#+END_SRC

#+RESULTS:
#+BEGIN_SRC R
irr
lpSolve
psych
lme4
Matrix
lava
mgcv
nlme
ggplot2
data.table
splines
stats
graphics
grDevices
utils
datasets
methods
base
#+END_SRC



** Data generation
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
n.id <- 10
n.scan <- 2
n.rater <- 5

set.seed(10)
m <- lvm(c(Ytest,Yretest) ~ 2*eta)
latent(m) <- ~eta
distribution(m, ~Ytest) <- lava::gaussian.lvm(mean = 1, sd = 1)
distribution(m, ~Yretest) <- lava::gaussian.lvm(mean = 1, sd = 1)

dtW.icc1 <- as.data.table(lava::sim(m, n.id))
dtW.icc1[, eta := NULL]
dtW.icc1[, Id := as.character(1:.N)]
dtL.icc1 <- melt(dtW.icc1, id.vars = "Id", value.name = "Y", variable.name = "session")

dfW.icc1 <- as.data.frame(dtW.icc1)
dfL.icc1 <- as.data.frame(dtL.icc1)

mm <- lvm(c(Y1,Y2,Y3,Y4,Y5) ~ 2*eta)
latent(mm) <- ~eta
distribution(mm, ~Y1) <- lava::gaussian.lvm(mean = 1, sd = 1)
distribution(mm, ~Y2) <- lava::gaussian.lvm(mean = 1, sd = 1)
distribution(mm, ~Y3) <- lava::gaussian.lvm(mean = 1, sd = 1)
distribution(mm, ~Y4) <- lava::gaussian.lvm(mean = 1, sd = 1)
distribution(mm, ~Y5) <- lava::gaussian.lvm(mean = 1, sd = 1)

dtW.icc2 <- as.data.table(lava::sim(mm, n.id))
dtW.icc2[, eta := NULL]
dtW.icc2[, Id := as.character(1:.N)]
dtL.icc2 <- melt(dtW.icc2, id.vars = "Id", value.name = "Y", variable.name = "session")

dfW.icc2 <- as.data.frame(dtW.icc2)
dfL.icc2 <- as.data.frame(dtL.icc2)
#+END_SRC


#+RESULTS:

\clearpage

* ICC1: fixed number of sessions assuming no session effect

Using ICC1, we assess the absolute agreement among measurements
repeated over one random factor (here patient identity) assuming no
other effect. The number of sessions is fixed meaning that it is
precisely those sessions that are interesting. 

\bigskip

/Example:/ we want to plan a study to assess treatment efficacy with
two sessions: baseline and post-treatment. EEG is used to measure
treatment efficacy. Prior to this study, another study is performed to
assessed the stability of the EEG measurement between two sessions. We
don't expect systematic difference in EEG signal between the sessions.

\bigskip

ICC1 is equivalent to the following mixed model:

#+BEGIN_EXPORT latex
\begin{equation}
 Y_{i,t} = \alpha + u_{i} + \varepsilon_{i,t} 
\end{equation}

\begin{tabular}{ll}
where & \(u_{i} \sim \Gaus[0,\tau^2] \)  \\
& \(\varepsilon_{i,t} \sim \Gaus[0,\sigma^2] \) \\
\end{tabular}

\begin{align}
 ICC^{single}_{1,agreement} &= \frac{\tau^2}{\tau^2 + \sigma^2} \\
 ICC^{average}_{1,agreement} &= \frac{\tau^2}{\tau^2 + \frac{\sigma^2}{n}}
\end{align}
#+END_EXPORT

** using mixed models
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
lme_ICC1 <- lmer(Y ~ 1 + (1|Id), data = dtL.icc1)

sigma_id <- attr(VarCorr(lme_ICC1)[[1]],"stddev")
sigma_error <- attr(VarCorr(lme_ICC1),"sc")

ICC1.lme <- c(
    single = as.double(sigma_id^2/(sigma_error^2+sigma_id^2)),
    average = as.double(sigma_id^2/(sigma_error^2/n.scan+sigma_id^2))
)

ICC1.lme
#+END_SRC

#+RESULTS:
:    single   average 
: 0.5191614 0.6834842

** using generalized least squares
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
gls_ICC1 <- gls(Y ~ 1, correlation = corCompSymm(form = ~ 1|Id), 
                data = dtL.icc1)

## correlation matrix
unclass(cov2cor(getVarCov(gls_ICC1)))
#+END_SRC

#+RESULTS:
:           [,1]      [,2]
: [1,] 1.0000000 0.5191607
: [2,] 0.5191607 1.0000000

# *** using lvm
# #+BEGIN_SRC R :results output :exports both :session *R* :cache no 
# lvm_ICC1 <- lvm(c(Ytest,Yretest) ~ 0+1*eta)
# covariance(lvm_ICC1, ~Ytest) <- "sigma2" # force same variance
# covariance(lvm_ICC1, ~Yretest) <- "sigma2" # force same variance
# latent(lvm_ICC1) <- ~eta

# elvm_ICC1 <- estimate(lvm_ICC1, data = dtW.data)

# summary(elvm_ICC1)
# #+END_SRC

** using anova
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
aov_ICC1 <- aov(Y ~ Error(Id), data = dtL.icc1) 

MSB <- summary(aov_ICC1)[["Error: Id"]][[1]]["Mean Sq"]
MSW <- summary(aov_ICC1)[["Error: Within"]][[1]]["Mean Sq"]

ICC1.aov <-  c(
    single = as.double((MSB - MSW)/(MSB + (n.scan-1)*MSW)),
    average = as.double((MSB - MSW)/MSB)
)
ICC1.aov
#+END_SRC

#+RESULTS:
:    single   average 
: 0.5191614 0.6834842

** using existing packages
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
tt.single <- c(irr = irr::icc(dfW.icc1[,c("Ytest", "Yretest")],
                              model="oneway", type="consistency")$value,
               psych = psych::ICC(dfW.icc1[,c("Ytest", "Yretest")])[[1]]$ICC[1])

tt.average <- c(irr = irr::icc(dfW.icc1[,c("Ytest", "Yretest")],
                               model="oneway", type="consistency", unit = "average")$value,
                psych = psych::ICC(dfW.icc1[,c("Ytest", "Yretest")])[[1]]$ICC[4])

rbind(single = tt.single, average = tt.average)
#+END_SRC

#+RESULTS:
:               irr     psych
: single  0.5191614 0.5191609
: average 0.6834842 0.6834838

\clearpage

* ICC3: fixed number of sessions accounting for a session effect

Using ICC3, we assess the absolute agreement among measurements
repeated over one random factor (here patient identity) accounting for
a possible session effect. The number of sessions is fixed meaning
that it is precisely those sessions that are interesting.

\bigskip

/Example:/ we want to plan a study (called main study) to assess
treatment efficacy with two sessions: baseline and post-treatment. EEG
is used to measure treatment efficacy. Prior to this study, another
study is performed to assessed the stability of the EEG measurement
between two sessions. Unfortunately the two measurements were not
performed using the same EEG machine so we suspect a systematic
difference in EEG signal between the sessions. The investigator will
make sure that this won't happen in the main study. Therefore the
systematic difference is not inherant to the EEG technic (i.e. won't
be observed in the main study).

\bigskip

/Note:/  In test
re-test analysis this should not be the case since we replicate a
measurement under the same conditions.

\bigskip
\bigskip

Using ICC3, we assess the absolute agreement among measurements
repeated over one random factor account for a possible session
effect. Compared to ICC1, this will lead to:
- a lower \(\sigma^2\) (some of the residual variance is explained)
- a higher \(\tau\) (individual measurements are better correlated since
  there is less arbitrary variation between them)
- a higher ICC

\bigskip

ICC3 is equivalent to the following mixed model:

#+BEGIN_EXPORT latex
\begin{equation}
 Y_{i,t} = \alpha + \beta_t t + u_{i} + \varepsilon_{i,t} 
\end{equation}

\begin{tabular}{ll}
where & \(u_{i} \sim \Gaus[0,\tau^2] \)  \\
& \(t\) is treated as a categorical variable \\
& \(\varepsilon_{i,t} \sim \Gaus[0,\sigma^2] \) \\
\end{tabular}

\begin{align}
 ICC^{single}_{1,agreement} &= \frac{\tau^2}{\tau^2 + \sigma^2} \\
 ICC^{average}_{1,agreement} &= \frac{\tau^2}{\tau^2 + \frac{\sigma^2}{n}}
\end{align}
#+END_EXPORT

\clearpage

** using mixed models
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
lme_ICC2 <- lmer(Y ~ session + (1|Id), data = dtL.icc1)

sigma_id <- attr(VarCorr(lme_ICC2)[[1]],"stddev")
sigma_error <- attr(VarCorr(lme_ICC2),"sc")

ICC2.lme <- c(
    single = as.double(sigma_id^2/(sigma_error^2+sigma_id^2)),
    average = as.double(sigma_id^2/(sigma_error^2/n.scan+sigma_id^2))
)

ICC2.lme
#+END_SRC

#+RESULTS:
:    single   average 
: 0.7495312 0.8568366


** using generalized least squares
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
gls_ICC2 <- gls(Y ~ session, correlation = corCompSymm(form = ~ 1|Id), data = dtL.icc1)

# correlation matrix
unclass(cov2cor(getVarCov(gls_ICC2)))
#+END_SRC

#+RESULTS:
:           [,1]      [,2]
: [1,] 1.0000000 0.7495308
: [2,] 0.7495308 1.0000000


** using anova
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
aov_ICC2 <- aov(Y ~ session + Error(Id), data = dtL.icc1) 

MSB <- summary(aov_ICC2)[["Error: Id"]][[1]]["Mean Sq"]
MSW <- summary(aov_ICC2)[["Error: Within"]][[1]]["Residuals","Mean Sq"]

ICC2.aov <-  c(
    single = as.double((MSB - MSW)/(MSB + (n.scan-1)*MSW)),
    average = as.double((MSB - MSW)/MSB)
)

ICC2.aov
#+END_SRC

#+RESULTS:
:    single   average 
: 0.7495312 0.8568366


** using existing packages
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
# single
cat("single \n")
psych::ICC(dfW.icc1[,c("Ytest", "Yretest")])[[1]]$ICC[3]

# average
cat("average \n")
psych::ICC(dfW.icc1[,c("Ytest", "Yretest")])[[1]]$ICC[6]
#+END_SRC

#+RESULTS:
: single
: [1] 0.7495307
: average
: [1] 0.8568363

* Heterogenous variance between sessions

The previous ICC are not corrected for a possible difference in
variance between sessions:
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
gls_heteroV <- gls(Y ~ session, 
                   weights = varIdent(form = ~ 1|session),
                   correlation = corCompSymm(form = ~ 1|Id), 
                   data = dtL.icc1)

# correlation matrix
unclass(cov2cor(getVarCov(gls_heteroV)))
#+END_SRC

#+RESULTS:
:          [,1]     [,2]
: [1,] 1.000000 0.763223
: [2,] 0.763223 1.000000

In test re-test analysis this should not be the case since we
replicate a measurement under the same conditions.

\clearpage


* ICC2: random number of sessions

Using ICC2, we assess the absolute agreement among measurements
repeated over two random factors, e.g. patient identity and
sessions. We don't account for a possible session effect. The number
of sessions is random meaning that we are not precisely interested in
those sessions. A more realistic example would be to consider raters
instead of sessions.

\bigskip

/Example:/ we want to study the reliability of the grades given by
teachers. We include 10 teachers that will grade 20 students. We are
not interested in those specific teachers since further studies may be
performed in other schools with other teachers.

\bigskip

ICC2 is equivalent to the following mixed model:
#+BEGIN_EXPORT latex
\begin{equation}
Y_{i,j,t} = \alpha + u_{i} + v_{j} + \varepsilon_{i,j,t}
\end{equation}

\begin{tabular}{ll}
where & \(u_{i} \sim \Gaus[0,\tau^2] \) \\
 &  \(v_{j} \sim \Gaus[0,\delta^2] \) \\
 & \(\varepsilon_{i,t} \sim \Gaus[0,\sigma^2] \) \\
\end{tabular}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{align}
 ICC_{2,agreement} &= \frac{\tau^2}{\tau^2 + \sigma^2} \text{ or } ICC_{2,consistency} = \frac{\tau^2}{\tau^2 + \delta^2 + \sigma^2} \\
 ICC^{average}_{2,agreement} &= \frac{\tau^2}{\tau^2 + \frac{\sigma^2}{n}} \text{ or } ICC^{average}_{2,consistency} = \frac{\tau^2}{\tau^2 + \frac{1}{n}(\delta^2 + \sigma^2)}
\end{align}
#+END_EXPORT


** using mixed models
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
lme_ICC2r <- lmer(Y ~ 1 + (1|session)+ (1|Id), data = dtL.icc2)

sigma_id <- attr(VarCorr(lme_ICC2r)[[1]],"stddev")
sigma_scan <- attr(VarCorr(lme_ICC2r)[[2]],"stddev")
sigma_error <- attr(VarCorr(lme_ICC2r),"sc")

ICC2r.lme <- c(
    consistency.single = as.double(sigma_id^2/(sigma_error^2+sigma_id^2)),
    agreement.single = as.double(sigma_id^2/(sigma_error^2+sigma_scan^2+sigma_id^2)),
    consistency.average = as.double(sigma_id^2/(sigma_error^2/n.rater+sigma_id^2)),
    agreement.average = as.double(sigma_id^2/(sigma_error^2/n.rater+sigma_scan^2/n.rater+sigma_id^2))
)
ICC2r.lme
#+END_SRC

#+RESULTS:
:  consistency.single    agreement.single consistency.average   agreement.average 
:           0.8057243           0.8001868           0.9539947           0.9524339

\clearpage

** using generalized least squares
Don't know how to specify non-nested random effects

** using anova
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
aov_ICC2r <- aov(Y ~ Error(session + Id), data = dtL.icc2) 

MSB <- summary(aov_ICC2r)[["Error: Id"]][[1]]["Mean Sq"]
MSscan <- summary(aov_ICC2r)[["Error: session"]][[1]]["Residuals","Mean Sq"]
MSW <- summary(aov_ICC2r)[["Error: Within"]][[1]]["Residuals","Mean Sq"]

ICC2r.aov <-  c(
    consistency.single = as.double((MSB - MSW)/(MSB + (n.rater-1)*MSW)),
    agreement.single = as.double((MSB - MSW)/(MSB + (n.rater-1)*MSW + n.rater * (MSscan-MSW)/n.id)),
    consistency.average = as.double((MSB - MSW)/MSB),
    agreement.average = as.double((MSB - MSW)/(MSB + (MSscan-MSW)/n.id))
)
ICC2r.aov
#+END_SRC

#+RESULTS:
:  consistency.single    agreement.single consistency.average   agreement.average 
:           0.8057232           0.8001849           0.9539944           0.9524334

** using existing packages
#+BEGIN_SRC R :results output :exports both :session *R* :cache no 
tt.single <- c(
    iccC = irr::icc(dfW.icc2[,c("Y1", "Y2", "Y3", "Y4", "Y5")],
                    model="twoway", type="consistency")$value,
    irrA = irr::icc(dfW.icc2[,c("Y1", "Y2", "Y3", "Y4", "Y5")],
                    model="twoway", type="agreement")$value,
    psych = psych::ICC(dfW.icc2[,c("Y1", "Y2", "Y3", "Y4", "Y5")])[[1]]$ICC[3:2]
)

tt.average <- c(
    iccC = irr::icc(dfW.icc2[,c("Y1", "Y2", "Y3", "Y4", "Y5")],
                    model="twoway", type="consistency", unit = "average")$value,
    iccA = irr::icc(dfW.icc2[,c("Y1", "Y2", "Y3", "Y4", "Y5")],
                    model="twoway", type="agreement", unit = "average")$value,
    psych = psych::ICC(dfW.icc2[,c("Y1", "Y2", "Y3", "Y4", "Y5")])[[1]]$ICC[6:5]
)
rbind(single = tt.single, average = tt.average)
#+END_SRC

#+RESULTS:
:              iccC      irrA    psych1    psych2
: single  0.8057232 0.8001849 0.8057243 0.8001868
: average 0.9539944 0.9524334 0.9539947 0.9524339

\clearpage

* Different correlation between sessions

When considering more than 2 sessions, the previous ICC assume the
same correlation between sessions (or raters). This can be relaxed
using an unstructured covariance matrix:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
gls_heteroC <- gls(Y ~ session,
                   correlation = corSymm(form = ~ 1|Id),
                   data = dtL.icc2)

# correlation matrix
M.icc <- unclass(cov2cor(getVarCov(gls_heteroC)))
print(M.icc)
#+END_SRC

#+RESULTS:
:           [,1]      [,2]      [,3]      [,4]      [,5]
: [1,] 1.0000000 0.8257161 0.6932362 0.8742870 0.7906416
: [2,] 0.8257161 1.0000000 0.7640218 0.7507233 0.8421197
: [3,] 0.6932362 0.7640218 1.0000000 0.5166736 0.6906414
: [4,] 0.8742870 0.7507233 0.5166736 1.0000000 0.5647855
: [5,] 0.7906416 0.8421197 0.6906414 0.5647855 1.0000000

Note that the mean ICC:
#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
c(mean = mean(setdiff(unique(M.icc),1)), 
  indiv = apply(M.icc, 1, function(x){mean(setdiff(x,1))}))
#+END_SRC

#+RESULTS:
:      mean    indiv1    indiv2    indiv3    indiv4    indiv5 
: 0.7312846 0.7959702 0.7956452 0.6661432 0.6766173 0.7220470

does not match the "normal" ICC:
#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports both :results output :session *R* :cache yes 
gls_homoC <- gls(Y ~ session,
                 correlation = corCompSymm(form = ~ 1|Id),
                 data = dtL.icc2)

# correlation matrix
unclass(cov2cor(getVarCov(gls_homoC)))
#+END_SRC

#+RESULTS[<2021-03-08 10:55:11> 790b9e6b10bda97286ac92c45cde0ea1910b03f5]:
:           [,1]      [,2]      [,3]      [,4]      [,5]
: [1,] 1.0000000 0.8057232 0.8057232 0.8057232 0.8057232
: [2,] 0.8057232 1.0000000 0.8057232 0.8057232 0.8057232
: [3,] 0.8057232 0.8057232 1.0000000 0.8057232 0.8057232
: [4,] 0.8057232 0.8057232 0.8057232 1.0000000 0.8057232
: [5,] 0.8057232 0.8057232 0.8057232 0.8057232 1.0000000

\clearpage

/Note:/ small difference between the function =icc= and
=gls=. Due to non optimal optimization in =gls=?

#+BEGIN_SRC R :exports both :results output :session *R* :cache yes 
irr::icc(dfW.icc2[,c("Y1", "Y2", "Y3", "Y4", "Y5")],
         model="oneway", type="consistency")$value
#+END_SRC

#+RESULTS[<2017-07-01 21:49:04> b5b0d239f1cdc28f670b3bc9b94e79eb87657c71]:
: [1] 0.7999099


* CONFIG :noexport:
#+LANGUAGE:  en
#+LaTeX_CLASS: org-article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+OPTIONS:   title:t author:t toc:nil todo:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t

** Display of the document
# ## space between lines
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER:\renewcommand{\baselinestretch}{1.1}

# ## margins
#+LATEX_HEADER:\geometry{top=1cm}

# ## personalize the prefix in the name of the sections
#+LaTeX_HEADER: \usepackage{titlesec}
# ## fix bug in titlesec version
# ##  https://tex.stackexchange.com/questions/299969/titlesec-loss-of-section-numbering-with-the-new-update-2016-03-15
#+LaTeX_HEADER: \usepackage{etoolbox}
#+LaTeX_HEADER: 
#+LaTeX_HEADER: \makeatletter
#+LaTeX_HEADER: \patchcmd{\ttlh@hang}{\parindent\z@}{\parindent\z@\leavevmode}{}{}
#+LaTeX_HEADER: \patchcmd{\ttlh@hang}{\noindent}{}{}{}
#+LaTeX_HEADER: \makeatother

** Color
# ## define new colors
#+LATEX_HEADER: \RequirePackage{colortbl} % arrayrulecolor to mix colors
#+LaTeX_HEADER: \definecolor{myorange}{rgb}{1,0.2,0}
#+LaTeX_HEADER: \definecolor{mypurple}{rgb}{0.7,0,8}
#+LaTeX_HEADER: \definecolor{mycyan}{rgb}{0,0.6,0.6}
#+LaTeX_HEADER: \newcommand{\lightblue}{blue!50!white}
#+LaTeX_HEADER: \newcommand{\darkblue}{blue!80!black}
#+LaTeX_HEADER: \newcommand{\darkgreen}{green!50!black}
#+LaTeX_HEADER: \newcommand{\darkred}{red!50!black}
#+LaTeX_HEADER: \definecolor{gray}{gray}{0.5}

# ## change the color of the links
#+LaTeX_HEADER: \hypersetup{
#+LaTeX_HEADER:  citecolor=[rgb]{0,0.5,0},
#+LaTeX_HEADER:  urlcolor=[rgb]{0,0,0.5},
#+LaTeX_HEADER:  linkcolor=[rgb]{0,0,0.5},
#+LaTeX_HEADER: }

** Font
# https://tex.stackexchange.com/questions/25249/how-do-i-use-a-particular-font-for-a-small-section-of-text-in-my-document
#+LaTeX_HEADER: \newenvironment{comment}{\small \color{gray}\fontfamily{lmtt}\selectfont}{\par}
#+LaTeX_HEADER: \newenvironment{activity}{\color{orange}\fontfamily{qzc}\selectfont}{\par}

** Symbols
# ## valid and cross symbols
#+LaTeX_HEADER: \RequirePackage{pifont}
#+LaTeX_HEADER: \RequirePackage{relsize}
#+LaTeX_HEADER: \newcommand{\Cross}{{\raisebox{-0.5ex}%
#+LaTeX_HEADER:		{\relsize{1.5}\ding{56}}}\hspace{1pt} }
#+LaTeX_HEADER: \newcommand{\Valid}{{\raisebox{-0.5ex}%
#+LaTeX_HEADER:		{\relsize{1.5}\ding{52}}}\hspace{1pt} }
#+LaTeX_HEADER: \newcommand{\CrossR}{ \textcolor{red}{\Cross} }
#+LaTeX_HEADER: \newcommand{\ValidV}{ \textcolor{green}{\Valid} }

# ## warning symbol
#+LaTeX_HEADER: \usepackage{stackengine}
#+LaTeX_HEADER: \usepackage{scalerel}
#+LaTeX_HEADER: \newcommand\Warning[1][3ex]{%
#+LaTeX_HEADER:   \renewcommand\stacktype{L}%
#+LaTeX_HEADER:   \scaleto{\stackon[1.3pt]{\color{red}$\triangle$}{\tiny\bfseries !}}{#1}%
#+LaTeX_HEADER:   \xspace
#+LaTeX_HEADER: }

# # R Software
#+LATEX_HEADER: \newcommand\Rlogo{\textbf{\textsf{R}}\xspace} % 

** Code
# Documentation at https://org-babel.readthedocs.io/en/latest/header-args/#results
# :tangle (yes/no/filename) extract source code with org-babel-tangle-file, see http://orgmode.org/manual/Extracting-source-code.html 
# :cache (yes/no)
# :eval (yes/no/never)
# :results (value/output/silent/graphics/raw/latex)
# :export (code/results/none/both)
#+PROPERTY: header-args :session *R* :tangle yes :cache no ## extra argument need to be on the same line as :session *R*

# Code display:
#+LATEX_HEADER: \RequirePackage{fancyvrb}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small,formatcom = {\color[rgb]{0.5,0,0}}}

# ## change font size input (global change)
# ## doc: https://ctan.math.illinois.edu/macros/latex/contrib/listings/listings.pdf
# #+LATEX_HEADER: \newskip \skipamount    \skipamount =6pt plus 0pt minus 6pt
#+LATEX_HEADER: \lstdefinestyle{code-tiny}{basicstyle=\ttfamily\footnotesize}
# #+LATEX_HEADER: \lstset{style=code-tiny}
# ## change font size input (local change, put just before BEGIN_SRC)
# ## #+ATTR_LATEX: :options basicstyle=\ttfamily\scriptsize
# ## change font size output (global change)
# ## \RecustomVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\tiny,formatcom = {\color[rgb]{0.5,0,0}}}

** Lists
#+LATEX_HEADER: \RequirePackage{enumitem} % better than enumerate

** Image and graphs
#+LATEX_HEADER: \RequirePackage{epstopdf} % to be able to convert .eps to .pdf image files
#+LATEX_HEADER: \RequirePackage{capt-of} % 
#+LATEX_HEADER: \RequirePackage{caption} % newlines in graphics

#+LaTeX_HEADER: \RequirePackage{tikz-cd} % graph
# ## https://tools.ietf.org/doc/texlive-doc/latex/tikz-cd/tikz-cd-doc.pdf

** Table
#+LATEX_HEADER: \RequirePackage{booktabs} % for nice lines in table (e.g. toprule, bottomrule, midrule, cmidrule)

** Inline latex
# @@latex:any arbitrary LaTeX code@@


** Algorithm
#+LATEX_HEADER: \RequirePackage{amsmath}
#+LATEX_HEADER: \RequirePackage{algorithm}
#+LATEX_HEADER: \RequirePackage[noend]{algpseudocode}

** Math
#+LATEX_HEADER: \RequirePackage{dsfont}
#+LATEX_HEADER: \RequirePackage{amsmath,stmaryrd,graphicx}
#+LATEX_HEADER: \RequirePackage{prodint} % product integral symbol (\PRODI)

# ## lemma
# #+LaTeX_HEADER: \RequirePackage{amsthm}
# #+LaTeX_HEADER: \newtheorem{theorem}{Theorem}
# #+LaTeX_HEADER: \newtheorem{lemma}[theorem]{Lemma}

*** Template for shortcut
#+LATEX_HEADER: \usepackage{ifthen}
#+LATEX_HEADER: \usepackage{xifthen}
#+LATEX_HEADER: \usepackage{xargs}
#+LATEX_HEADER: \usepackage{xspace}

#+LATEX_HEADER: \newcommand\defOperator[7]{%
#+LATEX_HEADER:	\ifthenelse{\isempty{#2}}{
#+LATEX_HEADER:		\ifthenelse{\isempty{#1}}{#7{#3}#4}{#7{#3}#4 \left#5 #1 \right#6}
#+LATEX_HEADER:	}{
#+LATEX_HEADER:	\ifthenelse{\isempty{#1}}{#7{#3}#4_{#2}}{#7{#3}#4_{#1}\left#5 #2 \right#6}
#+LATEX_HEADER: }
#+LATEX_HEADER: }

#+LATEX_HEADER: \newcommand\defUOperator[5]{%
#+LATEX_HEADER: \ifthenelse{\isempty{#1}}{
#+LATEX_HEADER:		#5\left#3 #2 \right#4
#+LATEX_HEADER: }{
#+LATEX_HEADER:	\ifthenelse{\isempty{#2}}{\underset{#1}{\operatornamewithlimits{#5}}}{
#+LATEX_HEADER:		\underset{#1}{\operatornamewithlimits{#5}}\left#3 #2 \right#4}
#+LATEX_HEADER: }
#+LATEX_HEADER: }

#+LATEX_HEADER: \newcommand{\defBoldVar}[2]{	
#+LATEX_HEADER:	\ifthenelse{\equal{#2}{T}}{\boldsymbol{#1}}{\mathbf{#1}}
#+LATEX_HEADER: }

**** Probability
#+LATEX_HEADER: \newcommandx\Esp[2][1=,2=]{\defOperator{#1}{#2}{E}{}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Prob[2][1=,2=]{\defOperator{#1}{#2}{P}{}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Qrob[2][1=,2=]{\defOperator{#1}{#2}{Q}{}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Var[2][1=,2=]{\defOperator{#1}{#2}{V}{ar}{\lbrack}{\rbrack}{\mathbb}}
#+LATEX_HEADER: \newcommandx\Cov[2][1=,2=]{\defOperator{#1}{#2}{C}{ov}{\lbrack}{\rbrack}{\mathbb}}

#+LATEX_HEADER: \newcommandx\Binom[2][1=,2=]{\defOperator{#1}{#2}{B}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Gaus[2][1=,2=]{\defOperator{#1}{#2}{N}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Wishart[2][1=,2=]{\defOperator{#1}{#2}{W}{ishart}{(}{)}{\mathcal}}

#+LATEX_HEADER: \newcommandx\Likelihood[2][1=,2=]{\defOperator{#1}{#2}{L}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\logLikelihood[2][1=,2=]{\defOperator{#1}{#2}{\ell}{}{(}{)}{}}
#+LATEX_HEADER: \newcommandx\Information[2][1=,2=]{\defOperator{#1}{#2}{I}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Score[2][1=,2=]{\defOperator{#1}{#2}{S}{}{(}{)}{\mathcal}}

**** Operators
#+LATEX_HEADER: \newcommandx\Vois[2][1=,2=]{\defOperator{#1}{#2}{V}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\IF[2][1=,2=]{\defOperator{#1}{#2}{IF}{}{(}{)}{\mathcal}}
#+LATEX_HEADER: \newcommandx\Ind[1][1=]{\defOperator{}{#1}{1}{}{(}{)}{\mathds}}

#+LATEX_HEADER: \newcommandx\Max[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{min}}
#+LATEX_HEADER: \newcommandx\Min[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{max}}
#+LATEX_HEADER: \newcommandx\argMax[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{argmax}}
#+LATEX_HEADER: \newcommandx\argMin[2][1=,2=]{\defUOperator{#1}{#2}{(}{)}{argmin}}
#+LATEX_HEADER: \newcommandx\cvD[2][1=D,2=n \rightarrow \infty]{\xrightarrow[#2]{#1}}

#+LATEX_HEADER: \newcommandx\Hypothesis[2][1=,2=]{
#+LATEX_HEADER:         \ifthenelse{\isempty{#1}}{
#+LATEX_HEADER:         \mathcal{H}
#+LATEX_HEADER:         }{
#+LATEX_HEADER: 	\ifthenelse{\isempty{#2}}{
#+LATEX_HEADER: 		\mathcal{H}_{#1}
#+LATEX_HEADER: 	}{
#+LATEX_HEADER: 	\mathcal{H}^{(#2)}_{#1}
#+LATEX_HEADER:         }
#+LATEX_HEADER:         }
#+LATEX_HEADER: }

#+LATEX_HEADER: \newcommandx\dpartial[4][1=,2=,3=,4=\partial]{
#+LATEX_HEADER: 	\ifthenelse{\isempty{#3}}{
#+LATEX_HEADER: 		\frac{#4 #1}{#4 #2}
#+LATEX_HEADER: 	}{
#+LATEX_HEADER: 	\left.\frac{#4 #1}{#4 #2}\right\rvert_{#3}
#+LATEX_HEADER: }
#+LATEX_HEADER: }

#+LATEX_HEADER: \newcommandx\dTpartial[3][1=,2=,3=]{\dpartial[#1][#2][#3][d]}

#+LATEX_HEADER: \newcommandx\ddpartial[3][1=,2=,3=]{
#+LATEX_HEADER: 	\ifthenelse{\isempty{#3}}{
#+LATEX_HEADER: 		\frac{\partial^{2} #1}{\partial #2^2}
#+LATEX_HEADER: 	}{
#+LATEX_HEADER: 	\frac{\partial^2 #1}{\partial #2\partial #3}
#+LATEX_HEADER: }
#+LATEX_HEADER: } 

**** General math
#+LATEX_HEADER: \newcommand\Real{\mathbb{R}}
#+LATEX_HEADER: \newcommand\Rational{\mathbb{Q}}
#+LATEX_HEADER: \newcommand\Natural{\mathbb{N}}
#+LATEX_HEADER: \newcommand\trans[1]{{#1}^\intercal}%\newcommand\trans[1]{{\vphantom{#1}}^\top{#1}}
#+LATEX_HEADER: \newcommand{\independent}{\mathrel{\text{\scalebox{1.5}{$\perp\mkern-10mu\perp$}}}}
#+LaTeX_HEADER: \newcommand\half{\frac{1}{2}}
#+LaTeX_HEADER: \newcommand\normMax[1]{\left|\left|#1\right|\right|_{max}}
#+LaTeX_HEADER: \newcommand\normTwo[1]{\left|\left|#1\right|\right|_{2}}

#+LATEX_HEADER: \newcommand\Veta{\boldsymbol{\eta}}
#+LATEX_HEADER: \newcommand\VX{\mathbf{X}}


** Notations
