#+TITLE:
#+Author: Brice Ozenne


* Descriptive

"Characteristics of the study population were presented as count ..."
"P-value below 0.05 was considered statistically significant"
# @@latex:any arbitrary LaTeX code@@

* Regression
"Residuals were visually inspected for normality"

"The addition of model paths was considered iteratively, based on Score
tests of improvement in model fit with a false-discovery rate of 0.05
(Benjamini–Hochbergfalse-discovery rate-corrected) across all possible
paths.

"Cox regression was performed to model effects of YYY on the
outcome-specific hazard rates. In all Cox regression analyses the
baseline hazard function was stratified by XXX".

* ATE

[long]
"The instantaneous risk of each event (XXX and death) were modeled
using cause-specific Cox regression where the aforementioned
covariates were used as repressors and using a treatment-specific
baseline hazard function. For each treatment modality, the
patient-specific absolute risk of an event was then computed as the
instantaneous risk of this event times its probability of being
event-free, cumulated over time. The standardized absolute risk was
then obtained by averaging the patient-specific risks for each
treatment modality over the whole cohort. Difference in standardized
risks can be attributed to the treatment effect under certain
assumptions [REF. section 13.5 in the book Causal inference what if by
Hernan and Robin], including no missing confounder in the
cause-specific Cox regressions."

[short]
 "Average treatment effects were reported as differences of the
absolute risks standardized to each of the treatments (g-formula)"

"... if assumptions met ..., the average treatment effects can be
interpreted as what one would have observed in arandomized clinical
trial."

* Mixed model
Changes in bodyweight over time were analyzed using a linear mixed
model which included follow-up time (categorical) as fixed effect and
which further assumed an unstructured covariance pattern to account
for repleated measurements on the same subjects.

* Review
Dear Prof. =XXX=, Thank you for considering our manuscript =XXX= for
publication in =XXX= and for the opportunity to submit a revised
version.  We hereby address, point by point, the comments and requests
raised by the reviewers. In the following reply, the reviewers' text
is marked in italics and we have assigned point numbers for each
comment. Our responses are marked with in blue commencing with
"Reply". The resulting changes in the manuscript are noted in blue
italics.  In addition to the point-by-point reply, we also submit a
revised version of the manuscript with corrections marked in bold.
Please do not hesitate to contact me, should you require additional
information.  

Yours Sincerely, 
The corresponding author

* CONFIG :noexport:
# #+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen, Copenhagen, Denmark}
#+LANGUAGE:  en
#+LaTeX_CLASS: org-article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+OPTIONS:   title:t author:t toc:nil todo:nil
#+OPTIONS:   H:3 num:t 
#+OPTIONS:   TeX:t LaTeX:t

#+LATEX_HEADER: %
#+LATEX_HEADER: %%%% specifications %%%%
#+LATEX_HEADER: %

** Latex command
#+LATEX_HEADER: \usepackage{ifthen}
#+LATEX_HEADER: \usepackage{xifthen}
#+LATEX_HEADER: \usepackage{xargs}
#+LATEX_HEADER: \usepackage{xspace}

#+LATEX_HEADER: \newcommand\Rlogo{\textbf{\textsf{R}}\xspace} % 

** Notations

** Code
# Documentation at https://org-babel.readthedocs.io/en/latest/header-args/#results
# :tangle (yes/no/filename) extract source code with org-babel-tangle-file, see http://orgmode.org/manual/Extracting-source-code.html 
# :cache (yes/no)
# :eval (yes/no/never)
# :results (value/output/silent/graphics/raw/latex)
# :export (code/results/none/both)
#+PROPERTY: header-args :session *R* :tangle yes :cache no ## extra argument need to be on the same line as :session *R*

# Code display:
#+LATEX_HEADER: \RequirePackage{fancyvrb}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small,formatcom = {\color[rgb]{0.5,0,0}}}

# ## change font size input
# ## #+ATTR_LATEX: :options basicstyle=\ttfamily\scriptsize
# ## change font size output
# ## \RecustomVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\tiny,formatcom = {\color[rgb]{0.5,0,0}}}

** Display 
#+LATEX_HEADER: \RequirePackage{colortbl} % arrayrulecolor to mix colors
#+LATEX_HEADER: \RequirePackage{setspace} % to modify the space between lines - incompatible with footnote in beamer
#+LaTeX_HEADER:\renewcommand{\baselinestretch}{1.1}
#+LATEX_HEADER:\geometry{top=1cm}

** Image
#+LATEX_HEADER: \RequirePackage{epstopdf} % to be able to convert .eps to .pdf image files
#+LATEX_HEADER: \RequirePackage{capt-of} % 
#+LATEX_HEADER: \RequirePackage{caption} % newlines in graphics
